/*! flashcards-9.js — Phase 5 (Interview & Bewerbung) + Gehalt/Karriere/Kunde deck (Đợt 7).
 * Merges onto window.FLASHCARDS.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- Phase 5 · Grammar ---- */
  { id:"fc6001", de:"Werdegang", article:"der", plural:"die Werdegänge", en:"career path, background", vi:"quá trình sự nghiệp", ex:"Erzählen Sie kurz etwas zu Ihrem Werdegang.", exEn:"Tell us briefly about your career path.", ipa:"VEER-de-gang", coll:"den Werdegang schildern", tip:"Umlaut im Plural. Gesprochen im Perfekt erzählen, geschrieben im Präteritum.", topic:"Career", level:"C1" },
  { id:"fc6002", de:"Relativpronomen", article:"das", plural:"die Relativpronomen", en:"relative pronoun", vi:"đại từ quan hệ", ex:"Ich bin jemand, der Verantwortung übernimmt.", exEn:"I'm someone who takes responsibility.", ipa:"re-la-TEEF-pro-noo-men", coll:"das Relativpronomen richtig setzen", tip:"Genus vom Bezugswort, Kasus vom eigenen Satz.", topic:"Grammar", level:"C1" },
  { id:"fc6003", de:"Bezugswort", article:"das", plural:"die Bezugswörter", en:"antecedent", vi:"từ được thay thế", ex:"Das Bezugswort bestimmt das Genus des Relativpronomens.", exEn:"The antecedent determines the pronoun's gender.", ipa:"be-TSUUKS-vort", coll:"sich auf das Bezugswort beziehen", tip:"Steht immer direkt vor dem Relativsatz.", topic:"Grammar", level:"C1" },
  { id:"fc6004", de:"hineinwachsen", article:"—", plural:"—", en:"to grow into (a role)", vi:"phát triển dần vào", ex:"Ich würde gern langfristig in eine Architektenrolle hineinwachsen.", exEn:"I'd like to grow into an architect role long-term.", ipa:"hi-NAYN-vak-sen", coll:"in eine Rolle hineinwachsen", tip:"Trennbar. Zeigt Ehrgeiz ohne Anspruch.", topic:"Career", level:"C1" },
  { id:"fc6005", de:"federführend", article:"—", plural:"—", en:"leading, in charge of", vi:"chủ trì", ex:"Die Migration habe ich federführend verantwortet.", exEn:"I led the migration.", ipa:"FEE-der-füü-rent", coll:"federführend verantworten", tip:"Schriftsprache — perfekt für den Lebenslauf, zu steif fürs Gespräch.", topic:"Career", level:"C1" },
  { id:"fc6006", de:"Rahmen", article:"der", plural:"die Rahmen", en:"range (salary), framework", vi:"khung lương", ex:"Wie sieht Ihr Rahmen für diese Position aus?", exEn:"What does your range look like for this role?", ipa:"RAA-men", coll:"einen Rahmen vorsehen", tip:"Plural = Singular. Die höflichste Art, nach der Gehaltsspanne zu fragen.", topic:"Career", level:"C1" },

  /* ---- Phase 5 · Vocabulary (HR & Vertrag) ---- */
  { id:"fc6007", de:"Arbeitszeugnis", article:"das", plural:"die Arbeitszeugnisse", en:"employer reference letter", vi:"thư chứng nhận công việc", ex:"„Stets zu unserer vollsten Zufriedenheit“ entspricht der Note sehr gut.", exEn:"'Always to our fullest satisfaction' equals a top grade.", ipa:"AR-byts-tsoyk-nis", coll:"ein Arbeitszeugnis ausstellen", tip:"Muss wohlwollend UND wahr sein — daher die Codesprache.", topic:"Career", level:"C1" },
  { id:"fc6008", de:"Festanstellung", article:"die", plural:"die Festanstellungen", en:"permanent employment", vi:"hợp đồng chính thức", ex:"Ich bin derzeit in Festanstellung.", exEn:"I'm currently in permanent employment.", ipa:"FEST-an-shtel-ung", coll:"in Festanstellung sein", tip:"Gegenteil im Alltag: freiberuflich, befristet.", topic:"Career", level:"B2" },
  { id:"fc6009", de:"Probezeit", article:"die", plural:"die Probezeiten", en:"probation period", vi:"thời gian thử việc", ex:"Die Stelle ist unbefristet, mit sechs Monaten Probezeit.", exEn:"The position is permanent, with six months' probation.", ipa:"PROO-be-tsyt", coll:"in der Probezeit sein", tip:"Sechs Monate sind die gesetzliche Höchstdauer.", topic:"Career", level:"B2" },
  { id:"fc6010", de:"Eintrittstermin", article:"der", plural:"die Eintrittstermine", en:"starting date", vi:"ngày bắt đầu", ex:"Nennen Sie bitte Ihren frühestmöglichen Eintrittstermin.", exEn:"Please state your earliest possible starting date.", ipa:"AYN-trits-ter-meen", coll:"den Eintrittstermin nennen", tip:"Folgt aus der Kündigungsfrist — beide zusammen lernen.", topic:"Career", level:"B2" },
  { id:"fc6011", de:"Wechselmotivation", article:"die", plural:"—", en:"reason for changing jobs", vi:"lý do chuyển việc", ex:"Nach der Wechselmotivation wird in fast jedem Gespräch gefragt.", exEn:"Almost every interview asks about your reason for moving.", ipa:"VEK-sel-mo-ti-va-tsyoon", coll:"die Wechselmotivation darlegen", tip:"Antwort zeigt nach vorn — nie Kritik am jetzigen Arbeitgeber.", topic:"Career", level:"C1" },
  { id:"fc6012", de:"Urlaubsanspruch", article:"der", plural:"die Urlaubsansprüche", en:"holiday entitlement", vi:"quyền nghỉ phép", ex:"Der Urlaubsanspruch liegt bei dreißig Tagen im Jahr.", exEn:"Holiday entitlement is thirty days a year.", ipa:"UR-laups-an-shprukh", coll:"Urlaubsanspruch haben", tip:"30 Tage sind branchenüblich; das Gesetz verlangt weniger.", topic:"Career", level:"B2" },
  { id:"fc6013", de:"Gegenmaßnahme", article:"die", plural:"die Gegenmaßnahmen", en:"countermeasure", vi:"biện pháp khắc phục", ex:"Nenne eine echte Schwäche und deine Gegenmaßnahme.", exEn:"Name a real weakness and your countermeasure.", ipa:"GEE-gen-maas-naa-me", coll:"eine Gegenmaßnahme ergreifen", tip:"Die Schwäche ohne Gegenmaßnahme gilt als Ausweichen.", topic:"Career", level:"C1" },
  { id:"fc6014", de:"aushandeln", article:"—", plural:"—", en:"to negotiate (to a result)", vi:"đàm phán ra kết quả", ex:"Das Gehalt haben wir in zwei Gesprächen ausgehandelt.", exEn:"We negotiated the salary over two conversations.", ipa:"AUS-han-deln", coll:"ein Gehalt aushandeln", tip:"*verhandeln über* = der Vorgang, *aushandeln* = mit Ergebnis.", topic:"Career", level:"C1" },
  { id:"fc6015", de:"wohlwollend", article:"—", plural:"—", en:"benevolent, favourable", vi:"thiện chí", ex:"Ein Arbeitszeugnis muss wohlwollend formuliert sein.", exEn:"A reference letter must be worded favourably.", ipa:"VOOL-vol-lent", coll:"wohlwollend formulieren", tip:"Rechtsbegriff — er erzwingt die Codesprache im Zeugnis.", topic:"Career", level:"C1" },

  /* ---- Phase 5 · Speaking ---- */
  { id:"fc6016", de:"Selbstvorstellung", article:"die", plural:"die Selbstvorstellungen", en:"self-introduction", vi:"phần tự giới thiệu", ex:"Die Selbstvorstellung dauert etwa neunzig Sekunden.", exEn:"The self-introduction runs about ninety seconds.", ipa:"ZELPST-for-shtel-ung", coll:"die Selbstvorstellung üben", tip:"Drei Beats: Jetzt → Werdegang → Warum hier.", topic:"Career", level:"C1" },
  { id:"fc6017", de:"Betriebsaufwand", article:"der", plural:"—", en:"operational overhead", vi:"chi phí vận hành", ex:"Der Nachteil wäre der höhere Betriebsaufwand.", exEn:"The downside would be higher operational overhead.", ipa:"be-TREEPS-auf-vant", coll:"der Betriebsaufwand steigt", tip:"Standardwort für die Nachteil-Seite eines Trade-offs.", topic:"Architecture", level:"C1" },
  { id:"fc6018", de:"mitgestalten", article:"—", plural:"—", en:"to help shape", vi:"cùng định hình", ex:"Ich möchte Entscheidungen mitgestalten, nicht nur umsetzen.", exEn:"I want to help shape decisions, not just implement them.", ipa:"MIT-ge-shtal-ten", coll:"Entscheidungen mitgestalten", tip:"Trennbar. Der Standardsatz für die Wechselmotivation.", topic:"Career", level:"C1" },
  { id:"fc6019", de:"Rufbereitschaft", article:"die", plural:"die Rufbereitschaften", en:"on-call duty", vi:"trực sẵn sàng", ex:"Wie stehen Sie zur Rufbereitschaft im Wechsel?", exEn:"How do you feel about rotating on-call duty?", ipa:"RUUF-be-ryt-shaft", coll:"Rufbereitschaft übernehmen", tip:"Steht oft im Nebensatz der Anzeige — nach Häufigkeit und Ausgleich fragen.", topic:"DevOps", level:"B2" },

  /* ---- Phase 5 · Listening (Telefon & Zahlen) ---- */
  { id:"fc6020", de:"Eckdaten", article:"die", plural:"(Plural)", en:"key figures, headline terms", vi:"các thông số chính", ex:"Zu den Eckdaten: Das Jahresgehalt liegt bei achtundsechzigtausend Euro.", exEn:"On the key terms: the annual salary is €68,000.", ipa:"EK-daa-ten", coll:"die Eckdaten nennen", tip:"Signalwort: Jetzt kommen die Zahlen — Stift bereithalten.", topic:"Career", level:"C1" },
  { id:"fc6021", de:"Jahresgehalt", article:"das", plural:"die Jahresgehälter", en:"annual salary", vi:"lương năm", ex:"Deutsche Gehälter werden als Jahresgehalt brutto genannt.", exEn:"German salaries are quoted as gross annual pay.", ipa:"YAA-res-ge-halt", coll:"das Jahresgehalt verhandeln", tip:"Immer brutto, immer pro Jahr. Umlaut im Plural.", topic:"Career", level:"B2" },
  { id:"fc6022", de:"variabler Anteil", article:"der", plural:"die Anteile", en:"variable component, bonus", vi:"phần thưởng biến đổi", ex:"Dazu kommt ein variabler Anteil von bis zu fünf Prozent.", exEn:"Plus a variable component of up to five percent.", ipa:"va-ri-AA-bler AN-tyl", coll:"an Ziele gekoppelt sein", tip:"Immer fragen: an Unternehmens- oder Teamziele gekoppelt?", topic:"Career", level:"C1" },
  { id:"fc6023", de:"mobiles Arbeiten", article:"das", plural:"—", en:"remote work", vi:"làm việc từ xa", ex:"Zwei Tage mobiles Arbeiten pro Woche nach Absprache.", exEn:"Two days of remote work per week by arrangement.", ipa:"MOO-bi-les AR-by-ten", coll:"mobiles Arbeiten vereinbaren", tip:"Amtlicher als „Homeoffice“ und in Anzeigen häufiger.", topic:"Workplace", level:"B2" },
  { id:"fc6024", de:"paraphrasieren", article:"—", plural:"—", en:"to paraphrase back", vi:"diễn giải lại", ex:"Habe ich das richtig verstanden — Sie meinen zwei Tage vor Ort?", exEn:"Did I understand correctly — you mean two days on site?", ipa:"pa-ra-fra-ZEE-ren", coll:"eine Aussage paraphrasieren", tip:"Die stärkste Rettungstechnik am Telefon.", topic:"Speaking", level:"C1" },

  /* ---- Phase 5 · Reading (Stellenanzeige) ---- */
  { id:"fc6025", de:"Stellenanzeige", article:"die", plural:"die Stellenanzeigen", en:"job advertisement", vi:"tin tuyển dụng", ex:"Mit großem Interesse habe ich Ihre Stellenanzeige gelesen.", exEn:"I read your job ad with great interest.", ipa:"SHTEL-len-an-tsy-ge", coll:"auf eine Stellenanzeige antworten", tip:"Kopf: die Anzeige → die.", topic:"Career", level:"B2" },
  { id:"fc6026", de:"Kennziffer", article:"die", plural:"die Kennziffern", en:"reference number", vi:"mã số vị trí", ex:"Bewerbung als Backend-Entwickler:in, Kennziffer BE-2291.", exEn:"Application as backend developer, ref. BE-2291.", ipa:"KEN-tsi-fer", coll:"unter Angabe der Kennziffer", tip:"Gehört in den Betreff — sonst muss jemand deine Bewerbung von Hand zuordnen.", topic:"Career", level:"C1" },
  { id:"fc6027", de:"voraussetzen", article:"—", plural:"—", en:"to require, to presuppose", vi:"yêu cầu bắt buộc", ex:"Mehrjährige Erfahrung mit Java setzen wir voraus.", exEn:"We require several years of Java experience.", ipa:"for-AUS-zets-en", coll:"etwas voraussetzen", tip:"Härtestes Muss-Signal. Trennbar: setzen … voraus.", topic:"Career", level:"C1" },
  { id:"fc6028", de:"wünschenswert", article:"—", plural:"—", en:"desirable", vi:"mong muốn có", ex:"Erfahrung mit Kafka ist wünschenswert.", exEn:"Kafka experience is desirable.", ipa:"VÜN-shens-veert", coll:"wünschenswert sein", tip:"Kann-Signal wie *von Vorteil* und *idealerweise* — kein Ausschlusskriterium.", topic:"Career", level:"B2" },
  { id:"fc6029", de:"fundiert", article:"—", plural:"—", en:"well-founded, solid", vi:"vững vàng", ex:"Fundierte Kenntnisse in Spring Boot sind erforderlich.", exEn:"Solid knowledge of Spring Boot is required.", ipa:"fun-DEERT", coll:"fundierte Kenntnisse", tip:"Leiter: Grundkenntnisse < gute < fundierte < einschlägige Erfahrung.", topic:"Career", level:"C1" },
  { id:"fc6030", de:"Weiterbildungsbudget", article:"das", plural:"die Weiterbildungsbudgets", en:"training budget", vi:"ngân sách đào tạo", ex:"Wir bieten ein jährliches Weiterbildungsbudget von 1.500 Euro.", exEn:"We offer an annual training budget of €1,500.", ipa:"VY-ter-bil-dungs-büd-zheh", coll:"das Budget ausschöpfen", tip:"Leichter zu erhöhen als das Fixgehalt — guter Verhandlungshebel.", topic:"Career", level:"B2" },
  { id:"fc6031", de:"betriebliche Altersvorsorge", article:"die", plural:"—", en:"company pension scheme", vi:"quỹ hưu trí công ty", ex:"Zum Paket gehört eine betriebliche Altersvorsorge.", exEn:"The package includes a company pension scheme.", ipa:"be-TREEP-li-khe AL-ters-for-zor-ge", coll:"bAV-Zuschuss", tip:"Abkürzung bAV. Nach dem Arbeitgeberanteil fragen.", topic:"Career", level:"C1" },
  { id:"fc6032", de:"Zuschuss", article:"der", plural:"die Zuschüsse", en:"subsidy, contribution", vi:"khoản trợ cấp", ex:"Es gibt einen Zuschuss zum Deutschlandticket.", exEn:"There's a subsidy for the Deutschlandticket.", ipa:"TSUU-shus", coll:"einen Zuschuss gewähren", tip:"Teilbetrag, nicht Vollübernahme — nach der Höhe fragen.", topic:"Career", level:"B2" },
  { id:"fc6033", de:"Ablösung", article:"die", plural:"die Ablösungen", en:"replacement, phase-out", vi:"thay thế dần", ex:"Du wirkst an der schrittweisen Ablösung des Monolithen mit.", exEn:"You'll help phase out the monolith step by step.", ipa:"AP-löö-zung", coll:"die Ablösung eines Systems", tip:"In der Anzeige ein ehrliches Signal: Es gibt Legacy-Code.", topic:"Architecture", level:"C1" },

  /* ---- Phase 5 · Writing (Bewerbung) ---- */
  { id:"fc6034", de:"Anlage", article:"die", plural:"die Anlagen", en:"enclosure, attachment", vi:"tài liệu đính kèm", ex:"Anlagen: Lebenslauf, Zeugnisse.", exEn:"Enclosures: CV, references.", ipa:"AN-laa-ge", coll:"Anlagen beifügen", tip:"Die Zeile steht unter dem Namen im Anschreiben.", topic:"Writing", level:"B2" },
  { id:"fc6035", de:"Familienstand", article:"der", plural:"—", en:"marital status", vi:"tình trạng hôn nhân", ex:"Familienstand und Geburtsdatum sind im Lebenslauf freiwillig.", exEn:"Marital status and date of birth are optional in the CV.", ipa:"fa-MEE-li-en-shtant", coll:"den Familienstand angeben", tip:"Seit dem AGG nicht erforderlich — du entscheidest.", topic:"Career", level:"B2" },
  { id:"fc6036", de:"in Aussicht stellen", article:"—", plural:"—", en:"to hold out the prospect of", vi:"hứa hẹn", ex:"Sie hatten eine Rückmeldung bis Ende September in Aussicht gestellt.", exEn:"You had indicated a reply by the end of September.", ipa:"in AUS-zikht SHTEL-len", coll:"etwas in Aussicht stellen", tip:"Höfliche Art, an eine Zusage zu erinnern, ohne sie eine Zusage zu nennen.", topic:"Writing", level:"C1" },
  { id:"fc6037", de:"gegenlesen", article:"—", plural:"—", en:"to proofread", vi:"đọc soát", ex:"Lass deine Bewerbung von einer deutschsprachigen Person gegenlesen.", exEn:"Have a German speaker proofread your application.", ipa:"GEE-gen-lee-zen", coll:"einen Text gegenlesen", tip:"Trennbar. Auch im Review üblich: *gegenprüfen*.", topic:"Writing", level:"C1" },
  { id:"fc6038", de:"Austausch", article:"der", plural:"—", en:"exchange, discussion", vi:"trao đổi", ex:"Der Austausch über Ihre Architektur hat mein Interesse verstärkt.", exEn:"The discussion about your architecture strengthened my interest.", ipa:"AUS-taush", coll:"der Austausch über + Akk.", tip:"Kollegialer als *das Gespräch* — Standard in der Dankes-Mail.", topic:"Writing", level:"C1" },

  /* ---- Dialogue · Gehaltsgespräch ---- */
  { id:"fc6039", de:"Konditionen", article:"die", plural:"(Plural)", en:"terms and conditions", vi:"các điều kiện", ex:"Jetzt geht es um die Konditionen.", exEn:"Now it's about the terms.", ipa:"kon-di-TSYOO-nen", coll:"die Konditionen verhandeln", tip:"Fast nur im Plural. Meint Gehalt plus alles Drumherum.", topic:"Career", level:"C1" },
  { id:"fc6040", de:"Fixgehalt", article:"das", plural:"die Fixgehälter", en:"base salary", vi:"lương cứng", ex:"Beim Fixgehalt sind wir für diese Stufe am oberen Rand.", exEn:"On base salary we're at the top end for this level.", ipa:"FIKS-ge-halt", coll:"das Fixgehalt erhöhen", tip:"Gegenstück zum variablen Anteil.", topic:"Career", level:"C1" },
  { id:"fc6041", de:"Gesamtpaket", article:"das", plural:"die Gesamtpakete", en:"overall package", vi:"gói tổng thể", ex:"Mir geht es nicht ausschließlich um die Fixzahl — auch das Gesamtpaket zählt.", exEn:"It isn't only the base figure for me — the overall package counts too.", ipa:"ge-ZAMT-pa-keet", coll:"über das Gesamtpaket verhandeln", tip:"Der Ausweg, wenn beim Fixgehalt kein Spielraum mehr ist.", topic:"Career", level:"C1" },
  { id:"fc6042", de:"Bedenkzeit", article:"die", plural:"—", en:"time to consider", vi:"thời gian cân nhắc", ex:"Dürfte ich mir das bis Freitag überlegen?", exEn:"May I think it over until Friday?", ipa:"be-DENK-tsyt", coll:"um Bedenkzeit bitten", tip:"Zwei bis fünf Tage sind üblich und werden ohne Nachfrage gewährt.", topic:"Career", level:"C1" },
  { id:"fc6043", de:"vorsehen", article:"—", plural:"—", en:"to earmark, to plan for", vi:"dự kiến", ex:"Wir hätten ein Jahresgehalt von 68.000 Euro vorgesehen.", exEn:"We had earmarked an annual salary of €68,000.", ipa:"FOR-zee-en", coll:"einen Rahmen vorsehen", tip:"Trennbar. Signalisiert: geplant, aber noch nicht endgültig.", topic:"Career", level:"C1" },
  { id:"fc6044", de:"vertretbar", article:"—", plural:"—", en:"defensible, justifiable", vi:"có thể biện minh", ex:"Das halte ich für vertretbar.", exEn:"I consider that defensible.", ipa:"fer-TREET-baar", coll:"etwas für vertretbar halten", tip:"Typisch, wenn jemand eine Zusage intern begründen muss.", topic:"Workplace", level:"C1" },
  { id:"fc6045", de:"Verhandlungsspielraum", article:"der", plural:"die -räume", en:"room to negotiate", vi:"dư địa đàm phán", ex:"Beim Weiterbildungsbudget gibt es mehr Verhandlungsspielraum als beim Fixum.", exEn:"There's more room to negotiate on training budget than on base pay.", ipa:"fer-HAND-lungs-shpeel-raum", coll:"Verhandlungsspielraum haben", tip:"Umlaut im Plural. Kopf: der Raum.", topic:"Career", level:"C1" },

  /* ---- Dialogue · Karrieregespräch ---- */
  { id:"fc6046", de:"Mitarbeitergespräch", article:"das", plural:"die -gespräche", en:"performance / development review", vi:"trao đổi định kỳ với sếp", ex:"Im Mitarbeitergespräch habe ich meine Entwicklungsziele angesprochen.", exEn:"In the review I raised my development goals.", ipa:"MIT-ar-by-ter-ge-shpreekh", coll:"ein Mitarbeitergespräch führen", tip:"Meist jährlich, mit Protokoll. Du eröffnest das Thema Beförderung.", topic:"Career", level:"C1" },
  { id:"fc6047", de:"Beförderung", article:"die", plural:"die Beförderungen", en:"promotion", vi:"thăng chức", ex:"Die Beförderungsrunde ist im Frühjahr.", exEn:"The promotion round is in spring.", ipa:"be-FÖR-de-rung", coll:"eine Beförderung anstreben", tip:"-ung → die. Verb: befördert werden.", topic:"Career", level:"B2" },
  { id:"fc6048", de:"Sichtbarkeit", article:"die", plural:"—", en:"visibility", vi:"mức độ hiện diện", ex:"Es geht weniger um Wissen als um Sichtbarkeit über das Team hinaus.", exEn:"It's less about knowledge than visibility beyond the team.", ipa:"ZIKHT-baar-kyt", coll:"Sichtbarkeit aufbauen", tip:"In vielen deutschen Firmen der eigentliche Unterschied zwischen den Stufen.", topic:"Career", level:"C1" },
  { id:"fc6049", de:"belegen", article:"—", plural:"—", en:"to evidence, to substantiate", vi:"chứng minh", ex:"Bis dahin müssen die Punkte belegt sein.", exEn:"The items have to be evidenced by then.", ipa:"be-LEE-gen", coll:"eine Leistung belegen", tip:"Belege schlagen Selbsteinschätzung — im 1:1 wie im Gespräch.", topic:"Career", level:"B2" },
  { id:"fc6050", de:"sich zurückhalten", article:"—", plural:"—", en:"to hold back", vi:"giữ kẽ", ex:"In der Architekturrunde habe ich mich bisher zurückgehalten.", exEn:"I've held back in the architecture forum so far.", ipa:"zikh tsu-RÜK-hal-ten", coll:"sich mit etwas zurückhalten", tip:"Wird in deutschen Teams eher als fehlende Initiative gelesen, nicht als Bescheidenheit.", topic:"Career", level:"C1" },
  { id:"fc6051", de:"nachhaken", article:"—", plural:"—", en:"to follow up, to press further", vi:"hỏi tới", ex:"Bei weich formulierter Kritik solltest du nachhaken.", exEn:"When criticism is softly worded, press further.", ipa:"NAAKH-haa-ken", coll:"bei jemandem nachhaken", tip:"Trennbar, umgangssprachlich, sehr häufig im Büro.", topic:"Speaking", level:"C1" },
  { id:"fc6052", de:"ersetzbar", article:"—", plural:"—", en:"replaceable", vi:"có thể thay thế", ex:"Ein Senior macht sich in Routineaufgaben ersetzbar.", exEn:"A senior makes themself replaceable in routine work.", ipa:"er-ZETS-baar", coll:"sich ersetzbar machen", tip:"Hier positiv gemeint — es schafft Zeit für die schwierigen Aufgaben.", topic:"Career", level:"C1" },

  /* ---- Dialogue · Kundentermin ---- */
  { id:"fc6053", de:"Verzug", article:"der", plural:"—", en:"delay", vi:"sự chậm trễ", ex:"Wie viel Verzug reden wir?", exEn:"How much delay are we talking about?", ipa:"fer-TSUUK", coll:"in Verzug geraten", tip:"Hat im Vertragsrecht eine eigene Bedeutung — immer in Arbeitstagen beziffern.", topic:"Workplace", level:"C1" },
  { id:"fc6054", de:"Übergangslösung", article:"die", plural:"die -lösungen", en:"interim solution", vi:"giải pháp tạm", ex:"Für die ersten zehn Tage brauchen wir eine Übergangslösung.", exEn:"For the first ten days we need an interim solution.", ipa:"ÜÜ-ber-gangs-löö-zung", coll:"eine Übergangslösung anbieten", tip:"Das Wort, das aus einer Verzögerung eine Option macht.", topic:"Workplace", level:"B2" },
  { id:"fc6055", de:"Arbeitstag", article:"der", plural:"die Arbeitstage", en:"working day", vi:"ngày làm việc", ex:"Realistisch sind zehn Arbeitstage.", exEn:"Realistically it's ten working days.", ipa:"AR-byts-taak", coll:"in Arbeitstagen rechnen", tip:"Zehn Arbeitstage sind zwei Wochen — der Unterschied zu *Tagen* sind zwei Wochenenden.", topic:"Workplace", level:"B2" },
  { id:"fc6056", de:"Verlässlichkeit", article:"die", plural:"—", en:"reliability", vi:"sự đáng tin cậy", ex:"Verlässlichkeit zählt hier mehr als Geschwindigkeit.", exEn:"Reliability counts for more here than speed.", ipa:"fer-LES-likh-kyt", coll:"Verlässlichkeit zeigen", tip:"Kernwert der deutschen Arbeitskultur — ein gehaltener Termin schlägt einen schnellen.", topic:"Culture", level:"C1" },
  { id:"fc6057", de:"Ansage", article:"die", plural:"die Ansagen", en:"clear statement", vi:"thông báo rõ ràng", ex:"Danke für die klare Ansage.", exEn:"Thanks for the clear message.", ipa:"AN-zaa-ge", coll:"eine klare Ansage machen", tip:"Als Lob gemeint: Klarheit gilt als Respekt, nicht als Härte.", topic:"Culture", level:"C1" },
  { id:"fc6058", de:"beschönigen", article:"—", plural:"—", en:"to gloss over", vi:"nói giảm cho đẹp", ex:"Eine Verzögerung wird benannt, nicht beschönigt.", exEn:"A delay is named, not glossed over.", ipa:"be-SHÖÖ-ni-gen", coll:"nichts beschönigen", tip:"Beschönigen kostet im deutschen Kundenkontakt mehr Vertrauen als die schlechte Nachricht selbst.", topic:"Culture", level:"C1" },
  { id:"fc6059", de:"stemmen", article:"—", plural:"—", en:"to manage, to shoulder", vi:"kham được", ex:"Eine Stunde am Tag können wir stemmen.", exEn:"An hour a day we can manage.", ipa:"SHTEM-men", coll:"eine Aufgabe stemmen", tip:"Umgangssprachlich, aber im Berufsalltag sehr verbreitet.", topic:"Workplace", level:"B2" },
  { id:"fc6060", de:"nachliefern", article:"—", plural:"—", en:"to deliver later, to supply afterwards", vi:"giao bổ sung", ex:"Der Export kommt zehn Tage später nach — den liefern wir nach.", exEn:"The export follows ten days later — we'll deliver it afterwards.", ipa:"NAAKH-lee-fern", coll:"etwas nachliefern", tip:"Trennbar. Macht aus einer Verzögerung eine Option statt eines Ausfalls.", topic:"Workplace", level:"B2" },
  { id:"fc6061", de:"Stichtag", article:"der", plural:"die Stichtage", en:"cut-off date", vi:"ngày chốt", ex:"Am Stichtag zu melden ist zu spät.", exEn:"Reporting on the cut-off date is too late.", ipa:"SHTIKH-taak", coll:"den Stichtag halten", tip:"Vier Wochen vorher ist es Planung, am Stichtag ein Vertrauensbruch.", topic:"Workplace", level:"B2" },
  { id:"fc6062", de:"abbilden", article:"—", plural:"—", en:"to map, to represent (in a system)", vi:"mô hình hoá", ex:"Die Rechnungsnummern müssen wir sauber abbilden.", exEn:"We have to map the invoice numbers cleanly.", ipa:"AP-bil-den", coll:"einen Vorgang abbilden", tip:"Trennbar. Standardwort, wenn Fachlogik in Software übersetzt wird.", topic:"Software Development", level:"B2" }
]);
