/*! flashcards-5.js — Alltag deck (Đợt 2). Merges onto window.FLASHCARDS.
 * Everyday-survival vocabulary from the ten content/alltag modules.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- Café & Bäckerei ---- */
  { id:"fc2001", de:"Brötchen", article:"das", plural:"die Brötchen", en:"bread roll", vi:"bánh mì tròn", ex:"Ich hätte gern zwei Brötchen mit Käse.", exEn:"I'd like two rolls with cheese.", ipa:"BRÖÖT-khen", coll:"ein belegtes Brötchen", tip:"-chen → immer das, Plural = Singular.", topic:"Alltag", level:"B1" },
  { id:"fc2002", de:"Leitungswasser", article:"das", plural:"—", en:"tap water", vi:"nước máy", ex:"Könnte ich ein Glas Leitungswasser bekommen?", exEn:"Could I have a glass of tap water?", ipa:"LY-tungs-vas-ser", coll:"ein Glas Leitungswasser", tip:"In Deutschland unüblich — oft wird Flaschenwasser verkauft.", topic:"Alltag", level:"B1" },
  { id:"fc2003", de:"Trinkgeld", article:"das", plural:"die Trinkgelder", en:"tip", vi:"tiền boa", ex:"Als Trinkgeld rundet man einfach auf.", exEn:"For a tip you simply round up.", ipa:"TRINK-gelt", coll:"Trinkgeld geben", tip:"5–10 % reicht. Man nennt die GESAMTSUMME: „Zehn, bitte.“", topic:"Alltag", level:"B1" },
  { id:"fc2004", de:"Bargeld", article:"das", plural:"—", en:"cash", vi:"tiền mặt", ex:"Viele kleine Läden nehmen nur Bargeld.", exEn:"Many small shops take cash only.", ipa:"BAAR-gelt", coll:"bar zahlen", tip:"„Kann ich mit Karte zahlen?“ — immer vorher fragen!", topic:"Alltag", level:"B1" },
  { id:"fc2005", de:"Theke", article:"die", plural:"die Theken", en:"counter", vi:"quầy", ex:"Die belegten Brötchen liegen an der Theke.", exEn:"The filled rolls are at the counter.", ipa:"TAY-ke", coll:"an der Theke bestellen", tip:"Nicht mit „die Theorie“ verwechseln.", topic:"Alltag", level:"B1" },

  /* ---- Mittagspause & Small Talk ---- */
  { id:"fc2006", de:"Mittagspause", article:"die", plural:"die Mittagspausen", en:"lunch break", vi:"giờ nghỉ trưa", ex:"In der Mittagspause reden wir über alles außer Arbeit.", exEn:"At lunch we talk about everything except work.", ipa:"MIT-taks-pau-ze", coll:"Mittagspause machen", tip:"-pause → die.", topic:"Alltag", level:"B1" },
  { id:"fc2007", de:"Kantine", article:"die", plural:"die Kantinen", en:"canteen", vi:"căng tin", ex:"Das Essen in der Kantine ist ganz okay.", exEn:"The canteen food is okay.", ipa:"kan-TEE-ne", coll:"in die Kantine gehen", tip:"Betonung auf TEE.", topic:"Alltag", level:"B1" },
  { id:"fc2008", de:"Floskel", article:"die", plural:"die Floskeln", en:"empty phrase, pleasantry", vi:"câu xã giao sáo", ex:"„Wie geht's?“ ist in Deutschland keine reine Floskel.", exEn:"'How are you?' isn't just a pleasantry in Germany.", ipa:"FLOS-kel", coll:"eine höfliche Floskel", tip:"Deutsche erwarten eine echte Antwort!", topic:"Alltag", level:"B2" },
  { id:"fc2009", de:"Gehalt", article:"das", plural:"die Gehälter", en:"salary", vi:"lương", ex:"Über das Gehalt spricht man in Deutschland nicht.", exEn:"You don't discuss salary in Germany.", ipa:"ge-HALT", coll:"das Gehalt verhandeln", tip:"das Gehalt = lương; der Gehalt = hàm lượng. Zwei Wörter!", topic:"Workplace", level:"B2" },
  { id:"fc2010", de:"Herkunft", article:"die", plural:"die Herkünfte", en:"origin, background", vi:"xuất thân", ex:"Über die Herkunft zu sprechen ist völlig normal.", exEn:"Talking about where you're from is completely normal.", ipa:"HER-kunft", coll:"die Herkunft nennen", tip:"Umlaut im Plural.", topic:"Alltag", level:"B2" },

  /* ---- Modalpartikeln ---- */
  { id:"fc2011", de:"Modalpartikel", article:"die", plural:"die Modalpartikeln", en:"modal particle", vi:"tiểu từ tình thái", ex:"Modalpartikeln machen dein Deutsch sofort natürlicher.", exEn:"Modal particles instantly make your German more natural.", ipa:"mo-DAAL-par-ti-kel", coll:"eine Modalpartikel verwenden", tip:"doch, mal, ja, halt, denn, eh — unbetont, nie am Satzanfang.", topic:"Alltag", level:"B2" },
  { id:"fc2012", de:"halt", article:"—", plural:"—", en:"just, simply (resignation)", vi:"thì… vậy thôi", ex:"Die Maschine spinnt halt wieder. Ist halt so.", exEn:"The machine's playing up again. That's just how it is.", ipa:"halt", coll:"Ist halt so.", tip:"Synonym: eben. Drückt Resignation aus.", topic:"Alltag", level:"B2" },
  { id:"fc2013", de:"doch", article:"—", plural:"—", en:"come on, do (softener)", vi:"thì cứ… đi", ex:"Frag doch mal kurz im Chat.", exEn:"Why don't you just ask in the chat.", ipa:"dokh", coll:"Frag doch mal …", tip:"„doch mal“ zusammen ist sehr häufig — mildert Aufforderungen.", topic:"Alltag", level:"B1" },
  { id:"fc2014", de:"Kaffeeküche", article:"die", plural:"die Kaffeeküchen", en:"office kitchen", vi:"bếp nhỏ văn phòng", ex:"In der Kaffeeküche trifft man immer jemanden.", exEn:"You always meet someone in the office kitchen.", ipa:"KA-fee-küü-khe", coll:"in der Kaffeeküche stehen", tip:"Eigene Tasse SOFORT spülen — sonst gibt es Ärger.", topic:"Alltag", level:"B1" },

  /* ---- Feierabend ---- */
  { id:"fc2015", de:"Feierabend", article:"der", plural:"die Feierabende", en:"end of the working day", vi:"giờ tan làm", ex:"Schönen Feierabend!", exEn:"Have a good evening!", ipa:"FY-er-aa-bent", coll:"Feierabend machen", tip:"Kein „Party-Abend“! Geschützte Freizeit nach der Arbeit.", topic:"Alltag", level:"B1" },
  { id:"fc2016", de:"Kneipe", article:"die", plural:"die Kneipen", en:"pub", vi:"quán bia", ex:"Wir gehen noch in die Kneipe um die Ecke.", exEn:"We're going to the pub round the corner.", ipa:"KNY-pe", coll:"in die Kneipe gehen", tip:"Informeller als „die Bar“.", topic:"Alltag", level:"B1" },
  { id:"fc2017", de:"Runde", article:"die", plural:"die Runden", en:"round (of drinks)", vi:"chầu", ex:"Noch eine Runde? Ich geb einen aus.", exEn:"Another round? It's on me.", ipa:"RUN-de", coll:"eine Runde ausgeben", tip:"„einen ausgeben“ = mời cả chầu.", topic:"Alltag", level:"B1" },
  { id:"fc2018", de:"satt", article:"—", plural:"—", en:"full (after eating)", vi:"no", ex:"Danke, ich bin satt.", exEn:"Thanks, I'm full.", ipa:"zat", coll:"satt sein/werden", tip:"⚠️ „Ich bin voll“ heißt BETRUNKEN, nicht satt!", topic:"Alltag", level:"B1" },
  { id:"fc2019", de:"absagen", article:"—", plural:"—", en:"to decline, to cancel", vi:"từ chối, hủy", ex:"Ich muss leider absagen, ich muss früh raus.", exEn:"I have to decline, I need to be up early.", ipa:"AP-zaa-gen", coll:"einen Termin absagen", tip:"Trennbar. Gegenteil: zusagen.", topic:"Alltag", level:"B1" },

  /* ---- Wohnung ---- */
  { id:"fc2020", de:"Kaltmiete", article:"die", plural:"die Kaltmieten", en:"base rent (excl. costs)", vi:"tiền thuê chưa phí", ex:"Die Kaltmiete liegt bei 890 Euro.", exEn:"The base rent is 890 euros.", ipa:"KALT-mee-te", coll:"die Kaltmiete beträgt …", tip:"Anzeigen nennen fast immer die KALTmiete — nicht das, was du zahlst!", topic:"Alltag", level:"B2" },
  { id:"fc2021", de:"Warmmiete", article:"die", plural:"die Warmmieten", en:"rent incl. service charges", vi:"tiền thuê đã gồm phí", ex:"Warm sind wir bei 1.100 Euro.", exEn:"Warm we're at 1,100 euros.", ipa:"VARM-mee-te", coll:"warm / kalt", tip:"Warmmiete = Kaltmiete + Nebenkosten. Das ist dein echter Betrag.", topic:"Alltag", level:"B2" },
  { id:"fc2022", de:"Nebenkosten", article:"die", plural:"(nur Plural)", en:"additional/service costs", vi:"phí phụ", ex:"Wie hoch sind die Nebenkosten?", exEn:"How high are the service charges?", ipa:"NAY-ben-kos-ten", coll:"die Nebenkosten betragen …", tip:"Heizung/Wasser meist drin, Strom + Internet NICHT.", topic:"Alltag", level:"B2" },
  { id:"fc2023", de:"Kaution", article:"die", plural:"die Kautionen", en:"deposit", vi:"tiền cọc", ex:"Die Kaution beträgt drei Kaltmieten.", exEn:"The deposit is three months' base rent.", ipa:"kau-TSYOON", coll:"die Kaution hinterlegen", tip:"Max. 3 Kaltmieten, gesetzlich in 3 Raten zahlbar.", topic:"Alltag", level:"B2" },
  { id:"fc2024", de:"Einbauküche", article:"die", plural:"die Einbauküchen", en:"fitted kitchen", vi:"bếp lắp sẵn", ex:"Ist eine Einbauküche vorhanden?", exEn:"Is there a fitted kitchen?", ipa:"AYN-bau-küü-khe", coll:"eine Einbauküche übernehmen", tip:"Viele deutsche Wohnungen haben KEINE Küche — 2.000–5.000 € extra!", topic:"Alltag", level:"B2" },
  { id:"fc2025", de:"Unterlagen", article:"die", plural:"(nur Plural)", en:"documents", vi:"giấy tờ", ex:"Die Unterlagen habe ich vollständig dabei.", exEn:"I have all the documents with me.", ipa:"UN-ter-laa-gen", coll:"Unterlagen einreichen/mitbringen", tip:"Immer Plural. Komplette Mappe = großer Vorteil bei der Besichtigung.", topic:"Alltag", level:"B2" },

  /* ---- Behörden ---- */
  { id:"fc2026", de:"Anmeldung", article:"die", plural:"die Anmeldungen", en:"address registration", vi:"đăng ký cư trú", ex:"Die Anmeldung muss innerhalb von 14 Tagen erfolgen.", exEn:"Registration must happen within 14 days.", ipa:"AN-mel-dung", coll:"sich anmelden", tip:"Ohne Anmeldung: kein Konto, keine Steuer-ID, kein Aufenthaltstitel.", topic:"Alltag", level:"B2" },
  { id:"fc2027", de:"Meldebescheinigung", article:"die", plural:"die Meldebescheinigungen", en:"registration certificate", vi:"giấy xác nhận cư trú", ex:"Für das Konto brauchen Sie die Meldebescheinigung.", exEn:"You need the registration certificate for the account.", ipa:"MEL-de-be-shy-ni-gung", coll:"die Meldebescheinigung vorlegen", tip:"Bekommst du sofort beim Termin. Gut aufheben!", topic:"Alltag", level:"B2" },
  { id:"fc2028", de:"Wohnungsgeberbestätigung", article:"die", plural:"die -bestätigungen", en:"landlord's confirmation", vi:"xác nhận của chủ nhà", ex:"Ohne Wohnungsgeberbestätigung geht die Anmeldung nicht.", exEn:"Registration doesn't work without the landlord's confirmation.", ipa:"VOO-nungs-gay-ber-be-shtee-ti-gung", coll:"die Wohnungsgeberbestätigung anfordern", tip:"Kopf = die Bestätigung → die. Vom Vermieter anfordern!", topic:"Alltag", level:"B2" },
  { id:"fc2029", de:"Aufenthaltstitel", article:"der", plural:"die Aufenthaltstitel", en:"residence permit", vi:"giấy phép cư trú", ex:"Den Aufenthaltstitel gibt es bei der Ausländerbehörde.", exEn:"The residence permit comes from the immigration office.", ipa:"AUF-ent-halts-tee-tel", coll:"einen Aufenthaltstitel beantragen", tip:"NICHT beim Bürgeramt! Plural = Singular.", topic:"Alltag", level:"B2" },
  { id:"fc2030", de:"Sachbearbeiter", article:"der", plural:"die Sachbearbeiter", en:"case worker, clerk", vi:"cán bộ xử lý hồ sơ", ex:"Der Sachbearbeiter war knapp, aber hilfsbereit.", exEn:"The clerk was brief but helpful.", ipa:"ZAKH-be-ar-by-ter", coll:"beim Sachbearbeiter vorsprechen", tip:"Knapper Ton ist normal, keine Unfreundlichkeit.", topic:"Alltag", level:"B2" },
  { id:"fc2031", de:"buchstabieren", article:"—", plural:"—", en:"to spell", vi:"đánh vần", ex:"Könnten Sie das bitte buchstabieren?", exEn:"Could you spell that, please?", ipa:"bookh-shta-BEE-ren", coll:"einen Namen buchstabieren", tip:"-ieren → Partizip ohne ge-: buchstabiert.", topic:"Alltag", level:"B1" },

  /* ---- Arzt ---- */
  { id:"fc2032", de:"Krankschreibung", article:"die", plural:"die Krankschreibungen", en:"sick note", vi:"giấy nghỉ ốm", ex:"Könnten Sie mir eine Krankschreibung ausstellen?", exEn:"Could you write me a sick note?", ipa:"KRANK-shry-bung", coll:"eine Krankschreibung bekommen", tip:"Auch: die Arbeitsunfähigkeitsbescheinigung (AU).", topic:"Alltag", level:"B2" },
  { id:"fc2033", de:"sich krankmelden", article:"—", plural:"—", en:"to report sick (to your employer)", vi:"báo ốm", ex:"Ich muss mich heute krankmelden.", exEn:"I have to call in sick today.", ipa:"KRANK-mel-den", coll:"sich beim Arbeitgeber krankmelden", tip:"DU meldest dich; der ARZT schreibt dich krank. Zwei Verben!", topic:"Alltag", level:"B2" },
  { id:"fc2034", de:"Versichertenkarte", article:"die", plural:"die Versichertenkarten", en:"health insurance card", vi:"thẻ bảo hiểm y tế", ex:"Bitte bringen Sie Ihre Versichertenkarte mit.", exEn:"Please bring your insurance card.", ipa:"fer-ZIKH-er-ten-kar-te", coll:"die Versichertenkarte vorlegen", tip:"Ohne Karte zahlst du erst mal selbst.", topic:"Alltag", level:"B1" },
  { id:"fc2035", de:"Halsschmerzen", article:"die", plural:"(nur Plural)", en:"sore throat", vi:"đau họng", ex:"Ich habe seit drei Tagen Halsschmerzen.", exEn:"I've had a sore throat for three days.", ipa:"HALS-shmer-tsen", coll:"Halsschmerzen haben", tip:"Alle …schmerzen sind Plural. seit + Präsens!", topic:"Alltag", level:"B1" },
  { id:"fc2036", de:"Übelkeit", article:"die", plural:"—", en:"nausea", vi:"buồn nôn", ex:"Mir ist übel.", exEn:"I feel nauseous.", ipa:"ÜÜ-bel-kyt", coll:"Mir ist übel.", tip:"⚠️ „Mir ist übel“ (korrekt) vs. „Ich bin übel“ (= ich bin gemein).", topic:"Alltag", level:"B2" },
  { id:"fc2037", de:"Rezept", article:"das", plural:"die Rezepte", en:"prescription; recipe", vi:"đơn thuốc; công thức", ex:"Ich verschreibe Ihnen etwas — hier ist das Rezept.", exEn:"I'll prescribe you something — here's the prescription.", ipa:"re-TSEPT", coll:"ein Rezept einlösen", tip:"Zwei Bedeutungen: Arzt UND Küche.", topic:"Alltag", level:"B1" },
  { id:"fc2038", de:"Hausarzt", article:"der", plural:"die Hausärzte", en:"GP, family doctor", vi:"bác sĩ gia đình", ex:"Zum Facharzt gehst du meist über den Hausarzt.", exEn:"You usually get to a specialist via your GP.", ipa:"HAUS-artst", coll:"zum Hausarzt gehen", tip:"Erste Anlaufstelle. Facharzt oft nur mit Überweisung.", topic:"Alltag", level:"B1" },

  /* ---- Supermarkt & Pfand ---- */
  { id:"fc2039", de:"Pfand", article:"das", plural:"die Pfänder", en:"deposit (on bottles)", vi:"tiền cọc chai", ex:"Ist da Pfand drauf?", exEn:"Is there a deposit on that?", ipa:"pfant", coll:"Pfand zurückbekommen", tip:"0,25 € Einweg, 0,08 € Mehrweg-Glas.", topic:"Alltag", level:"B1" },
  { id:"fc2040", de:"Pfandautomat", article:"der", plural:"die Pfandautomaten", en:"deposit return machine", vi:"máy trả vỏ chai", ex:"Der Pfandautomat nimmt nur ganze Flaschen.", exEn:"The machine only takes intact bottles.", ipa:"PFANT-au-to-maat", coll:"Flaschen am Pfandautomaten abgeben", tip:"Etikett nach vorn, nicht zerdrücken!", topic:"Alltag", level:"B1" },
  { id:"fc2041", de:"Kassenbon", article:"der", plural:"die Kassenbons", en:"receipt", vi:"hóa đơn", ex:"Haben Sie den Kassenbon dabei?", exEn:"Do you have the receipt with you?", ipa:"KAS-sen-bong", coll:"den Bon aufheben", tip:"Kurz: der Bon. Für Umtausch unbedingt aufheben.", topic:"Alltag", level:"B1" },
  { id:"fc2042", de:"Tüte", article:"die", plural:"die Tüten", en:"bag", vi:"túi", ex:"Brauchen Sie eine Tüte? — Ja, bitte eine.", exEn:"Do you need a bag? — Yes, one please.", ipa:"TÜÜ-te", coll:"eine Tüte kaufen", tip:"Kostet 20–50 Cent. Die meisten bringen einen Beutel mit.", topic:"Alltag", level:"B1" },
  { id:"fc2043", de:"umtauschen", article:"—", plural:"—", en:"to exchange (goods)", vi:"đổi hàng", ex:"Ich möchte das gern umtauschen, es ist defekt.", exEn:"I'd like to exchange this, it's faulty.", ipa:"UM-tau-shen", coll:"eine Ware umtauschen", tip:"Trennbar. Ohne Bon oft schwierig.", topic:"Alltag", level:"B1" },

  /* ---- Bahn ---- */
  { id:"fc2044", de:"Verspätung", article:"die", plural:"die Verspätungen", en:"delay", vi:"trễ giờ", ex:"Der Zug hat etwa zwanzig Minuten Verspätung.", exEn:"The train is about twenty minutes late.", ipa:"fer-SHPEE-tung", coll:"Verspätung haben", tip:"-ung → die. Ab 60 Min. gibt es 25 % zurück.", topic:"Alltag", level:"B1" },
  { id:"fc2045", de:"ausfallen", article:"—", plural:"—", en:"to be cancelled", vi:"bị hủy", ex:"Der ICE fällt heute leider aus.", exEn:"The ICE is cancelled today.", ipa:"AUS-fal-len", coll:"ein Zug fällt aus", tip:"Trennbar — steht am Satzende. Das Wort, auf das du warten musst!", topic:"Alltag", level:"B2" },
  { id:"fc2046", de:"Gleis", article:"das", plural:"die Gleise", en:"platform, track", vi:"sân ga", ex:"Der Zug fährt heute von Gleis drei ab.", exEn:"The train leaves from platform three today.", ipa:"glys", coll:"von Gleis … abfahren", tip:"Gleiswechsel = platform change — immer die Anzeige prüfen.", topic:"Alltag", level:"B1" },
  { id:"fc2047", de:"umsteigen", article:"—", plural:"—", en:"to change (trains)", vi:"đổi tàu", ex:"Reisende nach München steigen bitte in Nürnberg um.", exEn:"Passengers to Munich please change in Nuremberg.", ipa:"UM-shty-gen", coll:"in … umsteigen", tip:"Trennbar. Perfekt mit sein: ist umgestiegen.", topic:"Alltag", level:"B1" },
  { id:"fc2048", de:"Entschädigung", article:"die", plural:"die Entschädigungen", en:"compensation", vi:"bồi thường", ex:"Habe ich Anspruch auf Entschädigung?", exEn:"Am I entitled to compensation?", ipa:"ent-SHEE-di-gung", coll:"Entschädigung beantragen", tip:"25 % ab 60 Min., 50 % ab 120 Min. Verspätung.", topic:"Alltag", level:"B2" },
  { id:"fc2049", de:"Durchsage", article:"die", plural:"die Durchsagen", en:"announcement", vi:"thông báo loa", ex:"Die Durchsage habe ich nicht verstanden.", exEn:"I didn't understand the announcement.", ipa:"DURKH-zaa-ge", coll:"eine Durchsage hören", tip:"Achte auf: welcher Zug, was ist los, was tun.", topic:"Alltag", level:"B2" },

  /* ---- Telefon, Bank & Verträge ---- */
  { id:"fc2050", de:"Girokonto", article:"das", plural:"die Girokonten", en:"current account", vi:"tài khoản thanh toán", ex:"Ich möchte ein Girokonto eröffnen.", exEn:"I'd like to open a current account.", ipa:"ZHEE-ro-kon-to", coll:"ein Girokonto eröffnen", tip:"Braucht die Meldebescheinigung!", topic:"Alltag", level:"B2" },
  { id:"fc2051", de:"Lastschrift", article:"die", plural:"die Lastschriften", en:"direct debit", vi:"ủy nhiệm thu", ex:"Der Anbieter zieht den Betrag per Lastschrift ein.", exEn:"The provider debits the amount automatically.", ipa:"LAST-shrift", coll:"per Lastschrift zahlen", tip:"Du erteilst dafür ein SEPA-Mandat.", topic:"Alltag", level:"B2" },
  { id:"fc2052", de:"Kündigungsfrist", article:"die", plural:"die Kündigungsfristen", en:"notice period", vi:"thời hạn báo hủy", ex:"Die Kündigungsfrist beträgt einen Monat.", exEn:"The notice period is one month.", ipa:"KÜN-di-gungs-frist", coll:"die Kündigungsfrist einhalten", tip:"Verpasst = Vertrag verlängert sich automatisch. Kostet Geld!", topic:"Alltag", level:"B2" },
  { id:"fc2053", de:"kündigen", article:"—", plural:"—", en:"to cancel (a contract), to resign", vi:"hủy hợp đồng; xin nghỉ việc", ex:"Ich möchte meinen Vertrag zum nächstmöglichen Termin kündigen.", exEn:"I'd like to cancel at the earliest possible date.", ipa:"KÜN-di-gen", coll:"einen Vertrag kündigen", tip:"IMMER schriftlich + Bestätigung verlangen.", topic:"Alltag", level:"B2" },
  { id:"fc2054", de:"Dispo(kredit)", article:"der", plural:"die Dispokredite", en:"overdraft", vi:"thấu chi", ex:"Der Dispo ist teuer — etwa elf Prozent Zinsen.", exEn:"The overdraft is expensive — around 11 % interest.", ipa:"DIS-po", coll:"den Dispo nutzen", tip:"Lieber vermeiden. Zinsen sehr hoch.", topic:"Alltag", level:"B2" },
  { id:"fc2055", de:"Bestätigung", article:"die", plural:"die Bestätigungen", en:"confirmation", vi:"xác nhận", ex:"Könnten Sie mir das bitte schriftlich bestätigen?", exEn:"Could you confirm that in writing?", ipa:"be-SHTEE-ti-gung", coll:"eine Bestätigung anfordern", tip:"-ung → die. Ohne Bestätigung hast du keinen Beweis.", topic:"Alltag", level:"B1" }
]);
