/*! flashcards-10.js — Phase 6 (on the job) + Bewerbungsunterlagen deck (Đợt 8).
 * Merges onto window.FLASHCARDS.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- Phase 6 · Grammar (Partikeln, Register, Fossilien) ---- */
  { id:"fc7001", de:"Mittelfeld", article:"das", plural:"—", en:"middle field (of the clause)", vi:"phần giữa câu", ex:"Modalpartikeln stehen im Mittelfeld, nach den Pronomen.", exEn:"Modal particles sit in the middle field, after the pronouns.", ipa:"MIT-tel-felt", coll:"im Mittelfeld stehen", tip:"„Kannst du mir mal kurz helfen?“ — erst die Pronomen, dann die Partikel.", topic:"Grammar", level:"C1" },
  { id:"fc7002", de:"Abtönungspartikel", article:"die", plural:"die Abtönungspartikeln", en:"modal/flavouring particle", vi:"tiểu từ sắc thái", ex:"Doch, mal, halt und wohl sind Abtönungspartikeln.", exEn:"Doch, mal, halt and wohl are flavouring particles.", ipa:"AP-töö-nungs-par-ti-kel", coll:"eine Abtönungspartikel setzen", tip:"Zweiter Name für die Modalpartikel — betont, dass sie den Ton färbt, nicht den Inhalt.", topic:"Grammar", level:"C1" },
  { id:"fc7003", de:"Wechselpräposition", article:"die", plural:"die -präpositionen", en:"two-way preposition", vi:"giới từ hai cách", ex:"Die Datei liegt im Ordner, ich lege sie in den Ordner.", exEn:"The file is in the folder; I put it into the folder.", ipa:"VEK-sel-pre-po-zi-tsyoon", coll:"Akkusativ bei Richtung, Dativ bei Ort", tip:"legen/liegen, stellen/stehen, setzen/sitzen entscheiden über den Fall.", topic:"Grammar", level:"B2" },
  { id:"fc7004", de:"Haltung", article:"die", plural:"die Haltungen", en:"attitude, stance", vi:"thái độ", ex:"Partikeln transportieren keine Information, sondern eine Haltung.", exEn:"Particles carry no information, they carry an attitude.", ipa:"HAL-tung", coll:"eine Haltung transportieren", tip:"Genau deshalb klingt Deutsch ohne Partikeln flach.", topic:"Grammar", level:"C1" },
  { id:"fc7005", de:"angeben", article:"—", plural:"—", en:"to state (in a report)", vi:"khai báo", ex:"Der Kollege gab an, das Alerting habe nicht ausgelöst.", exEn:"The colleague stated that the alerting had not triggered.", ipa:"AN-gee-ben", coll:"angeben, dass …", tip:"Trennbar. Standard-Einleitung im Postmortem, immer mit Konjunktiv I.", topic:"Writing", level:"C1" },
  { id:"fc7006", de:"fossiliert", article:"—", plural:"—", en:"fossilized (of an error)", vi:"lỗi đã đóng băng", ex:"Fossilierte Fehler überleben, weil sie das Verständnis nicht stören.", exEn:"Fossilized errors survive because they don't block understanding.", ipa:"fo-si-LEERT", coll:"ein fossilierter Fehler", tip:"Auf C1 die eigentliche Gefahr — such dir zwei und jage sie eine Woche.", topic:"Foundations", level:"C1" },

  /* ---- Phase 6 · Vocabulary (Arbeitszeit, HR, Mitbestimmung) ---- */
  { id:"fc7007", de:"Kernzeit", article:"die", plural:"die Kernzeiten", en:"core hours", vi:"giờ bắt buộc có mặt", ex:"Wir haben Gleitzeit, aber die Kernzeit ist von zehn bis fünfzehn Uhr.", exEn:"We have flextime, but core hours are ten to three.", ipa:"KERN-tsyt", coll:"in der Kernzeit erreichbar sein", tip:"Ohne Kernzeit heißt das Modell meist Vertrauensarbeitszeit.", topic:"Workplace", level:"B2" },
  { id:"fc7008", de:"Freizeitausgleich", article:"der", plural:"—", en:"time off in lieu", vi:"nghỉ bù", ex:"Überstunden werden bei uns über Freizeitausgleich abgebaut.", exEn:"Overtime is taken as time off in lieu here.", ipa:"FRY-tsyt-aus-glykh", coll:"Überstunden in Freizeitausgleich abbauen", tip:"In deutschen Tech-Firmen der Normalfall, Auszahlung die Ausnahme.", topic:"Workplace", level:"B2" },
  { id:"fc7009", de:"Gleitzeitkonto", article:"das", plural:"die Gleitzeitkonten", en:"flextime account", vi:"tài khoản giờ làm", ex:"Auf dem Gleitzeitkonto stehen aktuell zwölf Plusstunden.", exEn:"There are twelve surplus hours on the flextime account.", ipa:"GLYT-tsyt-kon-to", coll:"Stunden auf dem Gleitzeitkonto", tip:"Kopf: das Konto. Plus- und Minusstunden werden dort verbucht.", topic:"Workplace", level:"B2" },
  { id:"fc7010", de:"Elternzeit", article:"die", plural:"—", en:"parental leave", vi:"nghỉ chăm con", ex:"Beide Elternteile können Elternzeit nehmen; der Arbeitsplatz bleibt geschützt.", exEn:"Both parents can take parental leave; the job is protected.", ipa:"EL-tern-tsyt", coll:"Elternzeit nehmen / beantragen", tip:"Nicht dasselbe wie Mutterschutz — das ist die gesetzliche Schutzfrist um die Geburt.", topic:"Workplace", level:"B2" },
  { id:"fc7011", de:"Betriebsrat", article:"der", plural:"die Betriebsräte", en:"works council", vi:"hội đồng lao động", ex:"Der Betriebsrat hat die Vereinbarung zum Homeoffice ausgehandelt.", exEn:"The works council negotiated the home-office agreement.", ipa:"be-TREEPS-raat", coll:"sich an den Betriebsrat wenden", tip:"Bei unklaren Klauseln ist er genau dafür da — fragen kostet nichts.", topic:"Workplace", level:"B2" },
  { id:"fc7012", de:"Betriebsvereinbarung", article:"die", plural:"die -vereinbarungen", en:"works agreement", vi:"thỏa ước nội bộ", ex:"Die Betriebsvereinbarung regelt mobiles Arbeiten und Erreichbarkeit.", exEn:"The works agreement covers remote work and availability.", ipa:"be-TREEPS-fer-ayn-baa-rung", coll:"eine Betriebsvereinbarung schließen", tip:"Bindet beide Seiten — und regelt oft genau das, was dich täglich betrifft.", topic:"Workplace", level:"C1" },
  { id:"fc7013", de:"Fortbildung", article:"die", plural:"die Fortbildungen", en:"professional training", vi:"đào tạo nâng cao", ex:"Mein Arbeitgeber zahlt eine Fortbildung zu Kubernetes.", exEn:"My employer is paying for Kubernetes training.", ipa:"FORT-bil-dung", coll:"eine Fortbildung besuchen", tip:"Überschneidet sich mit Weiterbildung. Leichter zu bewilligen als Gehalt.", topic:"Career", level:"B2" },
  { id:"fc7014", de:"Überstunden", article:"die", plural:"(Plural)", en:"overtime", vi:"giờ làm thêm", ex:"Ich habe letzte Woche viele Überstunden gemacht.", exEn:"I did a lot of overtime last week.", ipa:"ÜÜ-ber-shtun-den", coll:"Überstunden machen / abbauen", tip:"Fast immer Plural — der Singular klingt seltsam.", topic:"Workplace", level:"B2" },
  { id:"fc7015", de:"gutschreiben", article:"—", plural:"—", en:"to credit (hours)", vi:"ghi có", ex:"Die Stunden werden auf dem Gleitzeitkonto gutgeschrieben.", exEn:"The hours are credited to the flextime account.", ipa:"GUUT-shry-ben", coll:"jemandem etwas gutschreiben", tip:"Trennbar. Gegenteil: abziehen.", topic:"Workplace", level:"B2" },

  /* ---- Phase 6 · Speaking (Daily, Review, Incident) ---- */
  { id:"fc7016", de:"Blocker", article:"der", plural:"die Blocker", en:"blocker", vi:"điểm tắc", ex:"Blocker habe ich keine — nur eine Frage ans Team.", exEn:"No blockers — just one question for the team.", ipa:"BLO-ker", coll:"einen Blocker melden", tip:"Blocker früh zu nennen ist im deutschen Team Pflicht, kein Eingeständnis.", topic:"Agile", level:"B2" },
  { id:"fc7017", de:"Sachebene", article:"die", plural:"—", en:"factual level", vi:"bình diện sự việc", ex:"Widerspruch bleibt auf der Sachebene: die Sache kritisieren, die Person respektieren.", exEn:"Disagreement stays factual: criticise the issue, respect the person.", ipa:"ZAKH-ee-be-ne", coll:"auf der Sachebene bleiben", tip:"Der Schlüsselbegriff der deutschen Diskussionskultur.", topic:"Culture", level:"C1" },
  { id:"fc7018", de:"sich stauen", article:"—", plural:"—", en:"to pile up, to jam", vi:"dồn ứ", ex:"Nicht so gut: Die Reviews haben sich in der Wochenmitte gestaut.", exEn:"Less good: reviews piled up mid-week.", ipa:"zikh SHTAU-en", coll:"etwas staut sich", tip:"Beschreibt einen Zustand, keine Person — die Retro-Technik in einem Verb.", topic:"Agile", level:"B2" },
  { id:"fc7019", de:"sich vornehmen", article:"—", plural:"—", en:"to plan to do", vi:"dự định làm", ex:"Heute nehme ich mir das Caching vor.", exEn:"Today I'm taking on the caching.", ipa:"zikh FOR-nee-men", coll:"sich etwas vornehmen", tip:"Trennbar, mit Dativ-Reflexivpronomen: ich nehme mir … vor.", topic:"Agile", level:"B2" },
  { id:"fc7020", de:"hängen an", article:"—", plural:"—", en:"to be stuck on", vi:"đang tắc ở", ex:"Ich hänge am OAuth-Refresh — kann mir jemand kurz helfen?", exEn:"I'm stuck on the OAuth refresh — can someone help?", ipa:"HEN-gen an", coll:"an etwas hängen", tip:"Umgangssprachlich, im Daily aber Standard.", topic:"Agile", level:"B2" },
  { id:"fc7021", de:"Fehlerrate", article:"die", plural:"die Fehlerraten", en:"error rate", vi:"tỉ lệ lỗi", ex:"Ich habe zurückgerollt und beobachte die Fehlerrate.", exEn:"I rolled back and I'm watching the error rate.", ipa:"FEE-ler-raa-te", coll:"die Fehlerrate beobachten", tip:"Die Standardgröße im Incident-Update, immer mit Prozentangabe.", topic:"DevOps", level:"B2" },

  /* ---- Phase 6 · Listening (echtes Tempo) ---- */
  { id:"fc7022", de:"wegbrechen", article:"—", plural:"—", en:"to cut out (a connection)", vi:"rớt tiếng", ex:"Sorry, du bist kurz weggebrochen — kannst du das nochmal sagen?", exEn:"Sorry, you cut out — can you say that again?", ipa:"VEK-bre-khen", coll:"die Verbindung bricht weg", tip:"Trennbar. Das Standardwort für abgehackte Videokonferenzen.", topic:"Workplace", level:"B2" },
  { id:"fc7023", de:"dazuziehen", article:"—", plural:"—", en:"to bring someone in", vi:"kéo thêm người vào", ex:"Falls das größer wird, ziehen wir jemanden dazu.", exEn:"If it grows, we'll bring someone in.", ipa:"da-TSUU-tsee-en", coll:"jemanden dazuziehen", tip:"Trennbar. Höflicher als „Hilfe holen“ und im Team völlig normal.", topic:"Workplace", level:"C1" },
  { id:"fc7024", de:"Feature-Flag", article:"das", plural:"die Feature-Flags", en:"feature flag", vi:"cờ tính năng", ex:"Ich habe das Feature-Flag erstmal nur auf zehn Prozent ausgerollt.", exEn:"I rolled the feature flag out to ten percent only.", ipa:"FEE-tscher-fleg", coll:"ein Feature-Flag ausrollen", tip:"Englische Nomen mit deutschem Bindestrich — Genus meist das.", topic:"DevOps", level:"B2" },
  { id:"fc7025", de:"Mundart", article:"die", plural:"die Mundarten", en:"dialect", vi:"phương ngữ", ex:"Im Team hört man mehrere Mundarten — verstehen reicht, nachsprechen musst du nicht.", exEn:"You'll hear several dialects in the team — understanding is enough.", ipa:"MUNT-art", coll:"eine Mundart sprechen", tip:"Hochdeutsch bleibt dein aktives Ziel; Mundart nur passiv.", topic:"Culture", level:"C1" },
  { id:"fc7026", de:"zusammenfassen", article:"—", plural:"—", en:"to summarise", vi:"tóm tắt", ex:"Ich fasse kurz zusammen: Ich übernehme das Caching — richtig?", exEn:"Let me summarise: I take the caching — correct?", ipa:"tsu-ZA-men-fas-sen", coll:"kurz zusammenfassen", tip:"Der wertvollste Zug in jedem Meeting: zwölf Sekunden, drei gesparte Nachfragen.", topic:"Speaking", level:"B2" },

  /* ---- Phase 6 · Reading (Verwaltungsdeutsch) ---- */
  { id:"fc7027", de:"bedürfen (+ Gen.)", article:"—", plural:"—", en:"to require", vi:"cần có", ex:"Abweichungen bedürfen der Zustimmung des Betriebsrats.", exEn:"Deviations require the works council's approval.", ipa:"be-DÜR-fen", coll:"bedarf der Zustimmung / der Schriftform", tip:"Reines Amtsdeutsch, immer mit Genitiv.", topic:"Workplace", level:"C1" },
  { id:"fc7028", de:"unverzüglich", article:"—", plural:"—", en:"without undue delay", vi:"ngay lập tức", ex:"Die Krankmeldung hat unverzüglich zu erfolgen.", exEn:"The sick note must be filed without undue delay.", ipa:"UN-fer-tsüük-likh", coll:"unverzüglich melden", tip:"Rechtsbegriff, kein Alltagswort: sofort, nicht „bald“.", topic:"Workplace", level:"C1" },
  { id:"fc7029", de:"fristgerecht", article:"—", plural:"—", en:"within the deadline", vi:"đúng hạn", ex:"Sollte die Vereinbarung nicht fristgerecht vorliegen, gilt die alte Regelung.", exEn:"If the agreement isn't in on time, the old rule applies.", ipa:"FRIST-ge-rekht", coll:"fristgerecht einreichen", tip:"Gegenstück: verfristet — zu spät und damit unwirksam.", topic:"Workplace", level:"C1" },
  { id:"fc7030", de:"unberührt bleiben", article:"—", plural:"—", en:"to remain unaffected", vi:"vẫn giữ nguyên", ex:"Im Übrigen bleibt § 5 unberührt.", exEn:"Otherwise § 5 remains unaffected.", ipa:"UN-be-rüürt BLY-ben", coll:"§ … bleibt unberührt", tip:"Signalisiert: Diese Änderung betrifft jene Regel nicht — oft steckt dort die Ausnahme.", topic:"Workplace", level:"C1" },
  { id:"fc7031", de:"Erreichbarkeit", article:"die", plural:"—", en:"availability, reachability", vi:"khả năng liên lạc", ex:"Eine Verpflichtung zur Erreichbarkeit außerhalb der Arbeitszeit besteht nicht.", exEn:"There's no obligation to be reachable outside working hours.", ipa:"er-RYKH-baar-kyt", coll:"Erreichbarkeit vereinbaren", tip:"Der verneinte Satz dazu ist eines deiner wichtigsten Rechte — genau lesen.", topic:"Workplace", level:"C1" },
  { id:"fc7032", de:"Einzelfall", article:"der", plural:"die Einzelfälle", en:"individual case", vi:"trường hợp cá biệt", ex:"Abweichungen sind im Einzelfall möglich.", exEn:"Deviations are possible in individual cases.", ipa:"AYN-tsel-fal", coll:"im Einzelfall entscheiden", tip:"Verwaltungsformel für „nicht generell, aber verhandelbar“.", topic:"Workplace", level:"C1" },
  { id:"fc7033", de:"Arbeitsmittel", article:"das", plural:"die Arbeitsmittel", en:"work equipment", vi:"phương tiện làm việc", ex:"Die erforderlichen Arbeitsmittel werden vom Arbeitgeber gestellt.", exEn:"The necessary work equipment is provided by the employer.", ipa:"AR-byts-mit-tel", coll:"Arbeitsmittel stellen", tip:"*stellen* heißt hier bereitstellen und bezahlen. Plural = Singular.", topic:"Workplace", level:"C1" },

  /* ---- Phase 6 · Writing (Status, Postmortem) ---- */
  { id:"fc7034", de:"Statusmeldung", article:"die", plural:"die Statusmeldungen", en:"status update", vi:"báo cáo trạng thái", ex:"Eine gute Statusmeldung ist selbsttragend — sie braucht keine Rückfrage.", exEn:"A good status update stands alone — no follow-up needed.", ipa:"SHTAA-tus-mel-dung", coll:"eine Statusmeldung schreiben", tip:"Zustand zuerst, dann Details, dann der Ask.", topic:"Writing", level:"B2" },
  { id:"fc7035", de:"Handlungsbedarf", article:"der", plural:"—", en:"need for action", vi:"việc cần làm", ex:"Kein Handlungsbedarf — ich melde mich, wenn sich etwas ändert.", exEn:"No action needed — I'll report back if anything changes.", ipa:"HAND-lungs-be-darf", coll:"Handlungsbedarf besteht (nicht)", tip:"Ausdrücklich zu sagen, dass nichts zu tun ist, spart fünf Leuten die Prüfung.", topic:"Writing", level:"C1" },
  { id:"fc7036", de:"Grenzwert", article:"der", plural:"die Grenzwerte", en:"threshold", vi:"ngưỡng", ex:"Die Grenzwerte für den Verbindungspool stehen jetzt im Betriebshandbuch.", exEn:"The connection-pool thresholds are now in the runbook.", ipa:"GRENTS-veert", coll:"einen Grenzwert festlegen", tip:"Standardmaßnahme im Postmortem: Grenzwerte dokumentieren.", topic:"DevOps", level:"B2" },
  { id:"fc7037", de:"justieren", article:"—", plural:"—", en:"to adjust, fine-tune", vi:"tinh chỉnh", ex:"Offen: Das Alerting justiere ich morgen früh.", exEn:"Open: I'll fine-tune the alerting tomorrow morning.", ipa:"yus-TEE-ren", coll:"das Alerting justieren", tip:"Präziser als „ändern“ — kleine Korrektur an etwas Bestehendem.", topic:"DevOps", level:"C1" },
  { id:"fc7038", de:"mitschreiben", article:"—", plural:"—", en:"to document as you go", vi:"ghi song song", ex:"Ein Punkt für nächstes Mal: Lass uns die Doku direkt mitschreiben.", exEn:"One point for next time: let's write the docs as we go.", ipa:"MIT-shry-ben", coll:"die Doku mitschreiben", tip:"Trennbar. Auch: im Meeting mitschreiben.", topic:"Writing", level:"B2" },

  /* ---- Bewerbung · Lebenslauf & Anschreiben ---- */
  { id:"fc7039", de:"Grundkenntnisse", article:"die", plural:"(Plural)", en:"basic knowledge", vi:"kiến thức cơ bản", ex:"Terraform: Grundkenntnisse — im Gespräch halte ich das aus.", exEn:"Terraform: basic knowledge — that holds up in an interview.", ipa:"GRUNT-kent-nis-se", coll:"Grundkenntnisse in etwas haben", tip:"Leiter: Grundkenntnisse < gute < fundierte Kenntnisse < einschlägige Erfahrung.", topic:"Career", level:"B2" },
  { id:"fc7040", de:"Lücke", article:"die", plural:"die Lücken", en:"gap (in a CV)", vi:"khoảng trống", ex:"Eine Lücke im Lebenslauf benennt man, statt sie zu verstecken.", exEn:"You name a gap in your CV instead of hiding it.", ipa:"LÜ-ke", coll:"eine Lücke im Lebenslauf", tip:"Eine benannte Lücke ist eine Zeile; eine entdeckte ist eine Vertrauensfrage.", topic:"Career", level:"B2" },
  { id:"fc7041", de:"Notenumrechnung", article:"die", plural:"die -umrechnungen", en:"grade conversion", vi:"quy đổi điểm", ex:"Die Notenumrechnung macht meinen Abschluss vergleichbar.", exEn:"The grade conversion makes my degree comparable.", ipa:"NOO-ten-um-rekh-nung", coll:"eine Notenumrechnung angeben", tip:"Für Hochschulabschlüsse zeigt die anabin-Datenbank der ZAB die Einstufung.", topic:"Career", level:"C1" },
  { id:"fc7042", de:"Arbeitserlaubnis", article:"die", plural:"die -erlaubnisse", en:"work permit", vi:"giấy phép lao động", ex:"Arbeitserlaubnis: unbeschränkt.", exEn:"Work permit: unrestricted.", ipa:"AR-byts-er-laup-nis", coll:"eine Arbeitserlaubnis haben", tip:"Freiwillig im Lebenslauf — aber oft effizienter als eine offene Frage.", topic:"Career", level:"B2" },
  { id:"fc7043", de:"Initiativbewerbung", article:"die", plural:"die -bewerbungen", en:"speculative application", vi:"ứng tuyển chủ động", ex:"Ich bewerbe mich initiativ, weil mich Ihr Vortrag überzeugt hat.", exEn:"I'm applying speculatively because your talk convinced me.", ipa:"i-ni-tsya-TEEF-be-ver-bung", coll:"sich initiativ bewerben", tip:"Braucht einen eigenen, überprüfbaren Anlass — und nennt kein Gehalt.", topic:"Career", level:"C1" },
  { id:"fc7044", de:"zuschneiden auf", article:"—", plural:"—", en:"to tailor to", vi:"may đo theo", ex:"Der Hauptteil ist auf die Muss-Kriterien der Anzeige zugeschnitten.", exEn:"The main part is tailored to the ad's must-haves.", ipa:"TSUU-shny-den auf", coll:"einen Text auf etwas zuschneiden", tip:"Trennbar. Der Unterschied zwischen einer Bewerbung und einem Serienbrief.", topic:"Career", level:"C1" },

  /* ---- Bewerbung · Netzwerk & Prozess ---- */
  { id:"fc7045", de:"Kurzbeschreibung", article:"die", plural:"die -beschreibungen", en:"headline, short profile", vi:"mô tả ngắn", ex:"Die Kurzbeschreibung nennt Rolle, Stack und Kontext.", exEn:"The headline names role, stack and context.", ipa:"KURTS-be-shry-bung", coll:"eine Kurzbeschreibung formulieren", tip:"Nicht der Firmenname allein — danach sucht keine Recruiterin.", topic:"Career", level:"B2" },
  { id:"fc7046", de:"Ansprache", article:"die", plural:"die Ansprachen", en:"outreach, being approached", vi:"tiếp cận chủ động", ex:"Viele Stellen entstehen über Ansprache, nicht über Bewerbung.", exEn:"Many roles come from being approached, not from applying.", ipa:"AN-shpraa-khe", coll:"über Ansprache zustande kommen", tip:"Deshalb ist das Profil die eigentliche Bewerbung.", topic:"Career", level:"C1" },
  { id:"fc7047", de:"Kontaktanfrage", article:"die", plural:"die -anfragen", en:"connection request", vi:"lời mời kết nối", ex:"Eine Kontaktanfrage ohne Anlass wird meist ignoriert.", exEn:"A connection request without a reason usually gets ignored.", ipa:"kon-TAKT-an-fraa-ge", coll:"eine Kontaktanfrage senden", tip:"Ein Satz Anlass verdoppelt die Annahmequote.", topic:"Career", level:"B2" },
  { id:"fc7048", de:"Empfehlung", article:"die", plural:"die Empfehlungen", en:"referral, recommendation", vi:"giới thiệu", ex:"Eine interne Empfehlung würde mir sehr helfen — kein Problem, wenn es nicht passt.", exEn:"An internal referral would help a lot — no problem if it doesn't fit.", ipa:"emp-FEE-lung", coll:"um eine Empfehlung bitten", tip:"Mach das Nein leicht; genau dadurch wird ein Ja wahrscheinlicher.", topic:"Career", level:"B2" },
  { id:"fc7049", de:"Besetzung", article:"die", plural:"die Besetzungen", en:"filling (of a position)", vi:"tuyển lấp vị trí", ex:"Für die Besetzung wünsche ich Ihnen viel Erfolg.", exEn:"I wish you every success in filling the role.", ipa:"be-ZET-sung", coll:"die Besetzung einer Stelle", tip:"Der Standardsatz jeder höflichen Absage.", topic:"Career", level:"C1" },
  { id:"fc7050", de:"Eingangsbestätigung", article:"die", plural:"die -bestätigungen", en:"acknowledgement of receipt", vi:"xác nhận đã nhận", ex:"Die Eingangsbestätigung kam automatisch, danach zwei Wochen Stille.", exEn:"The acknowledgement came automatically, then two weeks of silence.", ipa:"AYN-gangs-be-shte-ti-gung", coll:"eine Eingangsbestätigung erhalten", tip:"Danach ist Stille Kalender, kein Signal — zwei Wochen sind normal.", topic:"Career", level:"C1" },
  { id:"fc7051", de:"Sichtung", article:"die", plural:"die Sichtungen", en:"screening of applications", vi:"vòng sàng lọc", ex:"Die Sichtung durch HR und Fachbereich dauert ein bis drei Wochen.", exEn:"Screening by HR and the department takes one to three weeks.", ipa:"ZIKH-tung", coll:"in der Sichtung sein", tip:"Zwei Leserkreise, zwei Blickwinkel — dein Anschreiben muss für beide funktionieren.", topic:"Career", level:"C1" },
  { id:"fc7052", de:"Bewerbermanagementsystem", article:"das", plural:"die -systeme", en:"applicant tracking system", vi:"hệ thống quản lý ứng viên", ex:"Grafiklastige Lebensläufe werden vom Bewerbermanagementsystem schlecht ausgelesen.", exEn:"Graphic-heavy CVs are parsed badly by applicant tracking systems.", ipa:"be-VER-ber-ma-nadsch-ment-züs-teem", coll:"über das System einreichen", tip:"Struktur schlägt Gestaltung: klares PDF, echte Überschriften.", topic:"Career", level:"C1" },
  { id:"fc7053", de:"Ausländerbehörde", article:"die", plural:"die -behörden", en:"immigration office", vi:"sở ngoại kiều", ex:"Für meinen Aufenthaltstitel ist die Ausländerbehörde zuständig.", exEn:"The immigration office handles my residence permit.", ipa:"AUS-len-der-be-höör-de", coll:"einen Termin bei der Ausländerbehörde", tip:"Zusammen mit BAMF und Make it in Germany die verlässliche Quelle — Zahlen ändern sich jährlich.", topic:"Career", level:"C1" },
  { id:"fc7054", de:"Anerkennung", article:"die", plural:"die Anerkennungen", en:"recognition (of a degree)", vi:"công nhận bằng cấp", ex:"Die Anerkennung meines Abschlusses prüfe ich über anabin.", exEn:"I check my degree's recognition via anabin.", ipa:"AN-er-ken-nung", coll:"die Anerkennung beantragen", tip:"Für Hochschulabschlüsse zuständig: die ZAB mit ihrer anabin-Datenbank.", topic:"Career", level:"C1" },
  { id:"fc7055", de:"Entgeltgruppe", article:"die", plural:"die Entgeltgruppen", en:"pay grade (under a collective agreement)", vi:"bậc lương", ex:"In tarifgebundenen Firmen liegt das Gehalt in einer Entgeltgruppe fest.", exEn:"In firms under a collective agreement, pay is fixed by grade.", ipa:"ent-GELT-grup-pe", coll:"in eine Entgeltgruppe eingruppiert werden", tip:"Gegenstück: der AT-Vertrag — außertariflich und frei verhandelbar.", topic:"Career", level:"C1" },
  { id:"fc7056", de:"außertariflich (AT)", article:"—", plural:"—", en:"outside the collective agreement", vi:"ngoài thang bảng lương", ex:"Die Stelle ist außertariflich, das Gehalt also verhandelbar.", exEn:"The role is outside the collective agreement, so pay is negotiable.", ipa:"AU-ser-ta-reef-likh", coll:"ein AT-Vertrag", tip:"Liegt in der Regel über der höchsten Entgeltgruppe.", topic:"Career", level:"C1" },
  { id:"fc7057", de:"aussortieren", article:"—", plural:"—", en:"to filter out", vi:"loại bớt", ex:"An der Sprachanforderung sortieren sich viele Bewerbungen selbst aus.", exEn:"Many applications filter themselves out at the language requirement.", ipa:"AUS-zor-tee-ren", coll:"Bewerbungen aussortieren", tip:"Trennbar. Wer die geforderte Stufe hat, sollte sie ausdrücklich nennen.", topic:"Career", level:"B2" },
  { id:"fc7058", de:"gebunden sein", article:"—", plural:"—", en:"to be already committed", vi:"đã có hẹn", ex:"Am Dienstag bin ich leider bereits gebunden.", exEn:"Unfortunately I'm already committed on Tuesday.", ipa:"ge-BUN-den zyn", coll:"anderweitig gebunden sein", tip:"Höflicher als „ich habe keine Zeit“ — nennt keinen Grund und braucht keinen.", topic:"Career", level:"C1" },
  { id:"fc7059", de:"reiflich überlegen", article:"—", plural:"—", en:"to consider carefully", vi:"cân nhắc kỹ", ex:"Nach reiflicher Überlegung habe ich mich für eine andere Position entschieden.", exEn:"After careful consideration I've chosen another position.", ipa:"RYF-likh üü-ber-LEE-gen", coll:"nach reiflicher Überlegung", tip:"Feste Wendung in Absagen — sie signalisiert Respekt vor dem Angebot.", topic:"Career", level:"C1" },
  { id:"fc7060", de:"auffindbar", article:"—", plural:"—", en:"findable, discoverable", vi:"dễ tìm thấy", ex:"Ein deutschsprachiges Profil macht dich für deutsche Suchen auffindbar.", exEn:"A German profile makes you findable in German searches.", ipa:"AUF-fint-baar", coll:"auffindbar sein", tip:"Backend-Entwickler und Backend Developer sind für eine Suchmaske zwei Wörter.", topic:"Career", level:"C1" }
]);
