/*! flashcards-7.js — Phase 3 + Retro/Architektur/Notfall deck (Đợt 5).
 * Merges onto window.FLASHCARDS.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- Phase 3 · Grammar ---- */
  { id:"fc4001", de:"Nominalstil", article:"der", plural:"—", en:"nominal style", vi:"lối viết danh từ hoá", ex:"Der Nominalstil gehört in die Doku, nicht ins Daily.", exEn:"Nominal style belongs in docs, not in the daily.", ipa:"no-mi-NAAL-shteel", coll:"im Nominalstil schreiben", tip:"Nebensatz → Präposition + Nomen: nach der Bereitstellung.", topic:"Grammar", level:"B2" },
  { id:"fc4002", de:"Funktionsverbgefüge", article:"das", plural:"die Funktionsverbgefüge", en:"light-verb construction", vi:"cụm động từ chức năng", ex:"„Eine Entscheidung treffen“ ist ein Funktionsverbgefüge.", exEn:"'To make a decision' is a light-verb construction.", ipa:"funk-TSYOONS-ferp-ge-füü-ge", coll:"ein FVG verwenden", tip:"Als Block lernen — nie wörtlich übersetzen.", topic:"Grammar", level:"C1" },
  { id:"fc4003", de:"zur Verfügung stellen", article:"—", plural:"—", en:"to provide, make available", vi:"cung cấp", ex:"Wir stellen dem Team eine dokumentierte Schnittstelle zur Verfügung.", exEn:"We provide the team a documented interface.", ipa:"tsur fer-FÜÜ-gung SHTEL-len", coll:"jemandem etwas zur Verfügung stellen", tip:"Formeller als „bereitstellen“.", topic:"Workplace", level:"B2" },
  { id:"fc4004", de:"in Betrieb nehmen", article:"—", plural:"—", en:"to put into operation, go live", vi:"đưa vào vận hành", ex:"Das Dashboard wird nächste Woche in Betrieb genommen.", exEn:"The dashboard goes live next week.", ipa:"in be-TREEP NEE-men", coll:"in / außer Betrieb nehmen", tip:"Gegenteil: außer Betrieb nehmen = abschalten.", topic:"DevOps", level:"B2" },
  { id:"fc4005", de:"eine Entscheidung treffen", article:"—", plural:"—", en:"to make a decision", vi:"ra quyết định", ex:"Das Team hat die Entscheidung getroffen, auf Events umzustellen.", exEn:"The team decided to switch to events.", ipa:"AYN-e ent-SHY-dung TREF-fen", coll:"eine Entscheidung treffen/revidieren", tip:"treffen, NICHT machen — häufigster Anglizismus-Fehler.", topic:"Workplace", level:"B2" },
  { id:"fc4006", de:"Partizipialattribut", article:"das", plural:"die -attribute", en:"participial attribute", vi:"định ngữ phân từ", ex:"„Die vom Client gesendete Anfrage“ ist ein Partizipialattribut.", exEn:"'The request sent by the client' is a participial attribute.", ipa:"par-ti-tsi-pi-AAL-at-tri-buut", coll:"ein Attribut auflösen", tip:"Lesen: Nomen zuerst suchen, dann rückwärts.", topic:"Grammar", level:"C1" },
  { id:"fc4007", de:"sodass", article:"—", plural:"—", en:"so that (result)", vi:"đến mức mà", ex:"Wir cachen die Antworten, sodass die Latenz sinkt.", exEn:"We cache responses so that latency drops.", ipa:"zo-DAS", coll:"…, sodass …", tip:"Subordinierend → Verb ans Ende. Folge, nicht Zweck.", topic:"Grammar", level:"B2" },
  { id:"fc4008", de:"indem", article:"—", plural:"—", en:"by (means of) …-ing", vi:"bằng cách", ex:"Wir erhöhen den Durchsatz, indem wir horizontal skalieren.", exEn:"We increase throughput by scaling horizontally.", ipa:"in-DEEM", coll:"…, indem …", tip:"Antwortet auf „wie?“. Verb ans Ende.", topic:"Grammar", level:"B2" },
  { id:"fc4009", de:"wohingegen", article:"—", plural:"—", en:"whereas", vi:"trong khi đó thì", ex:"REST ist zustandslos, wohingegen eine Session Zustand hält.", exEn:"REST is stateless, whereas a session holds state.", ipa:"vo-hin-GEE-gen", coll:"…, wohingegen …", tip:"Starker Gegensatz, formeller als „während“.", topic:"Grammar", level:"C1" },
  { id:"fc4010", de:"sofern", article:"—", plural:"—", en:"provided that", vi:"với điều kiện là", ex:"Sofern die Tests grün sind, wird deployt.", exEn:"Provided the tests are green, we deploy.", ipa:"zo-FERN", coll:"Sofern …, …", tip:"Bedingung, formeller als „wenn“.", topic:"Grammar", level:"C1" },

  /* ---- Phase 3 · Vocabulary ---- */
  { id:"fc4011", de:"Zugriffsberechtigung", article:"die", plural:"die -berechtigungen", en:"access permission", vi:"quyền truy cập", ex:"Die Zugriffsberechtigung wird im Gateway geprüft.", exEn:"Access permission is checked in the gateway.", ipa:"TSUU-grifs-be-rekh-ti-gung", coll:"eine Berechtigung erteilen/entziehen", tip:"Kopf: die Berechtigung.", topic:"Security", level:"B2" },
  { id:"fc4012", de:"Ausfallsicherheit", article:"die", plural:"—", en:"fault tolerance", vi:"khả năng chịu lỗi", ex:"Die Ausfallsicherheit erreichen wir über drei Replikate.", exEn:"We achieve fault tolerance with three replicas.", ipa:"AUS-fal-zikh-er-hyt", coll:"Ausfallsicherheit erhöhen", tip:"Kopf: die Sicherheit → die.", topic:"Architecture", level:"B2" },
  { id:"fc4013", de:"Lastverteilung", article:"die", plural:"die -verteilungen", en:"load balancing", vi:"cân bằng tải", ex:"Die Lastverteilung übernimmt ein Load Balancer.", exEn:"A load balancer handles the load balancing.", ipa:"LAST-fer-ty-lung", coll:"die Last verteilen", tip:"-ung → die.", topic:"Architecture", level:"B2" },
  { id:"fc4014", de:"Durchsatz", article:"der", plural:"—", en:"throughput", vi:"thông lượng", ex:"Wir haben den Durchsatz von 100 auf 500 Anfragen erhöht.", exEn:"We raised throughput from 100 to 500 requests.", ipa:"DURKH-zats", coll:"den Durchsatz erhöhen", tip:"Gegenstück zur Latenz.", topic:"Architecture", level:"B2" },
  { id:"fc4015", de:"Zwischenspeicherung", article:"die", plural:"die -speicherungen", en:"caching", vi:"bộ nhớ đệm", ex:"Die Zwischenspeicherung entlastet die Datenbank.", exEn:"Caching relieves the database.", ipa:"TSVI-shen-shpy-khe-rung", coll:"eine Zwischenspeicherung einführen", tip:"Auch: der Cache. -ung → die.", topic:"Architecture", level:"B2" },
  { id:"fc4016", de:"Fugenelement", article:"das", plural:"die Fugenelemente", en:"linking letter in a compound", vi:"chữ nối trong từ ghép", ex:"Das -s- in „Zugriffsberechtigung“ ist ein Fugenelement.", exEn:"The -s- in 'Zugriffsberechtigung' is a linking letter.", ipa:"FUU-gen-e-le-ment", coll:"ein Fugenelement einfügen", tip:"Für die Bedeutung ignorieren.", topic:"Grammar", level:"C1" },
  { id:"fc4017", de:"ausrollen", article:"—", plural:"—", en:"to roll out", vi:"triển khai dần", ex:"Wir rollen das Feature schrittweise auf alle Regionen aus.", exEn:"We roll the feature out region by region.", ipa:"AUS-rol-len", coll:"ein Feature ausrollen", tip:"Trennbar: rollt … aus.", topic:"DevOps", level:"B2" },
  { id:"fc4018", de:"entlasten", article:"—", plural:"—", en:"to relieve, offload", vi:"giảm tải", ex:"Der Cache entlastet die Datenbank erheblich.", exEn:"The cache relieves the database considerably.", ipa:"ent-LAS-ten", coll:"ein System entlasten", tip:"Gegenteil: belasten.", topic:"Architecture", level:"B2" },
  { id:"fc4019", de:"invalidieren", article:"—", plural:"—", en:"to invalidate", vi:"làm mất hiệu lực", ex:"Der Cache wird bei jeder Änderung invalidiert.", exEn:"The cache is invalidated on every change.", ipa:"in-va-li-DEE-ren", coll:"einen Cache invalidieren", tip:"Auch: ungültig machen.", topic:"Architecture", level:"C1" },
  { id:"fc4020", de:"nachgelagert", article:"—", plural:"—", en:"downstream", vi:"phía sau trong chuỗi", ex:"Die Anfrage geht an einen nachgelagerten Dienst.", exEn:"The request goes to a downstream service.", ipa:"NAAKH-ge-laa-gert", coll:"ein nachgelagerter Dienst", tip:"Gegenteil: vorgelagert (upstream).", topic:"Architecture", level:"C1" },

  /* ---- Phase 3 · Writing ---- */
  { id:"fc4021", de:"Akzeptanzkriterium", article:"das", plural:"die -kriterien", en:"acceptance criterion", vi:"tiêu chí nghiệm thu", ex:"Jedes Akzeptanzkriterium muss abhakbar sein.", exEn:"Every acceptance criterion must be checkable.", ipa:"ak-tsep-TANTS-kri-tee-ri-um", coll:"Akzeptanzkriterien formulieren", tip:"Binär prüfbar — nie „besser“.", topic:"Agile", level:"B2" },
  { id:"fc4022", de:"Voraussetzung", article:"die", plural:"die Voraussetzungen", en:"prerequisite", vi:"điều kiện tiên quyết", ex:"Unter „Voraussetzungen“ steht, was installiert sein muss.", exEn:"Under 'prerequisites' it says what must be installed.", ipa:"for-AUS-zets-ung", coll:"eine Voraussetzung erfüllen", tip:"Wichtigstes README-Wort.", topic:"Software Development", level:"B2" },
  { id:"fc4023", de:"Nachvollziehbarkeit", article:"die", plural:"—", en:"traceability", vi:"khả năng truy vết", ex:"Die Nachvollziehbarkeit sinkt, deshalb brauchen wir Tracing.", exEn:"Traceability drops, so we need tracing.", ipa:"naakh-fol-TSEE-baar-kyt", coll:"die Nachvollziehbarkeit sicherstellen", tip:"-keit → die.", topic:"Architecture", level:"C1" },
  { id:"fc4024", de:"abweisen", article:"—", plural:"—", en:"to reject (a request)", vi:"từ chối, chặn", ex:"Abgelaufene Tokens werden mit 401 abgewiesen.", exEn:"Expired tokens are rejected with a 401.", ipa:"AP-vy-zen", coll:"eine Anfrage abweisen", tip:"Trennbar. Partizip: abgewiesen.", topic:"Security", level:"B2" },

  /* ---- Retrospektive ---- */
  { id:"fc4025", de:"Retrospektive", article:"die", plural:"die Retrospektiven", en:"retrospective", vi:"họp nhìn lại sprint", ex:"In der Retrospektive besprechen wir den Prozess, nicht Personen.", exEn:"In the retro we discuss the process, not people.", ipa:"re-tro-spek-TEE-ve", coll:"eine Retro moderieren", tip:"Kurz: die Retro.", topic:"Agile", level:"B2" },
  { id:"fc4026", de:"untergehen", article:"—", plural:"—", en:"to get lost, be overlooked", vi:"bị bỏ sót", ex:"Es ist untergegangen, dass da eine Migration dranhängt.", exEn:"It got overlooked that a migration is attached.", ipa:"UN-ter-gee-en", coll:"Es ist untergegangen, dass …", tip:"Perfekt mit sein. Kritik OHNE Schuldzuweisung.", topic:"Workplace", level:"B2" },
  { id:"fc4027", de:"Maßnahme", article:"die", plural:"die Maßnahmen", en:"action item, measure", vi:"biện pháp", ex:"Wir nehmen das als Maßnahme auf.", exEn:"We'll take that as an action item.", ipa:"MAAS-naa-me", coll:"eine Maßnahme beschließen", tip:"Retro ohne Maßnahme + Name war keine Retro.", topic:"Agile", level:"B2" },
  { id:"fc4028", de:"Bedenken", article:"die", plural:"(nur Plural)", en:"reservations, concerns", vi:"quan ngại", ex:"Ich hätte Bedenken, dass das Refinement zu lang wird.", exEn:"I'd worry that refinement gets too long.", ipa:"be-DEN-ken", coll:"Bedenken äußern/haben", tip:"„Ich hätte Bedenken“ = weichster Widerspruch.", topic:"Workplace", level:"B2" },
  { id:"fc4029", de:"überziehen", article:"—", plural:"—", en:"to overrun (a meeting)", vi:"họp quá giờ", ex:"Wir sind jetzt schon regelmäßig überzogen.", exEn:"We already regularly overrun.", ipa:"üü-ber-TSEE-en", coll:"ein Meeting überziehen", tip:"Untrennbar hier: überzogen.", topic:"Workplace", level:"B2" },
  { id:"fc4030", de:"dranhängen", article:"—", plural:"—", en:"to be attached to it", vi:"dính kèm theo", ex:"Da hängt noch eine Migration dran.", exEn:"There's still a migration attached to that.", ipa:"DRAN-heng-en", coll:"an etwas dranhängen", tip:"Umgangssprachlich, trennbar.", topic:"Workplace", level:"B2" },

  /* ---- Architektur-Diskussion ---- */
  { id:"fc4031", de:"Einwand", article:"der", plural:"die Einwände", en:"objection", vi:"ý phản biện", ex:"Da hätte ich einen Einwand.", exEn:"I'd have an objection there.", ipa:"AYN-vant", coll:"einen Einwand erheben", tip:"Umlaut im Plural.", topic:"Speaking", level:"B2" },
  { id:"fc4032", de:"Anbindung", article:"die", plural:"die Anbindungen", en:"integration, connection", vi:"tích hợp", ex:"Wir diskutieren die Anbindung des Zahlungsdienstes.", exEn:"We're discussing the payment service integration.", ipa:"AN-bin-dung", coll:"eine Anbindung realisieren", tip:"-ung → die. Verb: anbinden.", topic:"Architecture", level:"B2" },
  { id:"fc4033", de:"plädieren", article:"—", plural:"—", en:"to argue in favour of", vi:"ủng hộ", ex:"Ich plädiere dafür, den Dienst asynchron anzubinden.", exEn:"I'm in favour of connecting the service asynchronously.", ipa:"ple-DEE-ren", coll:"plädieren für + Akk / dafür, … zu …", tip:"Formeller als „Ich bin dafür“.", topic:"Speaking", level:"C1" },
  { id:"fc4034", de:"gegenüberstellen", article:"—", plural:"—", en:"to compare side by side", vi:"đối chiếu", ex:"Lass uns die beiden Optionen gegenüberstellen.", exEn:"Let's put the two options side by side.", ipa:"gee-gen-ÜÜ-ber-shtel-len", coll:"zwei Optionen gegenüberstellen", tip:"Trennbar.", topic:"Speaking", level:"B2" },
  { id:"fc4035", de:"entkoppeln", article:"—", plural:"—", en:"to decouple", vi:"tách rời", ex:"Events entkoppeln die beiden Dienste.", exEn:"Events decouple the two services.", ipa:"ent-KOP-peln", coll:"Dienste entkoppeln", tip:"Nomen: die Entkopplung.", topic:"Architecture", level:"B2" },
  { id:"fc4036", de:"Voraussetzung (unter der …, dass)", article:"die", plural:"—", en:"provided that", vi:"với điều kiện là", ex:"Unter der Voraussetzung, dass wir die Statusanzeige bauen, bin ich einverstanden.", exEn:"Provided we build the status display, I agree.", ipa:"for-AUS-zets-ung", coll:"unter der Voraussetzung, dass …", tip:"Bedingte Zustimmung — zustimmen, ohne das Bedenken fallen zu lassen.", topic:"Speaking", level:"C1" },

  /* ---- Deployment-Notfall ---- */
  { id:"fc4037", de:"Rollback", article:"das", plural:"die Rollbacks", en:"rollback", vi:"quay lui phiên bản", ex:"Dann würde ich vorschlagen, wir machen erst mal ein Rollback.", exEn:"Then I'd suggest we roll back for now.", ipa:"ROL-bek", coll:"ein Rollback machen", tip:"Verb: zurückrollen. Kein Zeichen von Aufgeben.", topic:"DevOps", level:"B2" },
  { id:"fc4038", de:"Vorfall", article:"der", plural:"die Vorfälle", en:"incident", vi:"sự cố", ex:"Ausgelöst wurde der Vorfall durch eine Konfigurationsänderung.", exEn:"The incident was triggered by a config change.", ipa:"FOR-fal", coll:"einen Vorfall melden", tip:"Umlaut im Plural.", topic:"DevOps", level:"B2" },
  { id:"fc4039", de:"Auslöser", article:"der", plural:"die Auslöser", en:"trigger, cause", vi:"nguyên nhân kích hoạt", ex:"Der Auslöser war das Verbindungslimit.", exEn:"The trigger was the connection limit.", ipa:"AUS-löö-zer", coll:"den Auslöser finden", tip:"Plural = Singular. Verb: auslösen.", topic:"DevOps", level:"B2" },
  { id:"fc4040", de:"rangehen", article:"—", plural:"—", en:"to pick up (the phone)", vi:"bắt máy", ex:"Danke fürs schnelle Rangehen.", exEn:"Thanks for picking up so fast.", ipa:"RAN-gee-en", coll:"ans Telefon rangehen", tip:"Umgangssprachlich, trennbar.", topic:"Alltag", level:"B2" },
  { id:"fc4041", de:"anfassen", article:"—", plural:"—", en:"to touch, to modify", vi:"đụng vào, sửa", ex:"Wir haben da das Verbindungslimit angefasst.", exEn:"We touched the connection limit there.", ipa:"AN-fas-sen", coll:"eine Konfiguration anfassen", tip:"Dev-Umgangssprache für „ändern“.", topic:"DevOps", level:"B2" },
  { id:"fc4042", de:"sporadisch", article:"—", plural:"—", en:"sporadic", vi:"thỉnh thoảng", ex:"Reproduzierbar ist es nicht — eher sporadisch.", exEn:"It's not reproducible — more sporadic.", ipa:"spo-RAA-dish", coll:"sporadisch auftreten", tip:"Gegenteil: reproduzierbar.", topic:"DevOps", level:"B2" },
  { id:"fc4043", de:"reproduzierbar", article:"—", plural:"—", en:"reproducible", vi:"tái hiện được", ex:"Ist der Fehler reproduzierbar?", exEn:"Is the error reproducible?", ipa:"re-pro-du-TSEER-baar", coll:"reproduzierbar sein", tip:"Erste Frage in jedem Incident-Call.", topic:"DevOps", level:"B2" },
  { id:"fc4044", de:"Beobachtung", article:"die", plural:"die Beobachtungen", en:"observation", vi:"quan sát", ex:"Nenne zuerst die Beobachtung, dann die Vermutung.", exEn:"State the observation first, then the hypothesis.", ipa:"be-OH-bakh-tung", coll:"eine Beobachtung schildern", tip:"Beobachtung vor Interpretation — die Regel im Notfall.", topic:"DevOps", level:"B2" },
  { id:"fc4045", de:"eingreifen", article:"—", plural:"—", en:"to intervene", vi:"can thiệp", ex:"Klärt vorher, wer eingreift — sonst machen es zwei gleichzeitig.", exEn:"Agree who intervenes — otherwise two people do it at once.", ipa:"AYN-gry-fen", coll:"in ein System eingreifen", tip:"Trennbar. Nomen: der Eingriff.", topic:"DevOps", level:"B2" }
]);
