/*! flashcards-3.js — Foundations deck (systems vocabulary + verb signatures). Merges onto window.FLASHCARDS. */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- systems & learning meta-vocabulary ---- */
  { id:"fc901", de:"Zusammenhang", article:"der", plural:"die Zusammenhänge", en:"connection, interrelation", vi:"mối liên hệ", ex:"Im System hängt alles miteinander zusammen.", exEn:"In a system, everything is interconnected.", ipa:"tsu-ZAM-men-hang", coll:"einen Zusammenhang erkennen/verstehen", tip:"Verb: zusammenhängen mit + Dat.", topic:"Foundations", level:"B2" },
  { id:"fc902", de:"Muster", article:"das", plural:"die Muster", en:"pattern", vi:"khuôn mẫu", ex:"Suche das Muster, nicht die Ausnahme.", exEn:"Look for the pattern, not the exception.", ipa:"MUS-ter", coll:"ein Muster erkennen/anwenden", tip:"Plural = Singular. Design Pattern = das Entwurfsmuster.", topic:"Foundations", level:"B1" },
  { id:"fc903", de:"Satzklammer", article:"die", plural:"die Satzklammern", en:"sentence bracket", vi:"khung động từ", ex:"Das Verb öffnet die Satzklammer, das Partizip schließt sie.", exEn:"The verb opens the bracket, the participle closes it.", ipa:"ZATS-klam-mer", coll:"die Satzklammer bilden", tip:"Ich HABE den Service gestern DEPLOYT — bracket!", topic:"Foundations", level:"B1" },
  { id:"fc904", de:"Kompositum", article:"das", plural:"die Komposita", en:"compound word", vi:"từ ghép", ex:"Ein Kompositum liest man von rechts nach links.", exEn:"You read a compound from right to left.", ipa:"kom-POH-zi-tum", coll:"ein Kompositum zerlegen/bilden", tip:"Last noun = gender + base meaning (head-final).", topic:"Foundations", level:"B2" },
  { id:"fc905", de:"Vorsilbe", article:"die", plural:"die Vorsilben", en:"prefix", vi:"tiền tố", ex:"Die Vorsilbe ändert die Bedeutung des Verbs.", exEn:"The prefix changes the verb's meaning.", ipa:"FOR-zil-be", coll:"eine trennbare/untrennbare Vorsilbe", tip:"stellen → einstellen, bereitstellen, umstellen …", topic:"Foundations", level:"B1" },
  { id:"fc906", de:"Endung", article:"die", plural:"die Endungen", en:"(grammatical) ending", vi:"đuôi từ", ex:"Die Endung -ung macht das Nomen feminin.", exEn:"The ending -ung makes the noun feminine.", ipa:"EN-dung", coll:"die richtige Endung wählen", tip:"-ung/-heit/-keit → die · -chen → das · -er (Gerät) → der.", topic:"Foundations", level:"B1" },
  { id:"fc907", de:"Engpass", article:"der", plural:"die Engpässe", en:"bottleneck", vi:"nút thắt cổ chai", ex:"Sprechen ist mein Engpass, nicht Lesen.", exEn:"Speaking is my bottleneck, not reading.", ipa:"ENG-pas", coll:"den Engpass finden/beheben", tip:"Also: der Flaschenhals. Practice AT the constraint.", topic:"Foundations", level:"B2" },
  { id:"fc908", de:"Rückmeldung", article:"die", plural:"die Rückmeldungen", en:"feedback", vi:"phản hồi", ex:"Ohne Rückmeldung wiederhole ich meine Fehler.", exEn:"Without feedback I repeat my mistakes.", ipa:"RUEK-mel-dung", coll:"Rückmeldung geben/bekommen/einholen", tip:"Also 'das Feedback'. The correction loop needs it!", topic:"Foundations", level:"B1" },
  { id:"fc909", de:"Gewohnheit", article:"die", plural:"die Gewohnheiten", en:"habit", vi:"thói quen", ex:"Kleine Gewohnheiten schlagen große Pläne.", exEn:"Small habits beat big plans.", ipa:"ge-VOHN-hyt", coll:"eine Gewohnheit aufbauen/beibehalten", tip:"-heit → die. sich an etwas gewöhnen = get used to.", topic:"Foundations", level:"B1" },
  { id:"fc910", de:"Abruf", article:"der", plural:"die Abrufe", en:"retrieval, recall", vi:"truy xuất, gợi nhớ", ex:"Erst der Abruf macht Wörter aktiv.", exEn:"Only retrieval makes words active.", ipa:"AP-roof", coll:"auf Abruf; etwas abrufen", tip:"Verb: abrufen. Reading fills passive; retrieval fills active.", topic:"Foundations", level:"B2" },
  { id:"fc911", de:"Wiederholung", article:"die", plural:"die Wiederholungen", en:"repetition, review", vi:"sự ôn tập", ex:"Die Wiederholung kommt kurz vor dem Vergessen.", exEn:"The review comes just before forgetting.", ipa:"vee-der-HOH-lung", coll:"regelmäßige Wiederholung; Wiederholungen leeren (Anki)", tip:"SRS = spaced repetition = verteilte Wiederholung.", topic:"Foundations", level:"B1" },
  { id:"fc912", de:"Selbstgespräch", article:"das", plural:"die Selbstgespräche", en:"self-talk", vi:"tự nói một mình", ex:"Beim Debuggen führe ich Selbstgespräche auf Deutsch.", exEn:"While debugging I talk to myself in German.", ipa:"ZELPST-ge-shprayk", coll:"Selbstgespräche führen", tip:"Your staging environment — safe, daily.", topic:"Foundations", level:"B2" },
  { id:"fc913", de:"Fehlerjournal", article:"das", plural:"die Fehlerjournale", en:"error journal / log", vi:"nhật ký lỗi", ex:"Jede Korrektur kommt ins Fehlerjournal.", exEn:"Every correction goes into the error journal.", ipa:"FAY-ler-zhur-nahl", coll:"das Fehlerjournal führen/reviewen", tip:"Your personal bug tracker — see the Journal tool in this app.", topic:"Foundations", level:"B2" },
  { id:"fc914", de:"durchhalten", article:"", plural:"—", en:"to persevere, keep going", vi:"kiên trì", ex:"Im Plateau musst du einfach durchhalten.", exEn:"In the plateau you simply have to keep going.", ipa:"DURKH-hal-ten", coll:"bis zum Ziel durchhalten", tip:"Separable: ich halte durch. The plateau is delay, not failure.", topic:"Foundations", level:"B2" },
  { id:"fc915", de:"ableiten", article:"", plural:"—", en:"to derive", vi:"suy ra, phái sinh", ex:"Das Genus kann man oft von der Endung ableiten.", exEn:"You can often derive the gender from the ending.", ipa:"AP-ly-ten", coll:"eine Regel ableiten", tip:"Separable: ich leite ab. Learn patterns, derive words.", topic:"Foundations", level:"B2" },
  /* ---- verb signatures (Verb + Präposition + Kasus als EINE Einheit) ---- */
  { id:"fc916", de:"abhängen von + Dativ", article:"", plural:"—", en:"to depend on", vi:"phụ thuộc vào", ex:"Das Release hängt von den Tests ab.", exEn:"The release depends on the tests.", ipa:"AP-heng-en fon", coll:"Das hängt davon ab, ob …", tip:"Separable! davon abhängen = depend on it.", topic:"Foundations", level:"B1" },
  { id:"fc917", de:"warten auf + Akkusativ", article:"", plural:"—", en:"to wait for", vi:"chờ đợi", ex:"Wir warten auf das Code-Review.", exEn:"We are waiting for the code review.", ipa:"VAR-ten owf", coll:"auf den Build/die Antwort warten", tip:"NEVER 'warten für'. Signature = one unit.", topic:"Foundations", level:"B1" },
  { id:"fc918", de:"sich kümmern um + Akkusativ", article:"", plural:"—", en:"to take care of", vi:"lo liệu, phụ trách", ex:"Ich kümmere mich um das Deployment.", exEn:"I'll take care of the deployment.", ipa:"KUEM-mern um", coll:"sich um ein Ticket kümmern", tip:"Standup gold: 'Ich kümmere mich darum.'", topic:"Foundations", level:"B1" },
  { id:"fc919", de:"zugreifen auf + Akkusativ", article:"", plural:"—", en:"to access", vi:"truy cập", ex:"Der Dienst greift auf die Datenbank zu.", exEn:"The service accesses the database.", ipa:"TSOO-gry-fen owf", coll:"auf Daten/die API zugreifen", tip:"Separable: greift … zu. Noun: der Zugriff auf + Akk.", topic:"Foundations", level:"B2" },
  { id:"fc920", de:"helfen + Dativ", article:"", plural:"—", en:"to help", vi:"giúp đỡ", ex:"Ich helfe dem neuen Kollegen.", exEn:"I'm helping the new colleague.", ipa:"HEL-fen", coll:"jemandem bei etwas helfen", tip:"Dativ verb! 'Ich helfe dir' (never dich).", topic:"Foundations", level:"B1" },
  { id:"fc921", de:"teilnehmen an + Dativ", article:"", plural:"—", en:"to participate in", vi:"tham gia", ex:"Ich nehme am Daily teil.", exEn:"I take part in the daily.", ipa:"TYL-nay-men an", coll:"an einem Meeting/Workshop teilnehmen", tip:"an + dem = am. Separable: nehme … teil.", topic:"Foundations", level:"B1" },
  { id:"fc922", de:"sich bewerben um + Akkusativ", article:"", plural:"—", en:"to apply for (a job)", vi:"ứng tuyển", ex:"Ich bewerbe mich um die Stelle bei SAP.", exEn:"I'm applying for the position at SAP.", ipa:"be-VER-ben um", coll:"sich bei einer Firma um eine Stelle bewerben", tip:"um die Stelle (Akk), bei der Firma (Dat). Noun: die Bewerbung.", topic:"Foundations", level:"B2" },
  { id:"fc923", de:"bestehen aus + Dativ", article:"", plural:"—", en:"to consist of", vi:"bao gồm", ex:"Das System besteht aus drei Services.", exEn:"The system consists of three services.", ipa:"be-SHTAY-en ows", coll:"aus Komponenten bestehen", tip:"bestehen auf + Dat = insist; eine Prüfung bestehen = pass!", topic:"Foundations", level:"B2" },
  { id:"fc924", de:"achten auf + Akkusativ", article:"", plural:"—", en:"to pay attention to", vi:"chú ý đến", ex:"Achte auf die Verbposition.", exEn:"Pay attention to the verb position.", ipa:"AKH-ten owf", coll:"auf Details/Fehler achten", tip:"Code review phrase: 'Achte bitte auf …'", topic:"Foundations", level:"B1" },
  { id:"fc925", de:"sich freuen auf + Akkusativ", article:"", plural:"—", en:"to look forward to", vi:"mong chờ", ex:"Ich freue mich auf den Feierabend.", exEn:"I'm looking forward to the end of the workday.", ipa:"FROY-en owf", coll:"sich auf das Wochenende freuen", tip:"auf = future; über + Akk = about something present.", topic:"Foundations", level:"B1" },
  { id:"fc926", de:"sich konzentrieren auf + Akkusativ", article:"", plural:"—", en:"to focus on", vi:"tập trung vào", ex:"Diesen Monat konzentriere ich mich auf das Sprechen.", exEn:"This month I'm focusing on speaking.", ipa:"kon-tsen-TREE-ren owf", coll:"sich auf den Engpass konzentrieren", tip:"Practice at the constraint — auf + Akk.", topic:"Foundations", level:"B2" }
]);
