/*! flashcards-8.js — Phase 4 (Professional Communication) + Templates deck (Đợt 6).
 * Merges onto window.FLASHCARDS.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- Phase 4 · Grammar (formales Register) ---- */
  { id:"fc5001", de:"indirekte Rede", article:"die", plural:"—", en:"reported speech", vi:"lời nói gián tiếp", ex:"Im Protokoll steht die Diskussion in indirekter Rede.", exEn:"In the minutes the discussion is in reported speech.", ipa:"in-di-REK-te REE-de", coll:"etwas in indirekter Rede wiedergeben", tip:"Signalisiert Distanz, nicht Zweifel: „so wurde es gesagt“.", topic:"Grammar", level:"C1" },
  { id:"fc5002", de:"Konjunktiv I", article:"der", plural:"die Konjunktive", en:"subjunctive I", vi:"lối cầu khiến I", ex:"Er sagte, das Release sei fertig — Konjunktiv I.", exEn:"He said the release was ready — subjunctive I.", ipa:"KON-yunk-teef AYNS", coll:"im Konjunktiv I berichten", tip:"3. Sg.: sei, habe, könne, müsse, werde.", topic:"Grammar", level:"C1" },
  { id:"fc5003", de:"Ausweichform", article:"die", plural:"die Ausweichformen", en:"fallback form", vi:"dạng thay thế", ex:"Sieht Konjunktiv I wie der Indikativ aus, nimmt man die Ausweichform.", exEn:"If subjunctive I looks like the indicative, you take the fallback form.", ipa:"AUS-vykh-form", coll:"auf die Ausweichform zurückgreifen", tip:"Konjunktiv II (hätten, müssten) oder würde + Infinitiv.", topic:"Grammar", level:"C1" },
  { id:"fc5004", de:"mitteilen", article:"—", plural:"—", en:"to inform, to state", vi:"thông báo", ex:"Der Product Owner teilte mit, die Ursache sei bekannt.", exEn:"The PO stated that the cause was known.", ipa:"MIT-tay-len", coll:"jemandem etwas mitteilen", tip:"Trennbar. Protokollverb — formeller als „sagen“.", topic:"Workplace", level:"B2" },
  { id:"fc5005", de:"darauf hinweisen", article:"—", plural:"—", en:"to point out", vi:"chỉ ra", ex:"Herr Klein wies darauf hin, die Tests seien unvollständig.", exEn:"Mr Klein pointed out that the tests were incomplete.", ipa:"da-RAUF HIN-vy-zen", coll:"darauf hinweisen, dass …", tip:"Präteritum: wies … hin. Standard-Einleitung im Protokoll.", topic:"Workplace", level:"C1" },
  { id:"fc5006", de:"zu bedenken geben", article:"—", plural:"—", en:"to raise a concern", vi:"nêu quan ngại", ex:"Frau Weber gab zu bedenken, dass ein Werktag riskant sei.", exEn:"Ms Weber raised the concern that a weekday would be risky.", ipa:"tsu be-DEN-ken GEE-ben", coll:"zu bedenken geben, dass …", tip:"Weicher als „widersprechen“ — Einwand ohne Blockade.", topic:"Workplace", level:"C1" },
  { id:"fc5007", de:"Vorgangspassiv", article:"das", plural:"—", en:"process passive", vi:"bị động quá trình", ex:"„Das Ticket wird geschlossen“ ist Vorgangspassiv.", exEn:"'The ticket is being closed' is the process passive.", ipa:"FOR-gangs-pas-eef", coll:"im Vorgangspassiv formulieren", tip:"werden + Partizip II = es passiert gerade.", topic:"Grammar", level:"B2" },
  { id:"fc5008", de:"Zustandspassiv", article:"das", plural:"—", en:"statal passive", vi:"bị động trạng thái", ex:"„Das Ticket ist geschlossen“ ist Zustandspassiv.", exEn:"'The ticket is closed' is the statal passive.", ipa:"TSU-shtands-pas-eef", coll:"im Zustandspassiv formulieren", tip:"sein + Partizip II = das Ergebnis.", topic:"Grammar", level:"B2" },
  { id:"fc5009", de:"worden", article:"—", plural:"—", en:"been (passive participle of werden)", vi:"đã bị/được (phân từ bị động)", ex:"Der Hotfix ist gestern ausgeliefert worden.", exEn:"The hotfix was shipped yesterday.", ipa:"VOR-den", coll:"ist … worden", tip:"Nie „geworden“ im Passiv — „geworden“ nur beim Vollverb.", topic:"Grammar", level:"B2" },
  { id:"fc5010", de:"grundsätzlich", article:"—", plural:"—", en:"in principle, fundamentally", vi:"về nguyên tắc", ex:"Das ist grundsätzlich machbar, die Frist müssten wir aber verschieben.", exEn:"That's doable in principle, but we'd have to move the deadline.", ipa:"GRUNT-zets-likh", coll:"grundsätzlich möglich / machbar", tip:"Ein Ja mit eingebauter Bedingung.", topic:"Workplace", level:"B2" },
  { id:"fc5011", de:"gegebenenfalls (ggf.)", article:"—", plural:"—", en:"if applicable, where necessary", vi:"nếu cần", ex:"Ausnahmen sind ggf. schriftlich zu beantragen.", exEn:"Exceptions must be applied for in writing where necessary.", ipa:"ge-GEE-be-nen-fals", coll:"ggf. beantragen / anpassen", tip:"Amts- und Firmendeutsch; fast immer abgekürzt.", topic:"Workplace", level:"C1" },
  { id:"fc5012", de:"unter Umständen (u. U.)", article:"—", plural:"—", en:"possibly, under certain circumstances", vi:"trong một số trường hợp", ex:"Unter Umständen brauchen wir ein Wartungsfenster.", exEn:"We may possibly need a maintenance window.", ipa:"UN-ter UM-shten-den", coll:"unter Umständen nötig sein", tip:"Hedging: du sagst etwas, ohne dich festzulegen.", topic:"Workplace", level:"B2" },
  { id:"fc5013", de:"einräumen", article:"—", plural:"—", en:"to concede, to admit", vi:"thừa nhận", ex:"Ich räume ein, dass das Argument stichhaltig ist.", exEn:"I concede that the argument holds.", ipa:"AYN-roy-men", coll:"einen Punkt einräumen", tip:"Trennbar. In deutscher Fachdiskussion ein Stärkezeichen.", topic:"Speaking", level:"C1" },

  /* ---- Phase 4 · Vocabulary (Besprechungsdeutsch) ---- */
  { id:"fc5014", de:"Tagesordnung", article:"die", plural:"die Tagesordnungen", en:"agenda", vi:"chương trình họp", ex:"Ich stelle die Tagesordnung auf und schicke sie mit der Einladung.", exEn:"I'll draw up the agenda and send it with the invitation.", ipa:"TAA-ges-ord-nung", coll:"die Tagesordnung aufstellen / durchgehen", tip:"-ung → die. Abkürzung der Punkte: TOP.", topic:"Workplace", level:"B2" },
  { id:"fc5015", de:"Tagesordnungspunkt (TOP)", article:"der", plural:"die Tagesordnungspunkte", en:"agenda item", vi:"mục chương trình họp", ex:"Kommen wir zum nächsten Tagesordnungspunkt.", exEn:"Let's move to the next agenda item.", ipa:"TAA-ges-ord-nungs-punkt", coll:"einen TOP aufrufen", tip:"Der meistgebrauchte Moderationssatz überhaupt.", topic:"Workplace", level:"B2" },
  { id:"fc5016", de:"Abstimmung", article:"die", plural:"die Abstimmungen", en:"alignment; vote", vi:"phối hợp; biểu quyết", ex:"Nach der Abstimmung mit dem Betrieb steht der Termin.", exEn:"After aligning with ops the date is set.", ipa:"AP-shtim-ung", coll:"sich abstimmen mit; eine Abstimmung durchführen", tip:"Zwei Bedeutungen — der Kontext entscheidet.", topic:"Workplace", level:"B2" },
  { id:"fc5017", de:"Vieraugengespräch", article:"das", plural:"die Vieraugengespräche", en:"one-on-one", vi:"họp riêng hai người", ex:"Das klären wir besser im Vieraugengespräch.", exEn:"We'd better sort that out one-on-one.", ipa:"FEER-au-gen-ge-shpreekh", coll:"ein Vieraugengespräch führen", tip:"Wörtlich „unter vier Augen“ = zu zweit.", topic:"Workplace", level:"C1" },
  { id:"fc5018", de:"Beschluss", article:"der", plural:"die Beschlüsse", en:"resolution, formal decision", vi:"nghị quyết", ex:"Der Beschluss wurde im Protokoll festgehalten.", exEn:"The decision was recorded in the minutes.", ipa:"be-SHLUS", coll:"einen Beschluss fassen", tip:"Formeller als „Entscheidung“; Umlaut im Plural.", topic:"Workplace", level:"C1" },
  { id:"fc5019", de:"Absprache", article:"die", plural:"die Absprachen", en:"arrangement, agreement", vi:"thỏa thuận", ex:"Nach Absprache mit dem Kunden verschieben wir den Termin.", exEn:"By arrangement with the client we're moving the date.", ipa:"AP-shpraa-khe", coll:"nach Absprache mit …", tip:"Als feste Wendung ohne Artikel: „nach Absprache“.", topic:"Workplace", level:"B2" },
  { id:"fc5020", de:"offener Punkt", article:"der", plural:"die offenen Punkte", en:"open item", vi:"vấn đề còn tồn", ex:"Die offenen Punkte klären wir bis Freitag.", exEn:"We'll settle the open items by Friday.", ipa:"OF-fe-ner PUNKT", coll:"offene Punkte klären", tip:"Eigener Abschnitt in jedem Protokoll.", topic:"Workplace", level:"B2" },
  { id:"fc5021", de:"vertagen", article:"—", plural:"—", en:"to postpone to a later session", vi:"hoãn sang buổi sau", ex:"Die Frage der Kundeninformation wurde vertagt.", exEn:"The question of informing customers was postponed.", ipa:"fer-TAA-gen", coll:"eine Entscheidung vertagen", tip:"Wörtlich „auf einen anderen Tag legen“ — bleibt offen, nicht erledigt.", topic:"Workplace", level:"C1" },
  { id:"fc5022", de:"festhalten", article:"—", plural:"—", en:"to put on record", vi:"ghi nhận", ex:"Dann halten wir das so fest.", exEn:"Then let's record it that way.", ipa:"FEST-hal-ten", coll:"etwas im Protokoll festhalten", tip:"Trennbar. Nach diesem Satz schreibst du mit.", topic:"Workplace", level:"B2" },
  { id:"fc5023", de:"Schulung", article:"die", plural:"die Schulungen", en:"training session", vi:"buổi đào tạo", ex:"Am Donnerstag ist eine Schulung zur neuen Pipeline.", exEn:"There's training on the new pipeline on Thursday.", ipa:"SHUU-lung", coll:"eine Schulung besuchen / anbieten", tip:"-ung → die. Person: der/die Schulungsleiter/in.", topic:"Workplace", level:"B2" },

  /* ---- Phase 4 · Speaking (Redemittel) ---- */
  { id:"fc5024", de:"einhaken", article:"—", plural:"—", en:"to jump in, to cut in", vi:"xen vào", ex:"Darf ich kurz einhaken?", exEn:"May I jump in briefly?", ipa:"AYN-haa-ken", coll:"kurz einhaken", tip:"Trennbar. Immer erst das Signal, dann der Beitrag.", topic:"Speaking", level:"B2" },
  { id:"fc5025", de:"Gliederung", article:"die", plural:"die Gliederungen", en:"outline, structure", vi:"bố cục", ex:"Ich habe den Vortrag in drei Teile gegliedert.", exEn:"I've structured the talk in three parts.", ipa:"GLEE-de-rung", coll:"einen Vortrag gliedern", tip:"Hörst du „gegliedert“, schreib drei Spiegelstriche auf.", topic:"Speaking", level:"B2" },
  { id:"fc5026", de:"Übergang", article:"der", plural:"die Übergänge", en:"transition", vi:"chuyển ý", ex:"Damit komme ich zum nächsten Punkt.", exEn:"With that I come to the next point.", ipa:"ÜÜ-ber-gang", coll:"einen Übergang setzen", tip:"Umlaut im Plural. Der Standardübergang im Vortrag.", topic:"Speaking", level:"B2" },
  { id:"fc5027", de:"Ich-Botschaft", article:"die", plural:"die Ich-Botschaften", en:"I-statement", vi:"thông điệp „tôi“", ex:"Mir ist aufgefallen, dass der PR sehr groß war.", exEn:"I noticed the PR was very large.", ipa:"IKH-bot-shaft", coll:"Feedback in Ich-Botschaften geben", tip:"Situation → Wirkung → Wunsch, ohne „du“.", topic:"Speaking", level:"B2" },
  { id:"fc5028", de:"den Rahmen sprengen", article:"—", plural:"—", en:"to go beyond the scope", vi:"vượt khuôn khổ", ex:"Das würde den Rahmen sprengen — klären wir das offline?", exEn:"That would go beyond scope — shall we take it offline?", ipa:"deen RAA-men SHPREN-gen", coll:"den Rahmen sprengen", tip:"Höfliche Art, eine Frage zu vertagen, ohne sie abzuwerten.", topic:"Speaking", level:"C1" },
  { id:"fc5029", de:"Wortmeldung", article:"die", plural:"die Wortmeldungen", en:"request to speak", vi:"xin phát biểu", ex:"Gibt es noch Wortmeldungen zu diesem Punkt?", exEn:"Any further requests to speak on this point?", ipa:"VORT-mel-dung", coll:"eine Wortmeldung haben", tip:"Moderationswort — auch in Betriebsversammlungen.", topic:"Speaking", level:"C1" },
  { id:"fc5030", de:"sich melden", article:"—", plural:"—", en:"to get back to someone", vi:"phản hồi lại", ex:"Das kann ich jetzt nicht sicher sagen — ich melde mich dazu.", exEn:"I can't say for sure right now — I'll get back to you.", ipa:"zikh MEL-den", coll:"sich zu etwas melden", tip:"Besser als raten: Verlässlichkeit zählt mehr als Vollständigkeit.", topic:"Speaking", level:"B2" },

  /* ---- Phase 4 · Listening & Reading (Firmentexte) ---- */
  { id:"fc5031", de:"Wartungsfenster", article:"das", plural:"die Wartungsfenster", en:"maintenance window", vi:"khung giờ bảo trì", ex:"Das Wartungsfenster ist am Samstag ab sechs Uhr.", exEn:"The maintenance window is Saturday from six.", ipa:"VAR-tungs-fens-ter", coll:"ein Wartungsfenster anmelden", tip:"Plural = Singular. Kopf: das Fenster.", topic:"DevOps", level:"B2" },
  { id:"fc5032", de:"Ansprechpartner", article:"der", plural:"die Ansprechpartner", en:"contact person", vi:"người phụ trách", ex:"Bei Fragen ist das Plattform-Team euer Ansprechpartner.", exEn:"For questions the platform team is your contact.", ipa:"AN-shprekh-part-ner", coll:"Ansprechpartner sein für …", tip:"Steht am Ende fast jeder Rundmail und Wiki-Seite.", topic:"Workplace", level:"B2" },
  { id:"fc5033", de:"Geltungsbereich", article:"der", plural:"die Geltungsbereiche", en:"scope of application", vi:"phạm vi áp dụng", ex:"§1 regelt den Geltungsbereich der Richtlinie.", exEn:"§1 defines the policy's scope.", ipa:"GEL-tungs-be-rykh", coll:"in den Geltungsbereich fallen", tip:"Beantwortet die einzige Frage, die dich zuerst interessiert: gilt das für mich?", topic:"Workplace", level:"C1" },
  { id:"fc5034", de:"Nichteinhaltung", article:"die", plural:"—", en:"non-compliance, failure to meet", vi:"việc không tuân thủ", ex:"Bei Nichteinhaltung der Frist erlischt die Übergangsregelung.", exEn:"If the deadline is missed, the transitional arrangement lapses.", ipa:"NIKHT-ayn-hal-tung", coll:"bei Nichteinhaltung + Gen.", tip:"Vorsilbe Nicht- verneint das ganze Nomen: auch Nichtverfügbarkeit.", topic:"Workplace", level:"C1" },
  { id:"fc5035", de:"erlöschen", article:"—", plural:"—", en:"to lapse, to expire", vi:"hết hiệu lực", ex:"Die Genehmigung erlischt am 31. Dezember.", exEn:"The approval expires on 31 December.", ipa:"er-LÖ-shen", coll:"ein Anspruch erlischt", tip:"Endet von selbst, ohne dass jemand etwas tut.", topic:"Workplace", level:"C1" },
  { id:"fc5036", de:"einreichen", article:"—", plural:"—", en:"to submit", vi:"nộp", ex:"Anträge sind bis spätestens 15.09. einzureichen.", exEn:"Applications must be submitted by 15 September at the latest.", ipa:"AYN-ry-khen", coll:"einen Antrag einreichen", tip:"„sind einzureichen“ = sein + zu + Infinitiv = Pflicht.", topic:"Workplace", level:"B2" },
  { id:"fc5037", de:"zulässig", article:"—", plural:"—", en:"permissible", vi:"được phép", ex:"Abweichungen sind nur mit Genehmigung zulässig.", exEn:"Deviations are permissible only with approval.", ipa:"TSUU-le-sikh", coll:"zulässig sein", tip:"Gegenteile: unzulässig, untersagt, nicht gestattet.", topic:"Workplace", level:"C1" },
  { id:"fc5038", de:"im Zuge (+ Gen.)", article:"—", plural:"—", en:"in the course of", vi:"trong quá trình", ex:"Im Zuge der Migration werden alte Seiten archiviert.", exEn:"In the course of the migration old pages are archived.", ipa:"im TSUU-ge", coll:"im Zuge der Umstellung", tip:"Feste Präposition der Verwaltungssprache, immer mit Genitiv.", topic:"Workplace", level:"C1" },
  { id:"fc5039", de:"Übergangsregelung", article:"die", plural:"die Übergangsregelungen", en:"transitional arrangement", vi:"quy định chuyển tiếp", ex:"Die Übergangsregelung gilt noch bis Ende September.", exEn:"The transitional arrangement runs until the end of September.", ipa:"ÜÜ-ber-gangs-ree-ge-lung", coll:"eine Übergangsregelung gilt / erlischt", tip:"-ung → die. Häufig zusammen mit erlöschen.", topic:"Workplace", level:"C1" },
  { id:"fc5040", de:"untersagt", article:"—", plural:"—", en:"prohibited", vi:"bị cấm", ex:"Die Nutzung privater Geräte ist untersagt.", exEn:"Using private devices is prohibited.", ipa:"un-ter-ZAAKT", coll:"etwas ist untersagt", tip:"Härteste Verbotsform in Richtlinien; daneben „nicht gestattet“.", topic:"Workplace", level:"B2" },
  { id:"fc5041", de:"Füllwort", article:"das", plural:"die Füllwörter", en:"filler word", vi:"từ đệm", ex:"„Also, im Prinzip, genau“ sind Füllwörter.", exEn:"'Also, im Prinzip, genau' are filler words.", ipa:"FÜL-vort", coll:"Füllwörter überhören", tip:"Tragen Rhythmus, keine Information — überhören lernen.", topic:"Speaking", level:"B2" },
  { id:"fc5042", de:"im Anschluss", article:"—", plural:"—", en:"afterwards, following that", vi:"ngay sau đó", ex:"Gern beantworte ich Ihre Fragen im Anschluss.", exEn:"I'm happy to take your questions afterwards.", ipa:"im AN-shlus", coll:"im Anschluss an + Akk.", tip:"Standardformel am Ende von Vorträgen und Einladungen.", topic:"Speaking", level:"B2" },

  /* ---- Phase 4 · Writing & Templates ---- */
  { id:"fc5043", de:"Grußformel", article:"die", plural:"die Grußformeln", en:"sign-off", vi:"lời chào cuối thư", ex:"Die Grußformel muss zur Anrede passen.", exEn:"The sign-off has to match the salutation.", ipa:"GRUUS-for-mel", coll:"die passende Grußformel wählen", tip:"Sehr geehrte … → Mit freundlichen Grüßen; Hallo … → Viele Grüße.", topic:"Writing", level:"B2" },
  { id:"fc5044", de:"nachfassen", article:"—", plural:"—", en:"to follow up", vi:"nhắc lại nhẹ nhàng", ex:"Ich wollte kurz nachfassen wegen der Freigabe.", exEn:"I just wanted to follow up about the approval.", ipa:"NAAKH-fas-sen", coll:"bei jemandem nachfassen", tip:"Stufe 1 der Eskalationsleiter — freundlich, ohne Vorwurf.", topic:"Writing", level:"B2" },
  { id:"fc5045", de:"zur Verfügung stehen", article:"—", plural:"—", en:"to be available (for)", vi:"sẵn sàng hỗ trợ", ex:"Für Rückfragen stehe ich gern zur Verfügung.", exEn:"I'm happy to answer any questions.", ipa:"tsur fer-FÜÜ-gung SHTEE-en", coll:"für Rückfragen zur Verfügung stehen", tip:"Der Standard-Schlusssatz der formellen E-Mail.", topic:"Writing", level:"B2" },
  { id:"fc5046", de:"zukommen lassen", article:"—", plural:"—", en:"to send (formal)", vi:"gửi tới", ex:"Könnten Sie mir das Protokoll zukommen lassen?", exEn:"Could you send me the minutes?", ipa:"TSUU-kom-men LAS-sen", coll:"jemandem etwas zukommen lassen", tip:"Nur im Sie-Register; im Du klingt es gestelzt — dort „schicken“.", topic:"Writing", level:"C1" },
  { id:"fc5047", de:"Abwesenheitsnotiz", article:"die", plural:"die Abwesenheitsnotizen", en:"out-of-office reply", vi:"thông báo vắng mặt", ex:"Ich habe die Abwesenheitsnotiz für den Urlaub eingerichtet.", exEn:"I've set up the out-of-office reply for my holiday.", ipa:"AP-vee-zen-hyts-no-teets", coll:"eine Abwesenheitsnotiz einrichten", tip:"Immer „bis einschließlich“ schreiben — sonst bleibt der letzte Tag unklar.", topic:"Writing", level:"B2" },
  { id:"fc5048", de:"Vertretung", article:"die", plural:"die Vertretungen", en:"cover, stand-in", vi:"người thay thế", ex:"In dieser Zeit vertritt mich Anna Weber.", exEn:"Anna Weber is covering for me during that time.", ipa:"fer-TREE-tung", coll:"die Vertretung übernehmen", tip:"Verb: jemanden vertreten. -ung → die.", topic:"Workplace", level:"B2" },
  { id:"fc5049", de:"unaufgefordert", article:"—", plural:"—", en:"unprompted, of one's own accord", vi:"chủ động", ex:"Ich melde mich unaufgefordert, sobald es Neues gibt.", exEn:"I'll get in touch of my own accord as soon as there's news.", ipa:"UN-auf-ge-for-dert", coll:"sich unaufgefordert melden", tip:"Ein Zuverlässigkeitsversprechen — im deutschen Berufsdeutsch stark.", topic:"Writing", level:"C1" },
  { id:"fc5050", de:"einschließlich", article:"—", plural:"—", en:"inclusive of, up to and including", vi:"bao gồm cả", ex:"Ich bin bis einschließlich 12.09. nicht erreichbar.", exEn:"I'm unavailable up to and including 12 September.", ipa:"AYN-shlees-likh", coll:"bis einschließlich + Datum", tip:"Ohne dieses Wort ist unklar, ob der letzte Tag dazugehört.", topic:"Writing", level:"B2" },
  { id:"fc5051", de:"Abnahme", article:"die", plural:"die Abnahmen", en:"acceptance, sign-off", vi:"nghiệm thu", ex:"Alle Kriterien sind erfüllt — ich bitte um Abnahme.", exEn:"All criteria are met — requesting sign-off.", ipa:"AP-naa-me", coll:"um Abnahme bitten", tip:"Ohne diesen Satz bleibt ein fertiges Ticket liegen.", topic:"Agile", level:"B2" },
  { id:"fc5052", de:"Schweregrad", article:"der", plural:"die Schweregrade", en:"severity", vi:"mức nghiêm trọng", ex:"Schweregrad hoch — die Anmeldung ist blockiert.", exEn:"Severity high — login is blocked.", ipa:"SHVEE-re-graat", coll:"den Schweregrad einstufen", tip:"Immer mit Begründung, sonst wird über Adjektive diskutiert.", topic:"DevOps", level:"B2" },
  { id:"fc5053", de:"Abgrenzung", article:"die", plural:"die Abgrenzungen", en:"scoping, delimitation", vi:"giới hạn phạm vi", ex:"Zur Abgrenzung: Der PDF-Export ist nicht enthalten.", exEn:"For scoping: the PDF export is not included.", ipa:"AP-gren-tsung", coll:"eine Abgrenzung vornehmen", tip:"Der Abschnitt „Nicht enthalten“ spart die meisten Abnahmediskussionen.", topic:"Agile", level:"C1" },
  { id:"fc5054", de:"Änderungswunsch", article:"der", plural:"die Änderungswünsche", en:"requested change", vi:"yêu cầu chỉnh sửa", ex:"Änderungswunsch: Der Fehlerfall sollte protokolliert werden.", exEn:"Requested change: the error case should be logged.", ipa:"EN-de-rungs-vunsh", coll:"einen Änderungswunsch äußern", tip:"Review-Stufe 3: sollte vor dem Merge geändert werden.", topic:"Code Review", level:"B2" },
  { id:"fc5055", de:"Kleinigkeit", article:"die", plural:"die Kleinigkeiten", en:"nit, minor point", vi:"điểm nhỏ", ex:"Kleinigkeit: Der Name „liste2“ sagt wenig.", exEn:"Nit: the name 'liste2' says little.", ipa:"KLY-nikh-kyt", coll:"nur eine Kleinigkeit", tip:"Review-Stufe 2 — blockiert den Merge ausdrücklich nicht.", topic:"Code Review", level:"B2" },
  { id:"fc5056", de:"einarbeiten", article:"—", plural:"—", en:"to incorporate (comments)", vi:"tiếp thu, chỉnh theo", ex:"Alle Punkte sind eingearbeitet — bitte noch einmal drüberschauen.", exEn:"All points are incorporated — please take another look.", ipa:"AYN-ar-by-ten", coll:"Kommentare einarbeiten", tip:"Trennbar. Auch: jemanden einarbeiten = onboarden.", topic:"Code Review", level:"B2" },
  { id:"fc5057", de:"gegenprüfen", article:"—", plural:"—", en:"to double-check", vi:"kiểm tra chéo", ex:"Die Sortierung würde ich gern gegenprüfen lassen.", exEn:"I'd like the sorting double-checked.", ipa:"GEE-gen-prüü-fen", coll:"etwas gegenprüfen lassen", tip:"Eine eigene Unsicherheit zu benennen, gilt als souverän.", topic:"Code Review", level:"C1" },
  { id:"fc5058", de:"nachvollziehbar", article:"—", plural:"—", en:"comprehensible, traceable", vi:"dễ hiểu, lần lại được", ex:"Ich habe es kommentiert, damit die Entscheidung nachvollziehbar bleibt.", exEn:"I commented it so the decision stays traceable.", ipa:"naakh-fol-TSEE-baar", coll:"nachvollziehbar dokumentieren", tip:"Verb: nachvollziehen = gedanklich mitgehen.", topic:"Writing", level:"C1" },
  { id:"fc5059", de:"Auswirkung", article:"die", plural:"die Auswirkungen", en:"impact", vi:"tác động", ex:"Auswirkung: etwa 1 200 fehlgeschlagene Zahlungsversuche.", exEn:"Impact: roughly 1,200 failed payment attempts.", ipa:"AUS-vir-kung", coll:"Auswirkungen auf + Akk.", tip:"Im Incident-Report gehören Zahlen hierher, keine Adjektive.", topic:"DevOps", level:"B2" },
  { id:"fc5060", de:"Betriebshandbuch", article:"das", plural:"die Betriebshandbücher", en:"runbook, operations manual", vi:"sổ tay vận hành", ex:"Das Rollback steht im Betriebshandbuch.", exEn:"The rollback is in the runbook.", ipa:"be-TREEPS-hant-buukh", coll:"im Betriebshandbuch nachschlagen", tip:"Umlaut im Plural. Kopf: das Buch.", topic:"DevOps", level:"C1" },
  { id:"fc5061", de:"eingrenzen", article:"—", plural:"—", en:"to narrow down", vi:"khoanh vùng", ex:"Die Ursache ist eingegrenzt: nur Passwörter mit Sonderzeichen.", exEn:"The cause is narrowed down: only passwords with special characters.", ipa:"AYN-gren-tsen", coll:"eine Ursache eingrenzen", tip:"Trennbar. Der Standardsatz im Statuskommentar.", topic:"Debugging", level:"B2" },
  { id:"fc5062", de:"Begrenzung", article:"die", plural:"die Begrenzungen", en:"limit", vi:"giới hạn", ex:"Hier fehlt eine Begrenzung — die Abfrage lädt die ganze Historie.", exEn:"There's no limit here — the query loads the whole history.", ipa:"be-GREN-tsung", coll:"eine Begrenzung setzen", tip:"-ung → die. Verb: begrenzen.", topic:"Database", level:"B2" }
]);
