/*! flashcards-18.js — Goethe B1, der Meilenstein in Woche 8 (content/exams/goethe-b1.md).
 * 15 Zeilen in der Vokabel-Checkliste, 6 davon bereits verkartet (Nachweis, Modellsatz,
 * Zuordnung, Durchsage, erstatten, ablegen) — bleiben 9 neue Karten.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  { id:"fc9901", de:"Niederlassungserlaubnis", article:"die", plural:"die Niederlassungserlaubnisse", en:"permanent residence permit", vi:"giấy định cư vĩnh viễn", ex:"Für die Niederlassungserlaubnis reicht in der Regel ein B1-Nachweis.", exEn:"For the permanent residence permit a B1 certificate is usually enough.", ipa:"NII-der-la-sungs-er-laup-nis", coll:"die Niederlassungserlaubnis beantragen", tip:"Kopf: die Erlaubnis → die, Plural mit Doppel-s. Der häufigste echte Grund, Goethe B1 abzulegen — ein Behördengrund, kein Sprachgrund.", topic:"Exam", level:"C1" },
  { id:"fc9902", de:"Einbürgerung", article:"die", plural:"die Einbürgerungen", en:"naturalisation", vi:"nhập quốc tịch", ex:"Bei der Einbürgerung wird ein B1-Nachweis verlangt, mit wenigen Ausnahmen.", exEn:"Naturalisation requires a B1 certificate, with few exceptions.", ipa:"AYN-bür-ge-rung", coll:"die Einbürgerung beantragen", tip:"-ung → die. Von *der Bürger*. Welcher Nachweis in deinem Fall zählt, sagt dir die Ausländerbehörde — die Regeln unterscheiden sich je nach Bundesland.", topic:"Exam", level:"C1" },
  { id:"fc9903", de:"Anmeldefrist", article:"die", plural:"die Anmeldefristen", en:"registration deadline", vi:"hạn đăng ký", ex:"Die Anmeldefrist liegt meist Wochen vor dem Prüfungstermin — trag beides ein.", exEn:"The registration deadline is usually weeks before the exam date — note both.", ipa:"AN-mel-de-frist", coll:"die Anmeldefrist einhalten", tip:"Kopf: die Frist → die. Der Termin nützt nichts ohne die Frist: wer die verpasst, wartet auf den nächsten Durchgang.", topic:"Exam", level:"B2" },
  { id:"fc9904", de:"Forumsbeitrag", article:"der", plural:"die Forumsbeiträge", en:"forum post", vi:"bài đăng diễn đàn", ex:"Der Forumsbeitrag verlangt eine Meinung mit Begründung, nicht nur eine Erzählung.", exEn:"The forum post calls for an opinion with a reason, not just a story.", ipa:"FOO-rums-bay-traak", coll:"einen Forumsbeitrag schreiben", tip:"Kopf: der Beitrag → der, Umlaut im Plural. Im Schreiben-Teil das neutrale Register zwischen privater Nachricht und förmlicher Mitteilung.", topic:"Exam", level:"B2" },
  { id:"fc9905", de:"Mitteilung", article:"die", plural:"die Mitteilungen", en:"notification, message", vi:"thông báo", ex:"Die halbformelle Mitteilung braucht Anrede, Grund, Bitte und Gruß — mehr nicht.", exEn:"The semi-formal message needs a salutation, a reason, a request and a sign-off — no more.", ipa:"MIT-tay-lung", coll:"eine Mitteilung verfassen", tip:"-ung → die. Von *mitteilen*. Neutraler als *die Beschwerde* und kürzer als *der Brief*.", topic:"Exam", level:"B2" },
  { id:"fc9906", de:"Generalprobe", article:"die", plural:"die Generalproben", en:"dress rehearsal", vi:"tổng duyệt", ex:"Manche legen B1 als Generalprobe für telc B2 ab — das kostet Zeit und Gebühr.", exEn:"Some sit B1 as a dress rehearsal for telc B2 — that costs time and a fee.", ipa:"ge-ne-RAAL-proo-be", coll:"als Generalprobe ablegen", tip:"Kopf: die Probe → die. Aus dem Theater. Ein legitimer, aber teurer Grund — dieselbe Zeit in Phase 2 bringt dich näher an B2.", topic:"Exam", level:"C1" },
  { id:"fc9907", de:"Standortbestimmung", article:"die", plural:"die Standortbestimmungen", en:"assessment of where you stand", vi:"xác định trình độ hiện tại", ex:"Der Phase-1-Test ist eine Standortbestimmung, keine Prüfungsvorbereitung.", exEn:"The Phase 1 test is an assessment of where you stand, not exam preparation.", ipa:"SHTANT-ort-be-shti-mung", coll:"eine Standortbestimmung machen", tip:"-ung → die. Aus der Navigation: wo bin ich gerade. Sachlicher als *der Test* — es geht um Messen, nicht um Bestehen.", topic:"Exam", level:"C1" },
  { id:"fc9908", de:"Formsache", article:"die", plural:"die Formsachen", en:"formality", vi:"thủ tục hình thức", ex:"Wer im Phase-1-Test sicher über siebzig liegt, für den ist B1 eine Formsache.", exEn:"If you're safely above seventy in the Phase 1 test, B1 is a formality for you.", ipa:"FORM-za-khe", coll:"nur noch eine Formsache", tip:"Kopf: die Sache → die. Heißt: das Ergebnis steht schon fest, es fehlt nur der Vorgang.", topic:"Exam", level:"C1" },
  { id:"fc9909", de:"eingehen (auf)", article:"—", plural:"—", en:"to engage with, to respond to", vi:"đáp lại, tiếp lời", ex:"Im Sprechen-Teil wird bewertet, ob du auf deinen Partner eingehst.", exEn:"In the speaking part you're marked on whether you engage with your partner.", ipa:"AYN-gee-en auf", coll:"auf jemanden eingehen", tip:"Trennbar und stark, mit *sein*: gehe … ein, ging … ein, eingegangen. *auf* + Akkusativ. Ein eigenes Bewertungskriterium — den anderen niederzureden senkt deine eigene Note.", topic:"Exam", level:"C1" },
]);
