/*! flashcards-4.js — Phase 1 workbook deck (Đợt 1). Merges onto window.FLASHCARDS.
 * Sourced from the Vokabel-Checkliste of the six phase-1 *-uebungen modules.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- Grammar · Übungsteil ---- */
  { id:"fc1001", de:"Übung", article:"die", plural:"die Übungen", en:"exercise", vi:"bài tập", ex:"Diese Übung trainiert die Wortstellung.", exEn:"This exercise drills word order.", ipa:"ÜÜ-bung", coll:"eine Übung machen/lösen", tip:"-ung → immer die. Verb: üben.", topic:"Übungen", level:"B1" },
  { id:"fc1002", de:"Lösung", article:"die", plural:"die Lösungen", en:"solution, answer", vi:"đáp án; giải pháp", ex:"Die Lösungen stehen am Ende des Kapitels.", exEn:"The answers are at the end of the chapter.", ipa:"LÖÖ-zung", coll:"eine Lösung finden/suchen", tip:"Doppeldeutig: Antwort UND Lösung eines Problems.", topic:"Übungen", level:"B1" },
  { id:"fc1003", de:"Ursache", article:"die", plural:"die Ursachen", en:"cause, root cause", vi:"nguyên nhân", ex:"Ich habe den Log gelesen und die Ursache gefunden.", exEn:"I read the log and found the cause.", ipa:"UUR-za-khe", coll:"die Ursache finden/beheben", tip:"Root cause = die eigentliche Ursache.", topic:"Software Development", level:"B1" },
  { id:"fc1004", de:"Zugang", article:"der", plural:"die Zugänge", en:"access (to a system)", vi:"quyền truy cập", ex:"Darf ich den Prod-Zugang bekommen?", exEn:"May I get production access?", ipa:"TSUU-gang", coll:"Zugang beantragen/bekommen", tip:"Zugang = das Recht; Zugriff = der konkrete Vorgang.", topic:"Security", level:"B1" },
  { id:"fc1005", de:"übernehmen", article:"—", plural:"—", en:"to take over (a task)", vi:"nhận (việc)", ex:"Das Ticket übernehme ich.", exEn:"I'll take that ticket over.", ipa:"üü-ber-NEE-men", coll:"eine Aufgabe/ein Ticket übernehmen", tip:"Untrennbar: ich übernehme, nicht *ich nehme über.", topic:"Agile", level:"B1" },
  { id:"fc1006", de:"fehlen", article:"—", plural:"—", en:"to be missing", vi:"thiếu", ex:"Eine Umgebungsvariable fehlt in der Konfiguration.", exEn:"An environment variable is missing from the config.", ipa:"FEE-len", coll:"es fehlt an + Dativ", tip:"Das Fehlende ist Subjekt: „mir fehlt der Zugang“.", topic:"Software Development", level:"B1" },
  { id:"fc1007", de:"beheben", article:"—", plural:"—", en:"to fix (an error)", vi:"khắc phục", ex:"Ich habe den Login-Bug behoben.", exEn:"I fixed the login bug.", ipa:"be-HEE-ben", coll:"einen Fehler/eine Störung beheben", tip:"Partizip II ohne ge-: behoben.", topic:"Software Development", level:"B1" },

  /* ---- Vocabulary · Übungsteil ---- */
  { id:"fc1008", de:"Quellcode", article:"der", plural:"die Quellcodes", en:"source code", vi:"mã nguồn", ex:"Der Quellcode liegt im internen Repository.", exEn:"The source code is in the internal repository.", ipa:"KVEL-koht", coll:"den Quellcode einsehen/ändern", tip:"Quelle + Code → der (von Code).", topic:"Software Development", level:"B1" },
  { id:"fc1009", de:"Fehlermeldung", article:"die", plural:"die Fehlermeldungen", en:"error message", vi:"thông báo lỗi", ex:"Die Fehlermeldung steht im Log.", exEn:"The error message is in the log.", ipa:"FEE-ler-mel-dung", coll:"eine Fehlermeldung bekommen/auswerten", tip:"Fehler + Meldung → die (von Meldung).", topic:"Software Development", level:"B1" },
  { id:"fc1010", de:"Sicherheitslücke", article:"die", plural:"die Sicherheitslücken", en:"security hole, vulnerability", vi:"lỗ hổng bảo mật", ex:"Wir haben eine Sicherheitslücke geschlossen.", exEn:"We closed a security hole.", ipa:"ZIKH-er-hyts-lü-ke", coll:"eine Sicherheitslücke schließen", tip:"Lücke = gap. -heit → die, aber hier entscheidet Lücke.", topic:"Security", level:"B2" },
  { id:"fc1011", de:"Datenschutz", article:"der", plural:"—", en:"data protection, privacy", vi:"bảo vệ dữ liệu", ex:"Der Datenschutz ist in Deutschland sehr wichtig.", exEn:"Data protection is very important in Germany.", ipa:"DAA-ten-shuts", coll:"den Datenschutz einhalten", tip:"DSGVO = GDPR. Kein Plural.", topic:"Security", level:"B1" },
  { id:"fc1012", de:"Abfrage", article:"die", plural:"die Abfragen", en:"query", vi:"truy vấn", ex:"Diese Abfrage ist zu langsam.", exEn:"This query is too slow.", ipa:"AP-fraa-ge", coll:"eine Abfrage optimieren/ausführen", tip:"Verb: abfragen (trennbar).", topic:"Database", level:"B1" },
  { id:"fc1013", de:"Verbindung", article:"die", plural:"die Verbindungen", en:"connection", vi:"kết nối", ex:"Die Anwendung konnte keine Verbindung zur Datenbank herstellen.", exEn:"The application could not connect to the database.", ipa:"fer-BIN-dung", coll:"eine Verbindung herstellen/aufbauen", tip:"-ung → die. „Verbindung zu + Dativ“.", topic:"Networking", level:"B1" },
  { id:"fc1014", de:"Bereitstellung", article:"die", plural:"die Bereitstellungen", en:"deployment, provisioning", vi:"triển khai", ex:"Die Bereitstellung dauert etwa zwei Stunden.", exEn:"The deployment takes about two hours.", ipa:"be-RYT-shtel-lung", coll:"die Bereitstellung planen", tip:"Formeller als „das Deployment“.", topic:"DevOps", level:"B2" },

  /* ---- Speaking · Übungsteil ---- */
  { id:"fc1015", de:"Aussprache", article:"die", plural:"die Aussprachen", en:"pronunciation", vi:"phát âm", ex:"Meine Aussprache wird durch Shadowing besser.", exEn:"My pronunciation improves through shadowing.", ipa:"AUS-shpraa-khe", coll:"die Aussprache üben/verbessern", tip:"aus + Sprache → die.", topic:"Speaking", level:"B1" },
  { id:"fc1016", de:"Betonung", article:"die", plural:"die Betonungen", en:"stress, emphasis", vi:"trọng âm", ex:"Die Betonung liegt auf der ersten Silbe.", exEn:"The stress is on the first syllable.", ipa:"be-TOO-nung", coll:"die Betonung liegt auf + Dativ", tip:"-ung → die. Verb: betonen.", topic:"Speaking", level:"B1" },
  { id:"fc1017", de:"Redemittel", article:"das", plural:"die Redemittel", en:"set phrase, useful expression", vi:"mẫu câu", ex:"Diese Redemittel brauchst du in jedem Meeting.", exEn:"You need these phrases in every meeting.", ipa:"REE-de-mit-tel", coll:"Redemittel lernen/anwenden", tip:"Plural = Singular. Prüfungsvokabel!", topic:"Speaking", level:"B1" },
  { id:"fc1018", de:"zuständig", article:"—", plural:"—", en:"responsible (for)", vi:"phụ trách", ex:"Ich bin für die Schnittstellen zuständig.", exEn:"I'm responsible for the interfaces.", ipa:"TSUU-shten-dikh", coll:"zuständig für + Akkusativ", tip:"Signatur merken: zuständig FÜR + Akk.", topic:"Workplace", level:"B1" },
  { id:"fc1019", de:"ansprechen", article:"—", plural:"—", en:"to raise (a topic)", vi:"nêu ra", ex:"Ich möchte kurz etwas ansprechen.", exEn:"I'd like to raise something briefly.", ipa:"AN-shpre-khen", coll:"ein Thema/Problem ansprechen", tip:"Trennbar: ich spreche das an.", topic:"Workplace", level:"B2" },
  { id:"fc1020", de:"formulieren", article:"—", plural:"—", en:"to phrase, to word", vi:"diễn đạt", ex:"Kannst du das bitte anders formulieren?", exEn:"Can you phrase that differently?", ipa:"for-mu-LEE-ren", coll:"einen Satz neu formulieren", tip:"-ieren → Partizip ohne ge-: formuliert.", topic:"Speaking", level:"B1" },

  /* ---- Listening · Übungsteil ---- */
  { id:"fc1021", de:"Störung", article:"die", plural:"die Störungen", en:"outage, disruption", vi:"sự cố", ex:"Es gab gestern Abend eine Störung im Zahlungs-Service.", exEn:"There was an outage in the payment service last night.", ipa:"SHTÖÖ-rung", coll:"eine Störung melden/beheben", tip:"-ung → die. Verb: stören.", topic:"DevOps", level:"B1" },
  { id:"fc1022", de:"Bericht", article:"der", plural:"die Berichte", en:"report", vi:"báo cáo", ex:"Der ausführliche Bericht kommt bis Donnerstag.", exEn:"The detailed report is coming by Thursday.", ipa:"be-RIKHT", coll:"einen Bericht schreiben/schicken", tip:"Post-mortem = der Nachbericht / die Manöverkritik.", topic:"Workplace", level:"B1" },
  { id:"fc1023", de:"Fehlerbehandlung", article:"die", plural:"die Fehlerbehandlungen", en:"error handling", vi:"xử lý lỗi", ex:"Die Fehlerbehandlung in der zweiten Methode ist unklar.", exEn:"The error handling in the second method is unclear.", ipa:"FEE-ler-be-han-dlung", coll:"die Fehlerbehandlung implementieren", tip:"try/catch = der Try-Catch-Block.", topic:"Software Development", level:"B2" },
  { id:"fc1024", de:"Fachkraft", article:"die", plural:"die Fachkräfte", en:"skilled worker, specialist", vi:"nhân lực có chuyên môn", ex:"In Deutschland fehlen viele IT-Fachkräfte.", exEn:"Germany is short of many IT specialists.", ipa:"FAKH-kraft", coll:"Fachkräfte suchen/einstellen", tip:"Umlaut im Plural: Kraft → Kräfte. Fachkräftemangel = skills shortage.", topic:"Workplace", level:"B2" },
  { id:"fc1025", de:"Zusammenfassung", article:"die", plural:"die Zusammenfassungen", en:"summary", vi:"bản tóm tắt", ex:"Schreib bitte eine kurze Zusammenfassung für das Team.", exEn:"Please write a short summary for the team.", ipa:"tsu-ZAM-men-fas-sung", coll:"eine Zusammenfassung schreiben", tip:"Verb zusammenfassen = to summarize — NICHT to merge!", topic:"Workplace", level:"B1" },
  { id:"fc1026", de:"Diktat", article:"das", plural:"die Diktate", en:"dictation", vi:"bài chính tả", ex:"Ein kurzes Diktat pro Woche verbessert dein Hörverstehen.", exEn:"One short dictation a week improves your listening.", ipa:"dik-TAAT", coll:"ein Diktat schreiben", tip:"Betonung hinten: dik-TAAT.", topic:"Übungen", level:"B1" },
  { id:"fc1027", de:"hinterlassen", article:"—", plural:"—", en:"to leave (a comment, a message)", vi:"để lại", ex:"Ich habe zwei Kommentare im PR hinterlassen.", exEn:"I left two comments on the PR.", ipa:"hin-ter-LAS-sen", coll:"einen Kommentar/eine Nachricht hinterlassen", tip:"Untrennbar, Partizip ohne ge-: hinterlassen.", topic:"Workplace", level:"B2" },

  /* ---- Reading · Übungsteil ---- */
  { id:"fc1028", de:"Quereinsteiger", article:"der", plural:"die Quereinsteiger", en:"career changer", vi:"người chuyển ngành", ex:"Viele Firmen stellen auch Quereinsteiger ein.", exEn:"Many companies also hire career changers.", ipa:"KVEER-ayn-shty-ger", coll:"als Quereinsteiger anfangen", tip:"quer (sideways) + Einsteiger (entrant). Plural = Singular.", topic:"Career", level:"B2" },
  { id:"fc1029", de:"Bereitschaftsdienst", article:"der", plural:"die Bereitschaftsdienste", en:"on-call duty", vi:"trực hệ thống", ex:"Diese Woche habe ich Bereitschaftsdienst.", exEn:"I'm on call this week.", ipa:"be-RYT-shafts-deenst", coll:"Bereitschaftsdienst haben", tip:"Auch einfach „On-Call“ im Dev-Alltag.", topic:"DevOps", level:"B2" },
  { id:"fc1030", de:"Wartungsarbeiten", article:"die", plural:"(nur Plural)", en:"maintenance work", vi:"bảo trì", ex:"Am Freitag führen wir Wartungsarbeiten durch.", exEn:"We're doing maintenance work on Friday.", ipa:"VAR-tungs-ar-by-ten", coll:"Wartungsarbeiten durchführen", tip:"Meist im Plural. Wartungsfenster = maintenance window.", topic:"DevOps", level:"B2" },
  { id:"fc1031", de:"Kenntnisse", article:"die", plural:"(nur Plural)", en:"knowledge, skills", vi:"kiến thức", ex:"Deutschkenntnisse erhöhen deine Chancen deutlich.", exEn:"German skills clearly improve your chances.", ipa:"KENT-nis-se", coll:"Kenntnisse mitbringen/nachweisen", tip:"Fast immer Plural. Singular „die Kenntnis“ ist selten.", topic:"Career", level:"B1" },
  { id:"fc1032", de:"Vorgang", article:"der", plural:"die Vorgänge", en:"process, transaction", vi:"thao tác, giao dịch", ex:"Der Service speichert alle Vorgänge in der Datenbank.", exEn:"The service stores all transactions in the database.", ipa:"FOR-gang", coll:"einen Vorgang speichern/abbrechen", tip:"Umlaut im Plural: Vorgänge.", topic:"Software Development", level:"B2" },
  { id:"fc1033", de:"Bedarf", article:"der", plural:"—", en:"demand, need", vi:"nhu cầu", ex:"Der Bedarf an Cloud-Entwicklern ist groß.", exEn:"Demand for cloud developers is high.", ipa:"be-DARF", coll:"Bedarf an + Dativ", tip:"Kein Plural. Signatur: Bedarf AN + Dat.", topic:"Career", level:"B2" },
  { id:"fc1034", de:"fehlschlagen", article:"—", plural:"—", en:"to fail", vi:"thất bại", ex:"Ohne Datenbank schlagen die Integrationstests fehl.", exEn:"Without a database the integration tests fail.", ipa:"FEEL-shlaa-gen", coll:"ein Test/ein Deployment schlägt fehl", tip:"Trennbar: schlägt … fehl. Perfekt mit sein: ist fehlgeschlagen.", topic:"Testing", level:"B2" },
  { id:"fc1035", de:"erreichbar", article:"—", plural:"—", en:"reachable, available", vi:"truy cập được", ex:"Die Anwendung ist unter Port 8080 erreichbar.", exEn:"The application is available on port 8080.", ipa:"er-RYKH-baar", coll:"erreichbar sein/bleiben", tip:"Auch für Personen: „Ich bin ab 9 Uhr erreichbar.“", topic:"DevOps", level:"B1" },

  /* ---- Writing · Übungsteil ---- */
  { id:"fc1036", de:"Anrede", article:"die", plural:"die Anreden", en:"salutation", vi:"lời chào đầu thư", ex:"Nach der Anrede geht es klein weiter.", exEn:"After the salutation you continue in lowercase.", ipa:"AN-ree-de", coll:"die richtige Anrede wählen", tip:"Sehr geehrte/r … = formell; Hallo … = normal.", topic:"Writing", level:"B1" },
  { id:"fc1037", de:"Betreff", article:"der", plural:"die Betreffe", en:"subject line", vi:"dòng chủ đề", ex:"Betreff: Lesezugriff auf die Produktionsumgebung", exEn:"Subject: read access to the production environment", ipa:"be-TREF", coll:"einen Betreff formulieren", tip:"Ohne Artikel im Mailkopf: „Betreff: …“.", topic:"Writing", level:"B1" },
  { id:"fc1038", de:"Anliegen", article:"das", plural:"die Anliegen", en:"request, concern", vi:"việc cần", ex:"Mein Anliegen ist kurz erklärt.", exEn:"My request is quickly explained.", ipa:"AN-lee-gen", coll:"ein Anliegen haben/vorbringen", tip:"Plural = Singular.", topic:"Writing", level:"B2" },
  { id:"fc1039", de:"Genehmigung", article:"die", plural:"die Genehmigungen", en:"approval, authorization", vi:"sự phê duyệt", ex:"Ich brauche noch die Genehmigung vom Teamleiter.", exEn:"I still need approval from the team lead.", ipa:"ge-NEE-mi-gung", coll:"eine Genehmigung einholen/erteilen", tip:"-ung → die. Verb: genehmigen.", topic:"Workplace", level:"B2" },
  { id:"fc1040", de:"Zugriff", article:"der", plural:"die Zugriffe", en:"access (read/write)", vi:"quyền truy cập", ex:"Ich brauche Lesezugriff auf die Produktionsumgebung.", exEn:"I need read access to the production environment.", ipa:"TSUU-grif", coll:"Zugriff auf + Akkusativ", tip:"Lesezugriff / Schreibzugriff — der Unterschied zählt!", topic:"Security", level:"B1" },
  { id:"fc1041", de:"Übergabe", article:"die", plural:"die Übergaben", en:"handover", vi:"bàn giao", ex:"Vor dem Urlaub schreibe ich eine kurze Übergabe.", exEn:"Before vacation I write a short handover.", ipa:"üü-ber-GAA-be", coll:"eine Übergabe schreiben/machen", tip:"Verb: übergeben (untrennbar).", topic:"Workplace", level:"B2" },
  { id:"fc1042", de:"freischalten", article:"—", plural:"—", en:"to unlock, to grant access", vi:"mở quyền", ex:"Könnten Sie mir den Zugang bis Mittwoch freischalten?", exEn:"Could you grant me access by Wednesday?", ipa:"FRY-shal-ten", coll:"einen Zugang/ein Feature freischalten", tip:"Trennbar: ich schalte frei.", topic:"DevOps", level:"B2" },
  { id:"fc1043", de:"verschieben", article:"—", plural:"—", en:"to postpone, to move", vi:"dời lịch", ex:"Können wir das Deployment auf Samstag verschieben?", exEn:"Can we move the deployment to Saturday?", ipa:"fer-SHEE-ben", coll:"einen Termin verschieben auf + Akk", tip:"Auch: ein Ticket in den nächsten Sprint verschieben.", topic:"Agile", level:"B1" },

  /* ---- Assessment ---- */
  { id:"fc1044", de:"Freigabe", article:"die", plural:"die Freigaben", en:"approval, sign-off, release", vi:"phê duyệt", ex:"Für jedes Release braucht ihr zwei Freigaben.", exEn:"Every release needs two sign-offs.", ipa:"FRY-gaa-be", coll:"eine Freigabe erteilen/einholen", tip:"Fachliche Freigabe = PO; technische = Code-Review.", topic:"Agile", level:"B2" },
  { id:"fc1045", de:"Vorfall", article:"der", plural:"die Vorfälle", en:"incident", vi:"sự cố", ex:"Der Bericht zum Vorfall kommt bis Donnerstag.", exEn:"The incident report is coming by Thursday.", ipa:"FOR-fal", coll:"einen Vorfall melden/analysieren", tip:"Umlaut im Plural. Incident-Management = das Störungsmanagement.", topic:"DevOps", level:"B2" },
  { id:"fc1046", de:"Rücksprache", article:"die", plural:"die Rücksprachen", en:"consultation", vi:"trao đổi trước", ex:"Freitags wird nur nach Rücksprache deployt.", exEn:"On Fridays we only deploy after consultation.", ipa:"RÜK-shpraa-khe", coll:"nach Rücksprache mit + Dativ", tip:"Feste Wendung: „nach Rücksprache mit …“.", topic:"Workplace", level:"C1" },
  { id:"fc1047", de:"Auswertung", article:"die", plural:"die Auswertungen", en:"evaluation, scoring, analysis", vi:"đánh giá kết quả", ex:"Die Auswertung des Tests zeigt deine Schwachstellen.", exEn:"The test evaluation shows your weak spots.", ipa:"AUS-ver-tung", coll:"eine Auswertung machen", tip:"-ung → die. Verb: auswerten (trennbar).", topic:"Übungen", level:"B2" },
  { id:"fc1048", de:"zulassen", article:"—", plural:"—", en:"to permit, to allow", vi:"cho phép", ex:"Ohne beide Freigaben lässt die Pipeline das Deployment nicht zu.", exEn:"Without both approvals the pipeline won't allow the deployment.", ipa:"TSUU-las-sen", coll:"etwas zulassen/nicht zulassen", tip:"Trennbar: lässt … zu.", topic:"DevOps", level:"B2" },
  { id:"fc1049", de:"bestehen", article:"—", plural:"—", en:"to pass (a test)", vi:"đỗ, vượt qua", ex:"Ich habe die Prüfung mit 78 Punkten bestanden.", exEn:"I passed the exam with 78 points.", ipa:"be-SHTEE-en", coll:"eine Prüfung bestehen", tip:"Auch: bestehen AUS + Dat (to consist of) — zwei Bedeutungen!", topic:"Exam", level:"B1" },
  { id:"fc1050", de:"Prüfung", article:"die", plural:"die Prüfungen", en:"exam, test", vi:"kỳ thi", ex:"Die Prüfung dauert 90 Minuten.", exEn:"The exam takes 90 minutes.", ipa:"PRÜÜ-fung", coll:"eine Prüfung ablegen/bestehen", tip:"-ung → die. Verb: prüfen.", topic:"Exam", level:"B1" }
]);
