/*! flashcards-6.js — Phase 2 workbook + office dialogues deck (Đợt 3).
 * Merges onto window.FLASHCARDS.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- Phase 2 · Grammar & Vocabulary ---- */
  { id:"fc3001", de:"Engpass", article:"der", plural:"die Engpässe", en:"bottleneck", vi:"nút thắt cổ chai", ex:"Die Datenbank ist der Engpass im System.", exEn:"The database is the bottleneck in the system.", ipa:"ENG-pas", coll:"der Engpass sein/beseitigen", tip:"eng + Pass. Umlaut im Plural.", topic:"Architecture", level:"B2" },
  { id:"fc3002", de:"Ausfall", article:"der", plural:"die Ausfälle", en:"outage", vi:"sự cố ngừng hoạt động", ex:"Der Ausfall dauerte sechsundfünfzig Minuten.", exEn:"The outage lasted fifty-six minutes.", ipa:"AUS-fal", coll:"einen Ausfall verursachen/beheben", tip:"Verb: ausfallen (trennbar, Perfekt mit sein).", topic:"DevOps", level:"B2" },
  { id:"fc3003", de:"Wartbarkeit", article:"die", plural:"—", en:"maintainability", vi:"khả năng bảo trì", ex:"Die Wartbarkeit leidet unter der hohen Komplexität.", exEn:"Maintainability suffers from the high complexity.", ipa:"VART-baar-kyt", coll:"die Wartbarkeit verbessern", tip:"-keit → immer die. Von wartbar.", topic:"Architecture", level:"B2" },
  { id:"fc3004", de:"Skalierbarkeit", article:"die", plural:"—", en:"scalability", vi:"khả năng mở rộng", ex:"Die bessere Skalierbarkeit ist der Hauptgrund.", exEn:"Better scalability is the main reason.", ipa:"ska-LEER-baar-kyt", coll:"die Skalierbarkeit erhöhen", tip:"-keit → die. Muster: Adjektiv + -keit = Eigenschaft.", topic:"Architecture", level:"B2" },
  { id:"fc3005", de:"Auslieferung", article:"die", plural:"die Auslieferungen", en:"delivery, release", vi:"việc phát hành", ex:"Die Auslieferung wird immer langsamer.", exEn:"Delivery is getting slower and slower.", ipa:"AUS-lee-fe-rung", coll:"eine Auslieferung planen", tip:"-ung → die. Verb: ausliefern.", topic:"DevOps", level:"B2" },
  { id:"fc3006", de:"Nominalisierung", article:"die", plural:"die Nominalisierungen", en:"nominalisation", vi:"danh từ hóa", ex:"Nominalisierung macht Texte dichter, aber schwerer lesbar.", exEn:"Nominalisation makes texts denser but harder to read.", ipa:"no-mi-na-li-ZEE-rung", coll:"eine Nominalisierung auflösen", tip:"Verb → Nomen: bereitstellen → die Bereitstellung.", topic:"Grammar", level:"B2" },
  { id:"fc3007", de:"Relativsatz", article:"der", plural:"die Relativsätze", en:"relative clause", vi:"mệnh đề quan hệ", ex:"Im Relativsatz steht das Verb am Ende.", exEn:"In a relative clause the verb goes at the end.", ipa:"re-la-TEEF-zats", coll:"einen Relativsatz bilden", tip:"Genus vom Bezugswort, Kasus vom eigenen Satz!", topic:"Grammar", level:"B2" },
  { id:"fc3008", de:"verzichten", article:"—", plural:"—", en:"to do without, to forgo", vi:"bỏ, không dùng", ex:"Wir sollten auf Freitagsdeployments verzichten.", exEn:"We should do without Friday deployments.", ipa:"fer-TSIKH-ten", coll:"verzichten auf + Akkusativ", tip:"Signatur: verzichten AUF + Akk.", topic:"Workplace", level:"B2" },
  { id:"fc3009", de:"auslagern", article:"—", plural:"—", en:"to outsource", vi:"thuê ngoài", ex:"Zwei Drittel der Betriebe haben Anwendungen ausgelagert.", exEn:"Two thirds of firms have outsourced applications.", ipa:"AUS-laa-gern", coll:"Anwendungen/Daten auslagern", tip:"Trennbar. Auch: Code in eine Methode auslagern.", topic:"Architecture", level:"B2" },
  { id:"fc3010", de:"auslösen", article:"—", plural:"—", en:"to trigger, to cause", vi:"gây ra", ex:"Der Ausfall wurde durch eine fehlerhafte Konfiguration ausgelöst.", exEn:"The outage was triggered by a faulty configuration.", ipa:"AUS-löö-zen", coll:"einen Fehler/Alarm auslösen", tip:"Trennbar. Sehr häufig im Passiv.", topic:"DevOps", level:"B2" },
  { id:"fc3011", de:"Maßnahme", article:"die", plural:"die Maßnahmen", en:"measure, action item", vi:"biện pháp", ex:"Wir haben drei Maßnahmen beschlossen.", exEn:"We agreed on three measures.", ipa:"MAAS-naa-me", coll:"Maßnahmen beschließen/ergreifen", tip:"Das Standardwort im Post-Mortem.", topic:"Workplace", level:"B2" },
  { id:"fc3012", de:"Erhebung", article:"die", plural:"die Erhebungen", en:"survey, study", vi:"khảo sát", ex:"Nach einer aktuellen Erhebung setzen mehr Firmen auf Cloud.", exEn:"According to a recent survey more firms rely on cloud.", ipa:"er-HEE-bung", coll:"laut einer Erhebung", tip:"-ung → die. Formeller als „die Umfrage“.", topic:"Reading", level:"B2" },
  { id:"fc3013", de:"Einwand", article:"der", plural:"die Einwände", en:"objection", vi:"ý phản biện", ex:"Guter Einwand, aber ich würde das erst mal weglassen.", exEn:"Good point, but I'd leave that out for now.", ipa:"AYN-vant", coll:"einen Einwand erheben", tip:"Umlaut im Plural. „Guter Einwand“ = höfliches Widersprechen.", topic:"Speaking", level:"B2" },
  { id:"fc3014", de:"Fachkräftemangel", article:"der", plural:"—", en:"skills shortage", vi:"thiếu nhân lực", ex:"Der Fachkräftemangel ist zum Teil hausgemacht.", exEn:"The skills shortage is partly self-inflicted.", ipa:"FAKH-kref-te-man-gel", coll:"der Fachkräftemangel in der IT", tip:"Fachkräfte + Mangel → der (von Mangel).", topic:"Career", level:"B2" },
  { id:"fc3015", de:"Verhandlungsmacht", article:"die", plural:"—", en:"bargaining power", vi:"thế thương lượng", ex:"Wer alles auslagert, verliert Verhandlungsmacht.", exEn:"Whoever outsources everything loses bargaining power.", ipa:"fer-HAND-lungs-makht", coll:"Verhandlungsmacht verlieren/haben", tip:"Verhandlung + Macht → die.", topic:"Career", level:"C1" },
  { id:"fc3016", de:"unbedenklich", article:"—", plural:"—", en:"safe, harmless", vi:"an toàn", ex:"Wiederholungen sind nur bei idempotenten Operationen unbedenklich.", exEn:"Retries are only safe with idempotent operations.", ipa:"un-be-DENK-likh", coll:"etwas ist unbedenklich", tip:"un + bedenklich (worrying).", topic:"Architecture", level:"C1" },
  { id:"fc3017", de:"nachgelagert", article:"—", plural:"—", en:"downstream", vi:"phía sau, phụ thuộc", ex:"Die Anfrage wird an einen nachgelagerten Dienst weitergereicht.", exEn:"The request is passed to a downstream service.", ipa:"NAAKH-ge-laa-gert", coll:"ein nachgelagerter Dienst", tip:"Gegenteil: vorgelagert (upstream).", topic:"Architecture", level:"C1" },
  { id:"fc3018", de:"Zeitfenster", article:"das", plural:"die Zeitfenster", en:"time window", vi:"khung thời gian", ex:"Je später wir ausliefern, desto kleiner das Zeitfenster für eine Reaktion.", exEn:"The later we deliver, the smaller the window to react.", ipa:"TSYT-fens-ter", coll:"ein Zeitfenster haben", tip:"Plural = Singular.", topic:"DevOps", level:"B2" },
  { id:"fc3019", de:"Aufwand", article:"der", plural:"die Aufwände", en:"effort", vi:"công sức", ex:"Das kostet jetzt Zeit, spart aber später erheblichen Aufwand.", exEn:"It costs time now but saves considerable effort later.", ipa:"AUF-vant", coll:"Aufwand sparen/schätzen", tip:"Aufwandsschätzung = effort estimate.", topic:"Agile", level:"B2" },
  { id:"fc3020", de:"Stellung nehmen", article:"—", plural:"—", en:"to comment, take a position", vi:"nêu quan điểm", ex:"Bitte nehmen Sie dazu kurz Stellung.", exEn:"Please comment on this briefly.", ipa:"SHTEL-lung NEE-men", coll:"zu etwas Stellung nehmen", tip:"Signatur: Stellung nehmen ZU + Dat. Prüfungsvokabel!", topic:"Exam", level:"B2" },

  /* ---- Dialogue · Onboarding ---- */
  { id:"fc3021", de:"Zugangsdaten", article:"die", plural:"(nur Plural)", en:"credentials", vi:"thông tin đăng nhập", ex:"Die IT schickt dir gleich die Zugangsdaten.", exEn:"IT will send you the credentials shortly.", ipa:"TSUU-gangs-daa-ten", coll:"Zugangsdaten bekommen/beantragen", tip:"Immer Plural.", topic:"Workplace", level:"B1" },
  { id:"fc3022", de:"Gleitzeit", article:"die", plural:"—", en:"flexitime", vi:"giờ làm linh hoạt", ex:"Wir haben Gleitzeit mit Kernzeit von zehn bis fünfzehn Uhr.", exEn:"We have flexitime with core hours from ten to three.", ipa:"GLYT-tsyt", coll:"Gleitzeit haben", tip:"Gegenstück: die Kernzeit (Anwesenheitspflicht).", topic:"Workplace", level:"B1" },
  { id:"fc3023", de:"Einarbeitung", article:"die", plural:"die Einarbeitungen", en:"onboarding period", vi:"thời gian làm quen việc", ex:"Nimm dir für die Einarbeitung wirklich Zeit.", exEn:"Really take your time with the onboarding.", ipa:"AYN-ar-by-tung", coll:"die Einarbeitung dauert …", tip:"-ung → die. Verb: sich einarbeiten.", topic:"Workplace", level:"B1" },
  { id:"fc3024", de:"duzen", article:"—", plural:"—", en:"to use 'du' with sb", vi:"xưng hô thân mật", ex:"Wollen wir uns duzen?", exEn:"Shall we use first names?", ipa:"DUU-tsen", coll:"jemanden duzen / per du sein", tip:"Gegenteil: siezen. Das du wird ANGEBOTEN, nicht genommen.", topic:"Culture", level:"B1" },
  { id:"fc3025", de:"Bescheid sagen", article:"—", plural:"—", en:"to let sb know", vi:"báo cho biết", ex:"Sag Bescheid, wenn du was brauchst.", exEn:"Let me know if you need anything.", ipa:"be-SHYT ZAA-gen", coll:"jemandem Bescheid sagen/geben", tip:"Feste Wendung, „Bescheid“ großgeschrieben.", topic:"Workplace", level:"B1" },
  { id:"fc3026", de:"übelnehmen", article:"—", plural:"—", en:"to hold sth against sb", vi:"chấp nhặt", ex:"Das nimmt dir hier keiner übel.", exEn:"Nobody here will hold that against you.", ipa:"ÜÜ-bel-nee-men", coll:"jemandem etwas übelnehmen", tip:"Trennbar + Dativ der Person.", topic:"Culture", level:"B2" },
  { id:"fc3027", de:"Vorgesetzte", article:"der/die", plural:"die Vorgesetzten", en:"superior, manager", vi:"cấp trên", ex:"Gegenüber Vorgesetzten außerhalb der IT bleibt man oft beim Sie.", exEn:"With managers outside IT you often stay with Sie.", ipa:"FOR-ge-zets-te", coll:"der direkte Vorgesetzte", tip:"Adjektivisches Nomen — Endung ändert sich mit dem Artikel.", topic:"Workplace", level:"B2" },

  /* ---- Dialogue · Krankmeldung & Urlaub ---- */
  { id:"fc3028", de:"Übergabe", article:"die", plural:"die Übergaben", en:"handover", vi:"bàn giao", ex:"Zur Übergabe: PAY-482 ist fertig, es fehlt nur das Review.", exEn:"For the handover: PAY-482 is done, only the review is missing.", ipa:"üü-ber-GAA-be", coll:"eine Übergabe schreiben", tip:"Verb: übergeben (untrennbar).", topic:"Workplace", level:"B2" },
  { id:"fc3029", de:"Urlaubsantrag", article:"der", plural:"die Urlaubsanträge", en:"holiday request", vi:"đơn xin nghỉ phép", ex:"Ich stelle den Urlaubsantrag heute noch im System.", exEn:"I'll submit the holiday request in the system today.", ipa:"UR-laups-an-traag", coll:"einen Urlaubsantrag stellen", tip:"Umlaut im Plural. beantragen → genehmigen.", topic:"Workplace", level:"B2" },
  { id:"fc3030", de:"Resturlaub", article:"der", plural:"—", en:"remaining leave", vi:"phép còn lại", ex:"Der Resturlaub verfällt bei uns Ende März.", exEn:"Leftover leave expires here at the end of March.", ipa:"REST-ur-laup", coll:"Resturlaub nehmen/verfällt", tip:"Frag früh nach der Verfallsregel im Vertrag!", topic:"Workplace", level:"B2" },
  { id:"fc3031", de:"Lohnfortzahlung", article:"die", plural:"—", en:"continued pay when sick", vi:"trả lương khi ốm", ex:"Die Lohnfortzahlung läuft bis zu sechs Wochen.", exEn:"Continued pay runs for up to six weeks.", ipa:"LOON-fort-tsaa-lung", coll:"Anspruch auf Lohnfortzahlung", tip:"Danach zahlt die Krankenkasse Krankengeld.", topic:"Workplace", level:"C1" },
  { id:"fc3032", de:"beantragen", article:"—", plural:"—", en:"to apply for", vi:"nộp đơn xin", ex:"Urlaub muss man im Zeiterfassungssystem beantragen.", exEn:"Holiday has to be requested in the time-tracking system.", ipa:"be-AN-traa-gen", coll:"Urlaub/einen Zugang beantragen", tip:"Untrennbar, Partizip ohne ge-: beantragt.", topic:"Workplace", level:"B2" },
  { id:"fc3033", de:"genehmigen", article:"—", plural:"—", en:"to approve", vi:"phê duyệt", ex:"Deine Teamleitung genehmigt den Antrag im System.", exEn:"Your team lead approves the request in the system.", ipa:"ge-NEE-mi-gen", coll:"einen Antrag genehmigen/ablehnen", tip:"Gegenteil: ablehnen.", topic:"Workplace", level:"B2" },
  { id:"fc3034", de:"verfallen", article:"—", plural:"—", en:"to expire, to lapse", vi:"hết hạn", ex:"Nicht genommener Urlaub verfällt am 31. März.", exEn:"Untaken leave expires on 31 March.", ipa:"fer-FAL-len", coll:"Urlaub/ein Ticket verfällt", tip:"Perfekt mit sein: ist verfallen.", topic:"Workplace", level:"B2" },

  /* ---- Dialogue · Pair Programming ---- */
  { id:"fc3035", de:"Validierung", article:"die", plural:"die Validierungen", en:"validation", vi:"kiểm tra hợp lệ", ex:"Ich würde erst mal schauen, wo die Validierung passiert.", exEn:"I'd first look at where validation happens.", ipa:"va-li-DEE-rung", coll:"die Validierung greift/fehlt", tip:"-ung → die.", topic:"Software Development", level:"B2" },
  { id:"fc3036", de:"Ausnahme", article:"die", plural:"die Ausnahmen", en:"exception", vi:"ngoại lệ", ex:"Der Handler kennt diese Ausnahme nicht.", exEn:"The handler doesn't know this exception.", ipa:"AUS-naa-me", coll:"eine Ausnahme werfen/abfangen", tip:"werfen = throw, abfangen = catch.", topic:"Software Development", level:"B2" },
  { id:"fc3037", de:"Zeile", article:"die", plural:"die Zeilen", en:"line (of code)", vi:"dòng", ex:"Hier, Zeile vierundzwanzig.", exEn:"Here, line twenty-four.", ipa:"TSY-le", coll:"in Zeile … springen", tip:"Zahlen laut üben — sie sind die häufigste Verständnislücke.", topic:"Software Development", level:"B1" },
  { id:"fc3038", de:"Folgeticket", article:"das", plural:"die Folgetickets", en:"follow-up ticket", vi:"ticket tiếp theo", ex:"Machen wir ein Folgeticket draus?", exEn:"Shall we make a follow-up ticket of it?", ipa:"FOL-ge-ti-ket", coll:"ein Folgeticket anlegen", tip:"Höflicher Weg, etwas aus dem Scope zu nehmen.", topic:"Agile", level:"B2" },
  { id:"fc3039", de:"ergänzen", article:"—", plural:"—", en:"to add, to supplement", vi:"bổ sung", ex:"Wie wäre es, wenn wir dort einen Handler ergänzen?", exEn:"How about we add a handler there?", ipa:"er-GEN-tsen", coll:"etwas ergänzen", tip:"UNtrennbar: ich ergänze, habe ergänzt.", topic:"Software Development", level:"B2" },
  { id:"fc3040", de:"weglassen", article:"—", plural:"—", en:"to leave out, to omit", vi:"bỏ qua", ex:"Ich würde das erst mal weglassen, sonst wird der Scope zu groß.", exEn:"I'd leave that out for now, otherwise the scope gets too big.", ipa:"VEK-las-sen", coll:"etwas weglassen", tip:"Trennbar: ich lasse … weg.", topic:"Software Development", level:"B2" },
  { id:"fc3041", de:"drüberschauen", article:"—", plural:"—", en:"to look over, review quickly", vi:"xem qua", ex:"Willst du drüberschauen, bevor wir pushen?", exEn:"Want to look it over before we push?", ipa:"DRÜÜ-ber-shau-en", coll:"kurz drüberschauen", tip:"Umgangssprachlich für „durchsehen“. Trennbar.", topic:"Software Development", level:"B2" },
  { id:"fc3042", de:"ausprobieren", article:"—", plural:"—", en:"to try out", vi:"thử", ex:"Lass uns das mal ausprobieren.", exEn:"Let's just try it out.", ipa:"AUS-pro-bee-ren", coll:"etwas ausprobieren", tip:"Trennbar, aber Partizip ohne ge- im Stamm: ausprobiert.", topic:"Software Development", level:"B1" },
  { id:"fc3043", de:"Gedanke", article:"der", plural:"die Gedanken", en:"thought", vi:"suy nghĩ", ex:"Mein Gedanke wäre, dass die Validierung gar nicht aktiv ist.", exEn:"My thought would be that validation isn't active at all.", ipa:"ge-DAN-ke", coll:"einen Gedanken haben/äußern", tip:"n-Deklination: des Gedankens, dem Gedanken.", topic:"Speaking", level:"B2" },
  { id:"fc3044", de:"Umfang", article:"der", plural:"die Umfänge", en:"scope, extent", vi:"phạm vi", ex:"Sonst wird der Umfang zu groß.", exEn:"Otherwise the scope gets too big.", ipa:"UM-fang", coll:"den Umfang begrenzen", tip:"Im Dev-Alltag sagt man meist „der Scope“.", topic:"Agile", level:"B2" },
  { id:"fc3045", de:"tauschen", article:"—", plural:"—", en:"to swap", vi:"đổi", ex:"Wir tauschen alle zwanzig Minuten die Rollen.", exEn:"We swap roles every twenty minutes.", ipa:"TAU-shen", coll:"die Rollen/Plätze tauschen", tip:"Nicht mit „täuschen“ (to deceive) verwechseln!", topic:"Agile", level:"B1" }
]);
