/*! flashcards-17.js — die letzte Ernte: exams/ (Hören, Lesen-Sprachbausteine), interviews/
 * (4 Bänke) und die sechs Reste aus vocabulary/ — Flashcard-Pass 5.
 * Harvested per AUTHORING §6.1. 50 Zeilen → 46 Karten: drei echte Dubletten
 * (koppeln (an), Kompromiss, sich abstimmen) und eine Zeile, deren Deutsch nicht zu ihrer
 * eigenen englischen Glosse passt (*Vererbung überschreiben* — man überschreibt eine Methode).
 * Damit ist der messbare Vorrat erschöpft; siehe §6.1.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- telc B2 · Hörverstehen ---- */
  { id:"fc9801", de:"Hörverstehen", article:"das", plural:"—", en:"listening comprehension", vi:"nghe hiểu", ex:"Das Hörverstehen läuft ohne Pause — du hörst jeden Teil nur einmal.", exEn:"The listening section runs without a break — you hear each part only once.", ipa:"HÖÖR-fer-shtee-en", coll:"das Hörverstehen trainieren", tip:"Substantivierter Infinitiv → *das*, kein Plural. Ebenso: das Leseverstehen, das Sprechen, das Schreiben.", topic:"Exam", level:"B2" },
  { id:"fc9802", de:"Durchlaufzeit", article:"die", plural:"die Durchlaufzeiten", en:"lead time", vi:"thời gian xử lý", ex:"Die Durchlaufzeit vom Ticket bis zum Release liegt bei vier Tagen.", exEn:"The lead time from ticket to release is four days.", ipa:"DURKH-lauf-tsayt", coll:"die Durchlaufzeit verkürzen", tip:"Kopf: die Zeit → die. Nicht *die Laufzeit* (runtime, contract term) — *durch* macht daraus die Zeit durch den ganzen Prozess.", topic:"Exam", level:"C1" },
  { id:"fc9803", de:"Testabdeckung", article:"die", plural:"—", en:"test coverage", vi:"độ bao phủ test", ex:"Die Testabdeckung liegt bei achtzig Prozent, sagt aber nichts über die Qualität.", exEn:"Test coverage is at eighty percent, but says nothing about quality.", ipa:"TEST-ap-de-kung", coll:"die Testabdeckung erhöhen", tip:"-ung → die. Von *abdecken*. Eine Zahl, die im Vorstellungsgespräch gern kritisch eingeordnet werden will.", topic:"Exam", level:"B2" },
  { id:"fc9804", de:"Bildungsurlaub", article:"der", plural:"—", en:"educational leave", vi:"nghỉ phép để học", ex:"Für den Sprachkurs nehme ich Bildungsurlaub — fünf Tage, bezahlt.", exEn:"I'm taking educational leave for the language course — five days, paid.", ipa:"BIL-dungs-uur-laup", coll:"Bildungsurlaub beantragen", tip:"Kopf: der Urlaub → der. Ein gesetzlicher Anspruch in den meisten Bundesländern, meist fünf Tage im Jahr — und erstaunlich selten genutzt.", topic:"Exam", level:"C1" },
  { id:"fc9805", de:"Vorbehalt", article:"der", plural:"die Vorbehalte", en:"reservation, caveat", vi:"sự dè dặt", ex:"Ich stimme zu, aber mit einem Vorbehalt: Wir brauchen vorher Messwerte.", exEn:"I agree, but with one reservation: we need measurements first.", ipa:"FOR-be-halt", coll:"unter Vorbehalt zustimmen", tip:"*unter Vorbehalt* = subject to confirmation. Im Prüfungsgespräch das Wort für halbe Zustimmung.", topic:"Exam", level:"C1" },
  { id:"fc9806", de:"Einräumung", article:"die", plural:"die Einräumungen", en:"concession", vi:"sự nhượng bộ", ex:"Nach einer kleinen Einräumung fällt das eigene Argument stärker aus.", exEn:"After a small concession your own argument lands harder.", ipa:"AYN-roy-mung", coll:"eine Einräumung machen", tip:"-ung → die. Das grammatische Werkzeug dazu heißt *der Konzessivsatz*: *zwar … aber*, *obwohl*, *auch wenn*.", topic:"Exam", level:"C1" },
  { id:"fc9807", de:"verfrüht", article:"—", plural:"—", en:"premature", vi:"quá sớm", ex:"Eine Entscheidung wäre jetzt verfrüht — die Messung läuft noch.", exEn:"A decision would be premature now — the measurement is still running.", ipa:"fer-FRÜÜT", coll:"verfrüht sein", tip:"Partizip von *verfrühen*, praktisch nur als Adjektiv. Höflicher als *zu früh* und in der Prüfung ein Punktebringer.", topic:"Exam", level:"C1" },
  { id:"fc9808", de:"sinken / steigen", article:"—", plural:"—", en:"to fall / to rise", vi:"giảm / tăng", ex:"Die Fehlerrate sinkt, die Latenz steigt — beides gleichzeitig.", exEn:"The error rate is falling, latency is rising — both at once.", ipa:"ZIN-ken / SHTAY-gen", coll:"um zehn Prozent sinken / steigen", tip:"Beide stark und mit *sein*: sinkt, sank, gesunken; steigt, stieg, gestiegen. Das Grundpaar jeder Grafikbeschreibung.", topic:"Exam", level:"B2" },

  /* ---- telc B2 · Leseverstehen und Sprachbausteine ---- */
  { id:"fc9809", de:"Sprachbausteine", article:"die", plural:"die Sprachbausteine (Prüfungsteil)", en:"language elements (exam part)", vi:"phần ngữ pháp/từ vựng", ex:"Die Sprachbausteine prüfen Grammatik im Text, nicht isoliert.", exEn:"The Sprachbausteine section tests grammar in context, not in isolation.", ipa:"SHPRAAKH-bau-shtay-ne", coll:"die Sprachbausteine üben", tip:"Als Prüfungsteil immer Plural. Teil 1 prüft Grammatik, Teil 2 Wortschatz — der zweite ist der schwerere.", topic:"Exam", level:"B2" },
  { id:"fc9810", de:"Leseverstehen", article:"das", plural:"—", en:"reading comprehension", vi:"đọc hiểu", ex:"Beim Leseverstehen liest du zuerst die Fragen, dann den Text.", exEn:"For reading comprehension you read the questions first, then the text.", ipa:"LEE-ze-fer-shtee-en", coll:"das Leseverstehen trainieren", tip:"Substantivierter Infinitiv → *das*, kein Plural. Die Technik heißt *überfliegen* — nicht Wort für Wort lesen.", topic:"Exam", level:"B2" },
  { id:"fc9811", de:"Aufgabentyp", article:"der", plural:"die Aufgabentypen", en:"task type", vi:"dạng bài", ex:"Es gibt drei Aufgabentypen — kennst du sie, sparst du im Test Minuten.", exEn:"There are three task types — knowing them saves you minutes in the test.", ipa:"AUF-gaa-ben-tüp", coll:"die Aufgabentypen kennen", tip:"Kopf: der Typ → der. Fugen-n. Plural *-typen*, mit langem ü gesprochen.", topic:"Exam", level:"B2" },
  { id:"fc9812", de:"Zuordnung", article:"die", plural:"die Zuordnungen", en:"matching (task)", vi:"nối, ghép", ex:"Bei der Zuordnung bleibt immer eine Überschrift übrig — das ist Absicht.", exEn:"In matching tasks one heading is always left over — that's deliberate.", ipa:"TSUU-ord-nung", coll:"eine Zuordnung treffen", tip:"-ung → die. Von *zuordnen*. Der übrige Distraktor ist Prüfungsdesign, kein Fehler von dir.", topic:"Exam", level:"B2" },
  { id:"fc9813", de:"Befragung", article:"die", plural:"die Befragungen", en:"survey", vi:"cuộc khảo sát", ex:"Laut einer Befragung unter Beschäftigten wünschen sich zwei Drittel mehr Homeoffice.", exEn:"According to a survey of employees, two thirds want more remote work.", ipa:"be-FRAA-gung", coll:"laut einer Befragung", tip:"-ung → die. *laut* + Dativ oder Genitiv — die Standardquellenangabe in Prüfungstexten.", topic:"Exam", level:"B2" },
  { id:"fc9814", de:"Anwesenheit", article:"die", plural:"—", en:"attendance, presence", vi:"sự có mặt", ex:"Die Anwesenheit im Büro ist an zwei Tagen verpflichtend.", exEn:"Attendance in the office is mandatory on two days.", ipa:"AN-vee-zen-hayt", coll:"die Anwesenheit regeln", tip:"-heit → die, kein Plural. Gegenteil: die Abwesenheit. Von *anwesend* / *abwesend*.", topic:"Exam", level:"B2" },
  { id:"fc9815", de:"übertragen", article:"—", plural:"—", en:"to transfer", vi:"chuyển sang", ex:"Übertrag die Lösungen rechtzeitig auf den Antwortbogen.", exEn:"Transfer your answers onto the answer sheet in good time.", ipa:"üü-ber-TRAA-gen", coll:"auf den Antwortbogen übertragen", tip:"Stark und untrennbar: überträgt, übertrug, übertragen — kein *ge-*. Auch: Rechte übertragen, ein Spiel übertragen (to broadcast).", topic:"Exam", level:"B2" },

  /* ---- Interview · Backend ---- */
  { id:"fc9816", de:"Anziehungskraft", article:"die", plural:"die Anziehungskräfte", en:"appeal, draw", vi:"sức hút", ex:"Die Anziehungskraft der Stelle liegt für mich im Team, nicht im Stack.", exEn:"The appeal of the role for me is the team, not the stack.", ipa:"AN-tsee-ungs-kraft", coll:"die Anziehungskraft ausmachen", tip:"Kopf: die Kraft → die, Umlaut im Plural. Wörtlich die Gravitation — im Gespräch die elegante Antwort auf „Warum wir?“.", topic:"Career", level:"C1" },
  { id:"fc9817", de:"Rahmenbedingungen", article:"die", plural:"die Rahmenbedingungen (meist Plural)", en:"framework conditions", vi:"điều kiện khung", ex:"Unter diesen Rahmenbedingungen war die Entscheidung richtig.", exEn:"Under those framework conditions the decision was right.", ipa:"RAA-men-be-ding-ung-en", coll:"unter den gegebenen Rahmenbedingungen", tip:"Fast immer Plural. Die Formel *unter den gegebenen Rahmenbedingungen* erklärt eine alte Entscheidung, ohne sie zu verteidigen.", topic:"Career", level:"C1" },
  { id:"fc9818", de:"Idempotenz", article:"die", plural:"—", en:"idempotency", vi:"tính bất biến khi lặp", ex:"Idempotenz heißt: Dieselbe Anfrage zweimal ändert nichts am Ergebnis.", exEn:"Idempotency means the same request twice changes nothing about the result.", ipa:"i-dem-po-TENTS", coll:"Idempotenz sicherstellen", tip:"-enz → die, endbetont, kein Plural. Adjektiv: idempotent. Die klassische Rückfrage zu jedem Retry.", topic:"Architecture", level:"C1" },
  { id:"fc9819", de:"Grundursache", article:"die", plural:"die Grundursachen", en:"root cause", vi:"nguyên nhân gốc", ex:"Die Grundursache war nicht der Ausfall, sondern die fehlende Warnung davor.", exEn:"The root cause wasn't the outage but the missing warning before it.", ipa:"GRUNT-uur-zaa-khe", coll:"die Grundursache benennen", tip:"Kopf: die Ursache → die. Das Verfahren heißt *die Ursachenforschung*, die Behebung *die Ursachenbehebung*.", topic:"DevOps", level:"C1" },
  { id:"fc9820", de:"technische Schulden", article:"die", plural:"die technischen Schulden (nur Plural)", en:"technical debt", vi:"nợ kỹ thuật", ex:"Technische Schulden sind kein Versagen, sondern eine bewusst aufgenommene Anleihe.", exEn:"Technical debt isn't failure but a deliberately taken loan.", ipa:"TEKH-ni-she SHUL-den", coll:"technische Schulden aufnehmen / abbauen", tip:"*die Schulden* gibt es nur im Plural, das Adjektiv dekliniert mit: *die technischen Schulden*. Das Bild ist bewusst finanziell — man nimmt sie auf und zahlt Zinsen.", topic:"Software Development", level:"C1" },
  { id:"fc9821", de:"aussagekräftig", article:"—", plural:"—", en:"meaningful, expressive", vi:"có ý nghĩa rõ", ex:"Ein aussagekräftiger Name spart mehr Zeit als jeder Kommentar.", exEn:"A meaningful name saves more time than any comment.", ipa:"AUS-zaa-ge-kref-tikh", coll:"ein aussagekräftiger Name", tip:"Von *die Aussage* + *kräftig*. Das Standardwort im Code-Review für gutes Naming — und in der Stellenanzeige für „aussagekräftige Bewerbung“.", topic:"Code Review", level:"B2" },

  /* ---- Interview · DevOps ---- */
  { id:"fc9822", de:"Werkzeugkasten", article:"der", plural:"die Werkzeugkästen", en:"toolbox", vi:"bộ công cụ", ex:"Mein Werkzeugkasten ist bewusst klein — vier Werkzeuge, die ich wirklich kenne.", exEn:"My toolbox is deliberately small — four tools I actually know.", ipa:"VERK-tsoyk-kas-ten", coll:"im Werkzeugkasten haben", tip:"Kopf: der Kasten → der, Umlaut im Plural. *das Werkzeug* ist das Werkzeug — im Plural *die Werkzeuge*.", topic:"DevOps", level:"B2" },
  { id:"fc9823", de:"Fehlerkultur", article:"die", plural:"die Fehlerkulturen", en:"error culture", vi:"văn hóa xử lý lỗi", ex:"Eine gute Fehlerkultur fragt, was das System zugelassen hat — nicht, wer es war.", exEn:"A good error culture asks what the system allowed — not who did it.", ipa:"FEE-ler-kul-tuur", coll:"eine offene Fehlerkultur", tip:"Kopf: die Kultur → die, endbetont. Das dazugehörige Wort ist *schuldfrei* (blameless) — beide gehören ins Postmortem.", topic:"DevOps", level:"C1" },
  { id:"fc9824", de:"Belastung", article:"die", plural:"die Belastungen", en:"strain, load", vi:"tải, gánh nặng", ex:"Unter Belastung zeigt sich, ob das System wirklich entkoppelt ist.", exEn:"Under load you find out whether the system is really decoupled.", ipa:"be-LAS-tung", coll:"unter Belastung stehen", tip:"-ung → die. Gilt für Systeme und für Menschen — dasselbe Wort für Serverlast und für Stress.", topic:"DevOps", level:"B2" },
  { id:"fc9825", de:"Ausfallzeit", article:"die", plural:"die Ausfallzeiten", en:"downtime", vi:"thời gian ngừng", ex:"Die Ausfallzeit lag bei elf Minuten, das Ziel sind fünf.", exEn:"Downtime was eleven minutes, the target is five.", ipa:"AUS-fal-tsayt", coll:"die Ausfallzeit senken", tip:"Kopf: die Zeit → die. Das Gegenstück heißt *die Verfügbarkeit* — meist in Neunen gemessen.", topic:"DevOps", level:"B2" },
  { id:"fc9826", de:"Orchestrierungswerkzeug", article:"das", plural:"die Orchestrierungswerkzeuge", en:"orchestration tool", vi:"công cụ điều phối", ex:"Als Orchestrierungswerkzeug nutzen wir Kubernetes, aber bewusst ohne Service Mesh.", exEn:"As an orchestration tool we use Kubernetes, but deliberately without a service mesh.", ipa:"or-kes-TREE-rungs-verk-tsoyk", coll:"ein Orchestrierungswerkzeug einsetzen", tip:"Kopf: das Werkzeug → das. Verben auf *-ieren* geben *-ierung*: orchestrieren → die Orchestrierung.", topic:"Kubernetes", level:"C1" },
  { id:"fc9827", de:"ausfallsicher", article:"—", plural:"—", en:"fault-tolerant", vi:"chịu lỗi", ex:"Ausfallsicher heißt nicht fehlerfrei, sondern: Ein Ausfall bleibt folgenlos.", exEn:"Fault-tolerant doesn't mean error-free but that an outage has no consequences.", ipa:"AUS-fal-zikh-er", coll:"ausfallsicher auslegen", tip:"*-sicher* als Endung heißt „geschützt dagegen“: ausfallsicher, revisionssicher, kindersicher.", topic:"Architecture", level:"C1" },
  { id:"fc9828", de:"Ursachenforschung", article:"die", plural:"die Ursachenforschungen", en:"root-cause investigation", vi:"điều tra nguyên nhân", ex:"Die Ursachenforschung beginnt erst, wenn der Dienst wieder läuft.", exEn:"Root-cause investigation only begins once the service is running again.", ipa:"UUR-zaa-khen-for-shung", coll:"in die Ursachenforschung gehen", tip:"-ung → die. Fugen-n. Gründlicher als *die Ursachensuche* — die sucht, die Forschung belegt.", topic:"DevOps", level:"C1" },
  { id:"fc9829", de:"Schmerzpunkt", article:"der", plural:"die Schmerzpunkte", en:"pain point", vi:"điểm đau", ex:"Der größte Schmerzpunkt war das Deployment, nicht der Code.", exEn:"The biggest pain point was the deployment, not the code.", ipa:"SHMERTS-punkt", coll:"einen Schmerzpunkt benennen", tip:"Kopf: der Punkt → der. Lehnübersetzung aus dem Englischen, im deutschen Produktjargon inzwischen völlig normal.", topic:"DevOps", level:"C1" },
  { id:"fc9830", de:"fehleranfällig", article:"—", plural:"—", en:"error-prone", vi:"dễ lỗi", ex:"Der manuelle Schritt war fehleranfällig — deshalb haben wir ihn automatisiert.", exEn:"The manual step was error-prone — that's why we automated it.", ipa:"FEE-ler-an-fe-likh", coll:"fehleranfällig sein", tip:"*-anfällig* heißt „neigt dazu“: fehleranfällig, störanfällig, krankheitsanfällig.", topic:"DevOps", level:"C1" },

  /* ---- Interview · HR und Live-Coding ---- */
  { id:"fc9831", de:"Impuls", article:"der", plural:"die Impulse", en:"impulse, first instinct", vi:"phản xạ đầu tiên", ex:"Mein erster Impuls war, sofort zu antworten — besser war die Rückfrage.", exEn:"My first instinct was to answer straight away — the better move was to ask back.", ipa:"im-PULS", coll:"dem ersten Impuls widerstehen", tip:"Endbetont. *Mein erster Impuls war …* ist eine gute Eröffnung im HR-Gespräch: sie zeigt Reflexion statt Reflex.", topic:"Career", level:"C1" },
  { id:"fc9832", de:"Duplikat", article:"das", plural:"die Duplikate", en:"duplicate", vi:"bản trùng", ex:"Erst Duplikate entfernen, dann sortieren — sonst sortierst du doppelt.", exEn:"Remove duplicates first, then sort — otherwise you sort twice.", ipa:"du-pli-KAAT", coll:"Duplikate entfernen", tip:"Endbetont. Verb: duplizieren. Beim Live-Coding das Wort, mit dem du deinen Ansatz laut erklärst.", topic:"Software Development", level:"B2" },
  { id:"fc9833", de:"zurückgeben", article:"—", plural:"—", en:"to return (a value)", vi:"trả về", ex:"Die Methode gibt eine leere Liste zurück, nicht null.", exEn:"The method returns an empty list, not null.", ipa:"tsu-RÜK-gee-ben", coll:"einen Wert zurückgeben", tip:"Trennbar und stark: gebe … zurück, gab … zurück, zurückgegeben. Nomen: der Rückgabewert.", topic:"Java", level:"B2" },

  /* ---- Interview · Spring und Microservices ---- */
  { id:"fc9834", de:"Eigenverantwortung", article:"die", plural:"—", en:"personal responsibility, autonomy", vi:"tự chịu trách nhiệm", ex:"Jedes Team betreibt seinen Dienst in Eigenverantwortung — inklusive Bereitschaft.", exEn:"Each team runs its service autonomously — on-call included.", ipa:"AY-gen-fer-ant-vor-tung", coll:"in Eigenverantwortung betreiben", tip:"-ung → die, kein Plural. Das deutsche Wort für *you build it, you run it* — und im Gespräch wirkungsvoller als der englische Slogan.", topic:"Microservices", level:"C1" },
  { id:"fc9835", de:"fachlich", article:"—", plural:"—", en:"functional, domain-related", vi:"thuộc nghiệp vụ", ex:"Wir schneiden die Dienste fachlich, nicht technisch.", exEn:"We cut the services along domain lines, not technical ones.", ipa:"FAKH-likh", coll:"fachlich schneiden", tip:"Das Gegensatzpaar *fachlich* / *technisch* trägt fast jede deutsche Architekturdiskussion. Auch: *fachlich* = professionally competent, im Karrieregespräch.", topic:"Microservices", level:"C1" },
  { id:"fc9836", de:"letztendliche Konsistenz", article:"die", plural:"—", en:"eventual consistency", vi:"nhất quán sau cùng", ex:"Wir leben mit letztendlicher Konsistenz — die Anzeige hinkt Sekunden hinterher.", exEn:"We live with eventual consistency — the display lags by seconds.", ipa:"letst-ENT-likh-e kon-zis-TENTS", coll:"letztendliche Konsistenz in Kauf nehmen", tip:"Adjektiv dekliniert mit: *mit letztendlicher* Konsistenz im Dativ. Im Team sagt man meist *eventual consistency* — die deutsche Form steht in der Doku.", topic:"Microservices", level:"C1" },
  { id:"fc9837", de:"Saga-Muster", article:"das", plural:"die Saga-Muster", en:"saga pattern", vi:"mẫu saga", ex:"Statt verteilter Transaktionen nutzen wir das Saga-Muster mit Kompensation.", exEn:"Instead of distributed transactions we use the saga pattern with compensation.", ipa:"ZAA-ga-mus-ter", coll:"das Saga-Muster einsetzen", tip:"Kopf: das Muster → das, Plural = Singular. *die Kompensation* ist der Rückabwicklungsschritt — das Wort gehört zur Antwort dazu.", topic:"Microservices", level:"C1" },
  { id:"fc9838", de:"Rückfallebene", article:"die", plural:"die Rückfallebenen", en:"fallback level", vi:"mức dự phòng", ex:"Als Rückfallebene liefern wir zwischengespeicherte Daten mit Zeitstempel aus.", exEn:"As a fallback we serve cached data with a timestamp.", ipa:"RÜK-fal-ee-be-ne", coll:"eine Rückfallebene vorsehen", tip:"Kopf: die Ebene → die. Im Team hört man *der Fallback*; *die Rückfallebene* klingt im Gespräch durchdachter.", topic:"Architecture", level:"C1" },
  { id:"fc9839", de:"Fachbereich", article:"der", plural:"die Fachbereiche", en:"business department", vi:"bộ phận nghiệp vụ", ex:"Das entscheidet nicht die IT, sondern der Fachbereich.", exEn:"That's not IT's decision but the business department's.", ipa:"FAKH-be-raykh", coll:"mit dem Fachbereich abstimmen", tip:"Kopf: der Bereich → der. In deutschen Firmen die Standardbezeichnung für die Seite, die weiß, *was* gebaut werden soll.", topic:"Workplace", level:"B2" },
  { id:"fc9840", de:"vermeintlich", article:"—", plural:"—", en:"supposedly, ostensibly", vi:"tưởng là", ex:"Der vermeintliche Netzwerkfehler war am Ende ein Zeitüberschreitungswert.", exEn:"The supposed network error turned out to be a timeout setting.", ipa:"fer-MAYNT-likh", coll:"der vermeintliche Fehler", tip:"Signalisiert: es sah so aus, war aber nicht so. Nicht *vermutlich* (probably) — *vermeintlich* enthält bereits die Korrektur.", topic:"Speaking", level:"C1" },
  { id:"fc9841", de:"Rückwärtskompatibilität", article:"die", plural:"—", en:"backward compatibility", vi:"tương thích ngược", ex:"Rückwärtskompatibilität heißt: Wir dürfen Felder ergänzen, aber keine entfernen.", exEn:"Backward compatibility means we may add fields but never remove them.", ipa:"RÜK-verts-kom-pa-ti-bi-li-teet", coll:"Rückwärtskompatibilität wahren", tip:"-tät → die, endbetont, kein Plural. Das längste Wort dieser Sammlung — und im API-Gespräch das meistgebrauchte.", topic:"API", level:"C1" },

  /* ---- vocabulary/ · die letzten sechs aus Pass 1 ---- */
  { id:"fc9842", de:"Server", article:"der", plural:"die Server", en:"server", vi:"máy chủ", ex:"Der Server läuft in einem Rechenzentrum in Frankfurt.", exEn:"The server runs in a data centre in Frankfurt.", ipa:"ZER-ver", coll:"auf dem Server laufen", tip:"Plural = Singular. Im Deutschen mit deutlichem *r* am Anfang gesprochen, nicht englisch. *das Rechenzentrum* ist das Wort fürs Data Centre.", topic:"Networking", level:"B1" },
  { id:"fc9843", de:"Client", article:"der", plural:"die Clients", en:"client", vi:"máy khách", ex:"Der Client wiederholt die Anfrage nach einem Fehler — mit wachsendem Abstand.", exEn:"The client retries the request after an error — with growing intervals.", ipa:"KLY-ent", coll:"der Client fragt an", tip:"Deutsch zweisilbig gesprochen: KLY-ent. Plural englisch mit *-s*. Gegenstück: der Server.", topic:"Networking", level:"B1" },
  { id:"fc9844", de:"Gruppe", article:"die", plural:"die Gruppen", en:"group", vi:"nhóm", ex:"Jede Gruppe hat eigene Rechte — der Nutzer erbt sie über die Mitgliedschaft.", exEn:"Each group has its own permissions — the user inherits them via membership.", ipa:"GRU-pe", coll:"einer Gruppe zuordnen", tip:"-e → die. Unter Linux liegen die Gruppen in */etc/group*; die Rechte kommen über die Mitgliedschaft, nicht über den Namen.", topic:"Linux", level:"B1" },
  { id:"fc9845", de:"starten", article:"—", plural:"—", en:"to start", vi:"khởi chạy", ex:"Wir starten den Container mit einem einzigen Befehl.", exEn:"We start the container with a single command.", ipa:"SHTAR-ten", coll:"einen Dienst starten", tip:"Schwach: startet, startete, gestartet — mit *haben* für die Handlung, mit *sein* für den Vorgang (*Der Dienst ist gestartet*).", topic:"Docker", level:"B1" },
  { id:"fc9846", de:"den Aufwand schätzen", article:"—", plural:"—", en:"to estimate the effort", vi:"ước lượng công sức", ex:"Lass uns den Aufwand gemeinsam schätzen, nicht jeder für sich.", exEn:"Let's estimate the effort together, not each of us separately.", ipa:"deen AUF-vant SHET-sen", coll:"den Aufwand grob schätzen", tip:"*der Aufwand* im Akkusativ → *den*. Gemeinsam schätzen ist der ganze Sinn von Planning Poker — die Zahl ist Nebensache, das Gespräch nicht.", topic:"Agile", level:"B2" },
]);
