/*! flashcards-12.js — Alltag-Nachschlag: Behörde, Bahn, Arzt, Einkauf, Wohnen (Đợt 9).
 * Harvested from the Alltag modules' vocabulary tables, each with a fresh example sentence.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- Behörde & Papierkram ---- */
  { id:"fc8101", de:"Bürgeramt", article:"das", plural:"die Bürgerämter", en:"citizens' office", vi:"phòng hành chính công dân", ex:"Für die Anmeldung brauchst du einen Termin beim Bürgeramt.", exEn:"For registration you need an appointment at the citizens' office.", ipa:"BÜR-ger-amt", coll:"einen Termin beim Bürgeramt buchen", tip:"Auch: das Bürgerbüro, das Einwohnermeldeamt — je nach Stadt.", topic:"Alltag", level:"B1" },
  { id:"fc8102", de:"Behördengang", article:"der", plural:"die Behördengänge", en:"trip to the authorities", vi:"chuyến đi làm giấy tờ", ex:"Den Behördengang habe ich auf einen Vormittag gelegt.", exEn:"I scheduled the trip to the authorities for one morning.", ipa:"be-HÖÖR-den-gang", coll:"einen Behördengang erledigen", tip:"Umlaut im Plural. Sammelbegriff für alles, was ein Amt verlangt.", topic:"Alltag", level:"B2" },
  { id:"fc8103", de:"Formular", article:"das", plural:"die Formulare", en:"form", vi:"biểu mẫu", ex:"Das Formular können Sie auch vorher online ausfüllen.", exEn:"You can also fill in the form online beforehand.", ipa:"for-mu-LAAR", coll:"ein Formular ausfüllen", tip:"*ausfüllen* für Formulare, nicht *schreiben*.", topic:"Alltag", level:"B1" },
  { id:"fc8104", de:"Nachweis", article:"der", plural:"die Nachweise", en:"proof, evidence", vi:"giấy chứng minh", ex:"Als Nachweis reicht der Mietvertrag.", exEn:"The tenancy agreement is sufficient as proof.", ipa:"NAAKH-vys", coll:"einen Nachweis erbringen", tip:"Behördendeutsch für „Beleg“. Verb: nachweisen.", topic:"Alltag", level:"B2" },
  { id:"fc8105", de:"Bescheinigung", article:"die", plural:"die Bescheinigungen", en:"certificate, confirmation", vi:"giấy xác nhận", ex:"Die Bescheinigung bekommst du direkt am Schalter.", exEn:"You get the certificate right at the counter.", ipa:"be-SHY-ni-gung", coll:"eine Bescheinigung ausstellen", tip:"-ung → die. Verb: bescheinigen.", topic:"Alltag", level:"B2" },
  { id:"fc8106", de:"Gebühr", article:"die", plural:"die Gebühren", en:"fee", vi:"lệ phí", ex:"Die Gebühr beträgt fünfzehn Euro, bar oder mit Karte.", exEn:"The fee is fifteen euros, cash or card.", ipa:"ge-BÜÜR", coll:"eine Gebühr erheben / zahlen", tip:"*betragen* ist das Verb für Beträge: „die Gebühr beträgt …“.", topic:"Alltag", level:"B1" },
  { id:"fc8107", de:"Schalter", article:"der", plural:"die Schalter", en:"counter, service desk", vi:"quầy giao dịch", ex:"Gehen Sie bitte zu Schalter drei.", exEn:"Please go to counter three.", ipa:"SHAL-ter", coll:"am Schalter warten", tip:"Plural = Singular. Auch: der Lichtschalter — gleicher Wortkörper, andere Welt.", topic:"Alltag", level:"B1" },
  { id:"fc8108", de:"Wartezeit", article:"die", plural:"die Wartezeiten", en:"waiting time", vi:"thời gian chờ", ex:"Die Wartezeit auf einen Termin beträgt derzeit drei Wochen.", exEn:"The wait for an appointment is currently three weeks.", ipa:"VAR-te-tsyt", coll:"mit einer Wartezeit rechnen", tip:"*mit etwas rechnen* = damit rechnen müssen.", topic:"Alltag", level:"B1" },
  { id:"fc8109", de:"Steuer-ID", article:"die", plural:"die Steuer-IDs", en:"tax identification number", vi:"mã số thuế", ex:"Die Steuer-ID kommt einige Wochen nach der Anmeldung per Post.", exEn:"The tax ID arrives by post a few weeks after registration.", ipa:"SHTOY-er-ii-DEE", coll:"die Steuer-ID angeben", tip:"Lebenslang gültig — sorgfältig ablegen. Auch: die Steueridentifikationsnummer.", topic:"Alltag", level:"B2" },
  { id:"fc8110", de:"Kirchensteuer", article:"die", plural:"die Kirchensteuern", en:"church tax", vi:"thuế nhà thờ", ex:"Wer keiner Kirche angehört, zahlt keine Kirchensteuer.", exEn:"Anyone not belonging to a church pays no church tax.", ipa:"KIR-khen-shtoy-er", coll:"Kirchensteuer zahlen", tip:"Wird bei der Anmeldung abgefragt — die Angabe hat direkte Gehaltsfolgen.", topic:"Alltag", level:"B2" },
  { id:"fc8111", de:"Anspruch", article:"der", plural:"die Ansprüche", en:"entitlement, claim", vi:"quyền lợi", ex:"Bei mehr als sechzig Minuten Verspätung besteht ein Anspruch auf Erstattung.", exEn:"With over sixty minutes' delay there's a claim to a refund.", ipa:"AN-shpruukh", coll:"einen Anspruch haben auf + Akk.", tip:"Umlaut im Plural. *Anspruch auf etwas haben* — immer mit Akkusativ.", topic:"Alltag", level:"B2" },

  /* ---- Bahn & Verkehr ---- */
  { id:"fc8112", de:"Fahrkarte", article:"die", plural:"die Fahrkarten", en:"ticket", vi:"vé tàu", ex:"Die Fahrkarte gilt nur für diesen Zug.", exEn:"The ticket is valid only for this train.", ipa:"FAAR-kar-te", coll:"eine Fahrkarte lösen", tip:"*eine Fahrkarte lösen* klingt förmlich, *kaufen* ist alltäglich.", topic:"Alltag", level:"B1" },
  { id:"fc8113", de:"Zugbindung", article:"die", plural:"die Zugbindungen", en:"train restriction on a ticket", vi:"ràng buộc chuyến tàu", ex:"Beim Sparpreis gilt Zugbindung — bei Verspätung entfällt sie.", exEn:"Saver fares carry a train restriction — it lapses if you're delayed.", ipa:"TSUUK-bin-dung", coll:"die Zugbindung entfällt", tip:"Wichtigste Regel für Sparpreise: Bei Verspätung darfst du den nächsten Zug nehmen.", topic:"Alltag", level:"B2" },
  { id:"fc8114", de:"Sparpreis", article:"der", plural:"die Sparpreise", en:"saver fare", vi:"vé giá rẻ", ex:"Der Sparpreis ist billiger, aber an einen bestimmten Zug gebunden.", exEn:"The saver fare is cheaper but tied to a specific train.", ipa:"SHPAAR-prys", coll:"einen Sparpreis buchen", tip:"Gegenstück: der Flexpreis, ohne Zugbindung.", topic:"Alltag", level:"B2" },
  { id:"fc8115", de:"Sitzplatzreservierung", article:"die", plural:"die -reservierungen", en:"seat reservation", vi:"đặt chỗ ngồi", ex:"Ohne Sitzplatzreservierung stehst du freitags oft im Gang.", exEn:"Without a seat reservation you often stand in the aisle on Fridays.", ipa:"ZITS-plats-re-zer-vee-rung", coll:"eine Sitzplatzreservierung buchen", tip:"Getrennt vom Ticket buchbar — auf Fernstrecken fast Pflicht.", topic:"Alltag", level:"B1" },
  { id:"fc8116", de:"Anschluss", article:"der", plural:"die Anschlüsse", en:"connection (train)", vi:"chuyến nối tiếp", ex:"Wenn wir zwanzig Minuten Verspätung haben, ist der Anschluss weg.", exEn:"With twenty minutes' delay we'll miss the connection.", ipa:"AN-shlus", coll:"den Anschluss verpassen", tip:"Umlaut im Plural. Auch technisch: der Netzanschluss.", topic:"Alltag", level:"B1" },
  { id:"fc8117", de:"Zugausfall", article:"der", plural:"die Zugausfälle", en:"train cancellation", vi:"chuyến tàu bị huỷ", ex:"Wegen eines Zugausfalls verschiebt sich alles um eine Stunde.", exEn:"Because of a cancellation everything shifts by an hour.", ipa:"TSUUK-aus-fal", coll:"ein Zugausfall wird angezeigt", tip:"Umlaut im Plural. Verwandt: der Stromausfall, der Systemausfall.", topic:"Alltag", level:"B2" },
  { id:"fc8118", de:"Schienenersatzverkehr", article:"der", plural:"—", en:"rail replacement service", vi:"xe buýt thay tàu", ex:"Zwischen Fulda und Kassel fährt Schienenersatzverkehr.", exEn:"There's a rail replacement service between Fulda and Kassel.", ipa:"SHEE-nen-er-zats-fer-keer", coll:"Schienenersatzverkehr einrichten", tip:"Oft abgekürzt SEV auf der Anzeigetafel — plane doppelte Fahrzeit ein.", topic:"Alltag", level:"B2" },
  { id:"fc8119", de:"Anzeigetafel", article:"die", plural:"die Anzeigetafeln", en:"departure board", vi:"bảng thông báo", ex:"Auf der Anzeigetafel steht Gleis neun statt Gleis sieben.", exEn:"The board shows platform nine instead of seven.", ipa:"AN-tsy-ge-taa-fel", coll:"auf die Anzeigetafel schauen", tip:"Gleiswechsel werden oft nur dort und per Durchsage angekündigt.", topic:"Alltag", level:"B1" },
  { id:"fc8120", de:"Bahnsteig", article:"der", plural:"die Bahnsteige", en:"platform", vi:"sân ga", ex:"Der Zug fährt heute von einem anderen Bahnsteig ab.", exEn:"The train departs from a different platform today.", ipa:"BAAN-shtyk", coll:"auf dem Bahnsteig warten", tip:"*das Gleis* ist die Nummer, *der Bahnsteig* der Ort — im Alltag oft synonym.", topic:"Alltag", level:"B1" },
  { id:"fc8121", de:"Erstattung", article:"die", plural:"die Erstattungen", en:"refund", vi:"hoàn tiền", ex:"Die Erstattung beantragst du online mit dem Fahrgastrechte-Formular.", exEn:"You apply for the refund online with the passenger-rights form.", ipa:"er-SHTA-tung", coll:"eine Erstattung beantragen", tip:"-ung → die. Verb: erstatten.", topic:"Alltag", level:"B2" },
  { id:"fc8122", de:"Streik", article:"der", plural:"die Streiks", en:"strike", vi:"đình công", ex:"Wegen eines Streiks fährt heute nur jeder dritte Zug.", exEn:"Because of a strike only every third train is running.", ipa:"SHTRYK", coll:"ein Streik wird angekündigt", tip:"Verb: streiken. Streiks werden in Deutschland meist Tage vorher angekündigt.", topic:"Alltag", level:"B1" },

  /* ---- Arzt & Gesundheit ---- */
  { id:"fc8123", de:"Krankenkasse", article:"die", plural:"die Krankenkassen", en:"health insurer", vi:"quỹ bảo hiểm y tế", ex:"Welche Krankenkasse haben Sie? — Die TK.", exEn:"Which health insurer do you have? — TK.", ipa:"KRAN-ken-ka-se", coll:"bei einer Krankenkasse versichert sein", tip:"Erste Frage in jeder Praxis, direkt nach dem Namen.", topic:"Alltag", level:"B1" },
  { id:"fc8124", de:"Sprechstunde", article:"die", plural:"die Sprechstunden", en:"consultation hours", vi:"giờ khám", ex:"Die offene Sprechstunde ist montags von acht bis zehn.", exEn:"Open consultation hours are Mondays eight to ten.", ipa:"SHPREKH-shtun-de", coll:"in die Sprechstunde kommen", tip:"*offene Sprechstunde* = ohne Termin, aber mit Wartezeit.", topic:"Alltag", level:"B1" },
  { id:"fc8125", de:"Überweisung", article:"die", plural:"die Überweisungen", en:"referral (also: bank transfer)", vi:"giấy chuyển khám", ex:"Für den Facharzt brauchen Sie eine Überweisung vom Hausarzt.", exEn:"For the specialist you need a referral from your GP.", ipa:"üü-ber-VY-zung", coll:"eine Überweisung ausstellen", tip:"Zwei Welten, ein Wort: Arzt-Überweisung und Bank-Überweisung.", topic:"Alltag", level:"B2" },
  { id:"fc8126", de:"Facharzt", article:"der", plural:"die Fachärzte", en:"specialist doctor", vi:"bác sĩ chuyên khoa", ex:"Beim Facharzt wartet man oft mehrere Wochen auf einen Termin.", exEn:"With a specialist you often wait weeks for an appointment.", ipa:"FAKH-artst", coll:"zum Facharzt überweisen", tip:"Umlaut im Plural. Gegenstück: der Hausarzt.", topic:"Alltag", level:"B1" },
  { id:"fc8127", de:"Beschwerde", article:"die", plural:"die Beschwerden", en:"complaint; (medical) symptom", vi:"triệu chứng; khiếu nại", ex:"Seit wann haben Sie diese Beschwerden?", exEn:"Since when have you had these symptoms?", ipa:"be-SHVEER-de", coll:"Beschwerden haben", tip:"Im Plural fast immer medizinisch; im Singular meist eine Reklamation.", topic:"Alltag", level:"B2" },

  /* ---- Einkauf, Pfand, Café ---- */
  { id:"fc8128", de:"Mehrwegflasche", article:"die", plural:"die Mehrwegflaschen", en:"reusable bottle", vi:"chai tái sử dụng", ex:"Mehrwegflaschen haben mehr Pfand als Einwegflaschen.", exEn:"Reusable bottles carry a higher deposit than single-use ones.", ipa:"MEER-veek-fla-she", coll:"Mehrweg statt Einweg", tip:"Der Pfandbetrag unterscheidet sich — deshalb der Aufdruck auf jeder Flasche.", topic:"Alltag", level:"B1" },
  { id:"fc8129", de:"Einwegflasche", article:"die", plural:"die Einwegflaschen", en:"single-use bottle", vi:"chai dùng một lần", ex:"Die Einwegflasche kommt in den Automaten, die Kiste nicht.", exEn:"The single-use bottle goes in the machine, the crate doesn't.", ipa:"AYN-veek-fla-she", coll:"Einwegpfand zurückgeben", tip:"Pfandautomaten nehmen fast nur Einweg — Mehrweg oft an der Kasse.", topic:"Alltag", level:"B1" },
  { id:"fc8130", de:"Umtausch", article:"der", plural:"—", en:"exchange, return of goods", vi:"đổi hàng", ex:"Ohne Kassenbon ist ein Umtausch schwierig.", exEn:"Without a receipt an exchange is difficult.", ipa:"UM-taush", coll:"einen Umtausch verlangen", tip:"Kein gesetzliches Recht auf Umtausch im Laden — Kulanz der Händler. Anders im Onlinehandel.", topic:"Alltag", level:"B2" },
  { id:"fc8131", de:"Kasse", article:"die", plural:"die Kassen", en:"checkout, till", vi:"quầy thu ngân", ex:"An der Kasse geht es in Deutschland schnell — pack zügig ein.", exEn:"Checkout is fast in Germany — pack quickly.", ipa:"KA-se", coll:"an der Kasse anstehen", tip:"Doppeldeutig: auch *die Krankenkasse* wird kurz *die Kasse* genannt.", topic:"Alltag", level:"B1" },
  { id:"fc8132", de:"Kleingeld", article:"das", plural:"—", en:"small change", vi:"tiền lẻ", ex:"Haben Sie es vielleicht klein? — Moment, ich schaue nach Kleingeld.", exEn:"Do you have it in change? — One moment, let me look.", ipa:"KLYN-gelt", coll:"Kleingeld dabeihaben", tip:"In Bäckereien und Kiosken oft noch nötig — Kartenzahlung ist nicht überall selbstverständlich.", topic:"Alltag", level:"B1" },
  { id:"fc8133", de:"Betrag", article:"der", plural:"die Beträge", en:"amount, sum", vi:"số tiền", ex:"Der Betrag wird sofort von Ihrem Konto abgebucht.", exEn:"The amount is debited from your account immediately.", ipa:"be-TRAAK", coll:"einen Betrag überweisen", tip:"Umlaut im Plural. Verb: betragen — „die Gebühr beträgt …“.", topic:"Alltag", level:"B1" },
  { id:"fc8134", de:"Rechnung", article:"die", plural:"die Rechnungen", en:"bill, invoice", vi:"hoá đơn", ex:"Die Rechnung, bitte — zusammen oder getrennt?", exEn:"The bill, please — together or separately?", ipa:"REKH-nung", coll:"die Rechnung bitten / begleichen", tip:"Im Restaurant fragt die Bedienung fast immer: *zusammen oder getrennt?*", topic:"Alltag", level:"B1" },
  { id:"fc8135", de:"Bedienung", article:"die", plural:"die Bedienungen", en:"server, waiting staff", vi:"nhân viên phục vụ", ex:"Die Bedienung kommt gleich zu Ihnen.", exEn:"The server will be with you shortly.", ipa:"be-DEE-nung", coll:"die Bedienung rufen", tip:"Auch: die Bedienung eines Geräts. Im Lokal ruft man nicht *Fräulein*, sondern hebt kurz die Hand.", topic:"Alltag", level:"B1" },
  { id:"fc8136", de:"Apfelschorle", article:"die", plural:"die Apfelschorlen", en:"apple juice with sparkling water", vi:"nước táo pha soda", ex:"Für mich eine Apfelschorle, bitte.", exEn:"An apple spritzer for me, please.", ipa:"AP-fel-shor-le", coll:"eine Apfelschorle bestellen", tip:"Das deutsche Standardgetränk, wenn man nichts Alkoholisches will.", topic:"Alltag", level:"B1" },
  { id:"fc8137", de:"Biergarten", article:"der", plural:"die Biergärten", en:"beer garden", vi:"quán bia ngoài trời", ex:"Im Biergarten darf man an vielen Orten eigenes Essen mitbringen.", exEn:"In many beer gardens you may bring your own food.", ipa:"BEER-gar-ten", coll:"in den Biergarten gehen", tip:"Umlaut im Plural. Die Selbstbedienung ist dort die Regel.", topic:"Alltag", level:"B1" },
  { id:"fc8138", de:"Bäckerei", article:"die", plural:"die Bäckereien", en:"bakery", vi:"tiệm bánh mì", ex:"In der Bäckerei sagt man *ein belegtes Brötchen*, nicht *ein Sandwich*.", exEn:"At the bakery you say 'ein belegtes Brötchen', not 'a sandwich'.", ipa:"be-ke-RY", coll:"in die Bäckerei gehen", tip:"Regional: Brötchen, Semmel, Schrippe, Weck — dasselbe Gebäck, vier Namen.", topic:"Alltag", level:"B1" },
  { id:"fc8139", de:"Filterkaffee", article:"der", plural:"—", en:"filter coffee", vi:"cà phê phin giấy", ex:"Wenn die Maschine spinnt, gibt es Filterkaffee aus der Kanne.", exEn:"When the machine plays up, there's filter coffee from the pot.", ipa:"FIL-ter-ka-fee", coll:"Filterkaffee aufsetzen", tip:"In der Büroküche der Rückfallmodus — und ein sicheres Smalltalk-Thema.", topic:"Alltag", level:"B1" },
  { id:"fc8140", de:"Kanne", article:"die", plural:"die Kannen", en:"pot, carafe", vi:"bình", ex:"Probier mal die Kanne da hinten, die ist frisch.", exEn:"Try the pot back there, it's fresh.", ipa:"KA-ne", coll:"eine Kanne aufsetzen", tip:"Auch: die Teekanne, die Gießkanne.", topic:"Alltag", level:"B1" },

  /* ---- Wohnen & Umzug ---- */
  { id:"fc8141", de:"Umzug", article:"der", plural:"die Umzüge", en:"move (house or office)", vi:"cuộc chuyển nhà", ex:"Seit dem Umzug ins neue Büro stehen die Kartons im Flur.", exEn:"Since the move to the new office the boxes have been in the corridor.", ipa:"UM-tsuuk", coll:"einen Umzug planen", tip:"Umlaut im Plural. Verb: umziehen — trennbar, mit *sein*.", topic:"Alltag", level:"B1" },
  { id:"fc8142", de:"Karton", article:"der", plural:"die Kartons", en:"cardboard box", vi:"thùng carton", ex:"Die Kartons stehen seit zwei Wochen im Flur.", exEn:"The boxes have been in the hallway for two weeks.", ipa:"kar-TONG", coll:"einen Karton packen", tip:"Auch *die Kiste* — Kiste ist stabiler, Karton aus Pappe.", topic:"Alltag", level:"B1" },
  { id:"fc8143", de:"Flur", article:"der", plural:"die Flure", en:"corridor, hallway", vi:"hành lang", ex:"Im Flur darf nichts stehen — das ist ein Fluchtweg.", exEn:"Nothing may stand in the corridor — it's an escape route.", ipa:"FLUUR", coll:"auf dem Flur stehen", tip:"Nicht verwechseln mit *die Flur* (Feldflur) — im Alltag praktisch immer maskulin.", topic:"Alltag", level:"B1" },
  { id:"fc8144", de:"Techniker", article:"der", plural:"die Techniker", en:"technician", vi:"kỹ thuật viên", ex:"Der Techniker kommt wohl erst morgen.", exEn:"The technician probably won't come until tomorrow.", ipa:"TEKH-ni-ker", coll:"einen Techniker bestellen", tip:"Plural = Singular. Bei Handwerkerterminen gilt oft nur ein Zeitfenster, keine Uhrzeit.", topic:"Alltag", level:"B1" },
  { id:"fc8145", de:"Bauarbeiten", article:"die", plural:"(nur Plural)", en:"construction work", vi:"công trình xây dựng", ex:"Wegen Bauarbeiten ist die Straße gesperrt.", exEn:"The road is closed due to construction work.", ipa:"BAU-ar-by-ten", coll:"wegen Bauarbeiten gesperrt", tip:"Nur Plural — wie *die Ferien* und *die Kosten*.", topic:"Alltag", level:"B1" },

  /* ---- Smalltalk, Wetter, Freizeit ---- */
  { id:"fc8146", de:"Smalltalk", article:"der", plural:"—", en:"small talk", vi:"chuyện phiếm", ex:"Fünf Minuten Smalltalk in der Küche sind normal, zwanzig nicht.", exEn:"Five minutes of small talk in the kitchen is normal, twenty isn't.", ipa:"SMOOL-tok", coll:"Smalltalk machen", tip:"Sichere Themen: Wochenende, Wetter, Urlaub, Kaffee. Nicht: Gehalt, Politik.", topic:"Alltag", level:"B1" },
  { id:"fc8147", de:"Halbzeit", article:"die", plural:"die Halbzeiten", en:"half (of a match); halfway point", vi:"hiệp đấu; nửa chặng", ex:"In der zweiten Halbzeit ist noch ein Tor gefallen.", exEn:"Another goal was scored in the second half.", ipa:"HALP-tsyt", coll:"in der zweiten Halbzeit", tip:"*ein Tor fällt* — im Deutschen fällt das Tor, es wird nicht gemacht.", topic:"Alltag", level:"B1" },
  { id:"fc8148", de:"Tor", article:"das", plural:"die Tore", en:"goal; gate", vi:"bàn thắng; cổng", ex:"Das entscheidende Tor fiel in der letzten Minute.", exEn:"The decisive goal came in the last minute.", ipa:"TOOR", coll:"ein Tor schießen / ein Tor fällt", tip:"Achtung: *der Tor* (veraltet: Narr) ist ein anderes Wort — im Alltag immer *das Tor*.", topic:"Alltag", level:"B1" },
  { id:"fc8149", de:"Hagel", article:"der", plural:"—", en:"hail", vi:"mưa đá", ex:"Gestern gab es kurz Hagel, danach war es wieder sonnig.", exEn:"There was brief hail yesterday, then it was sunny again.", ipa:"HAA-gel", coll:"es hagelt", tip:"Wetterverben sind unpersönlich: *es hagelt, es schneit, es regnet*.", topic:"Alltag", level:"B1" },
  { id:"fc8150", de:"Schwimmbad", article:"das", plural:"die Schwimmbäder", en:"swimming pool", vi:"bể bơi", ex:"Am Wochenende waren wir mit den Kindern im Schwimmbad.", exEn:"At the weekend we were at the pool with the children.", ipa:"SHVIM-baat", coll:"ins Schwimmbad gehen", tip:"Umlaut im Plural. Richtung mit *ins*, Ort mit *im*.", topic:"Alltag", level:"B1" },
  { id:"fc8151", de:"Begegnung", article:"die", plural:"die Begegnungen", en:"encounter", vi:"cuộc gặp gỡ", ex:"Kurze Begegnungen im Flur sind der Kern des Büroalltags.", exEn:"Brief encounters in the corridor are the core of office life.", ipa:"be-GEEG-nung", coll:"eine zufällige Begegnung", tip:"-ung → die. Verb: jemandem begegnen (+ Dativ).", topic:"Alltag", level:"B2" },
  { id:"fc8152", de:"Augenkontakt", article:"der", plural:"—", en:"eye contact", vi:"giao tiếp bằng mắt", ex:"Beim Anstoßen ist Augenkontakt üblich — sonst wirkt es unhöflich.", exEn:"Eye contact when clinking glasses is customary — otherwise it seems rude.", ipa:"AU-gen-kon-takt", coll:"Augenkontakt halten", tip:"Beim *Prost* schaut man einander an, nicht auf die Gläser.", topic:"Culture", level:"B2" },
  { id:"fc8153", de:"Ironie", article:"die", plural:"—", en:"irony", vi:"sự mỉa mai", ex:"Ironie funktioniert im deutschen Büro seltener, als man denkt.", exEn:"Irony works less often in a German office than you'd think.", ipa:"i-ro-NEE", coll:"Ironie verstehen", tip:"Schriftlich fast nie zuverlässig lesbar — im Chat besser weglassen.", topic:"Culture", level:"B2" },
  { id:"fc8154", de:"Aberglaube", article:"der", plural:"—", en:"superstition", vi:"mê tín", ex:"Vorher zu gratulieren gilt als Aberglaube — man tut es einfach nicht.", exEn:"Congratulating in advance counts as superstition — you simply don't.", ipa:"AA-ber-glau-be", coll:"an Aberglauben glauben", tip:"Konkret: Zum Geburtstag nie vorher gratulieren.", topic:"Culture", level:"B2" }
]);
