/*! flashcards-11.js — Goethe C1, Interview-Banken & Alltag-Nachschlag (Đợt 9).
 * Merges onto window.FLASHCARDS.
 */
window.FLASHCARDS = (window.FLASHCARDS || []).concat([
  /* ---- Goethe C1 · Lesen & Hören ---- */
  { id:"fc8001", de:"Modellsatz", article:"der", plural:"die Modellsätze", en:"official sample paper", vi:"đề mẫu chính thức", ex:"Lade den aktuellen Modellsatz C1 von goethe.de herunter.", exEn:"Download the current C1 sample paper from goethe.de.", ipa:"mo-DEL-zats", coll:"den Modellsatz durcharbeiten", tip:"Immer zuerst — Formate werden gelegentlich überarbeitet.", topic:"Exam", level:"C1" },
  { id:"fc8002", de:"Aussagekraft", article:"die", plural:"—", en:"validity, informative value", vi:"tính thuyết phục", ex:"Die freiwillige Teilnahme schränkt die Aussagekraft ein.", exEn:"Voluntary participation limits the validity.", ipa:"AUS-zaa-ge-kraft", coll:"die Aussagekraft einschränken", tip:"Häufig in C1-Sachtexten, fast immer im Zusammenhang mit Kritik an Studien.", topic:"Exam", level:"C1" },
  { id:"fc8003", de:"Befund", article:"der", plural:"die Befunde", en:"finding", vi:"kết quả nghiên cứu", ex:"Die Befunde sind bemerkenswert einheitlich.", exEn:"The findings are remarkably consistent.", ipa:"be-FUNT", coll:"die Befunde zeigen", tip:"Neutraler als *Ergebnis* und typisch für wissenschaftliche Prosa.", topic:"Exam", level:"C1" },
  { id:"fc8004", de:"Umformulierung", article:"die", plural:"die -formulierungen", en:"paraphrase", vi:"diễn đạt lại", ex:"Die richtige Antwort ist fast immer eine Umformulierung des Textes.", exEn:"The correct answer is almost always a paraphrase of the text.", ipa:"UM-for-mu-lee-rung", coll:"eine Umformulierung erkennen", tip:"Die Kernkompetenz im C1-Lesen — wörtliche Nähe ist ein Warnsignal.", topic:"Exam", level:"C1" },
  { id:"fc8006", de:"verpuffen", article:"—", plural:"—", en:"to fizzle out", vi:"tan biến vô ích", ex:"Ohne bessere Organisation verpufft der Effekt binnen Monaten.", exEn:"Without better organisation the effect fizzles out within months.", ipa:"fer-PU-fen", coll:"der Effekt verpufft", tip:"Bildhaft und sehr häufig in Kommentaren und Interviews.", topic:"Exam", level:"C1" },
  { id:"fc8007", de:"belastbar", article:"—", plural:"—", en:"robust, resilient", vi:"vững chắc", ex:"Es wird sich zeigen, wie belastbar diese Überzeugungen sind.", exEn:"It will show how robust these convictions are.", ipa:"be-LAST-baar", coll:"belastbare Zahlen", tip:"Doppelbedeutung: belastbare Daten (robust) und ein belastbarer Mensch (resilient).", topic:"Exam", level:"C1" },
  { id:"fc8008", de:"gleichwohl", article:"—", plural:"—", en:"nevertheless", vi:"tuy vậy", ex:"Die Kritik ist berechtigt; gleichwohl bleibt der Befund bestehen.", exEn:"The criticism is valid; nevertheless the finding stands.", ipa:"glykh-VOOL", coll:"gleichwohl gilt …", tip:"Gehobenes *trotzdem*. Signalwort für eine Einschränkung.", topic:"Exam", level:"C1" },
  { id:"fc8009", de:"nicht zuletzt", article:"—", plural:"—", en:"not least", vi:"không kém phần", ex:"Nicht zuletzt deshalb wurde das Projekt gestoppt.", exEn:"Not least for that reason the project was stopped.", ipa:"nikht TSU-letst", coll:"nicht zuletzt deshalb", tip:"Abstufung, keine Ausschließlichkeit — genau hier setzen Distraktoren an.", topic:"Exam", level:"C1" },
  { id:"fc8010", de:"Zuständigkeit", article:"die", plural:"die Zuständigkeiten", en:"responsibility, remit", vi:"phạm vi trách nhiệm", ex:"In den erfolgreichen Fällen wurden zugleich die Zuständigkeiten geklärt.", exEn:"In the successful cases responsibilities were clarified at the same time.", ipa:"TSUU-shten-dikh-kyt", coll:"Zuständigkeiten klären", tip:"Nicht dasselbe wie *Verantwortung* — Zuständigkeit ist formal zugewiesen.", topic:"Workplace", level:"C1" },

  /* ---- Goethe C1 · Schreiben ---- */
  { id:"fc8011", de:"Stellungnahme", article:"die", plural:"die Stellungnahmen", en:"position statement", vi:"ý kiến chính thức", ex:"Nehmen Sie in einer kurzen Stellungnahme dazu Position.", exEn:"Take a position on this in a short statement.", ipa:"SHTEL-lung-naa-me", coll:"eine Stellungnahme abgeben", tip:"Die häufigste Textsorte im C1-Schreiben.", topic:"Exam", level:"C1" },
  { id:"fc8012", de:"Entkräftung", article:"die", plural:"die Entkräftungen", en:"refutation", vi:"phản bác", ex:"Nach der Gegenposition folgt die Entkräftung.", exEn:"The refutation follows the opposing position.", ipa:"ent-KREF-tung", coll:"zur Entkräftung anführen", tip:"Der Block, den schwache C1-Texte weglassen.", topic:"Exam", level:"C1" },
  { id:"fc8013", de:"Aufgabenerfüllung", article:"die", plural:"—", en:"task achievement", vi:"mức hoàn thành đề bài", ex:"Die Aufgabenerfüllung wird pro Text bewertet.", exEn:"Task achievement is assessed per text.", ipa:"AUF-gaa-ben-er-fül-lung", coll:"die Aufgabenerfüllung prüfen", tip:"Eigene Bewertungsposition — ein fehlender Teilauftrag kostet mehr als drei Grammatikfehler.", topic:"Exam", level:"C1" },
  { id:"fc8014", de:"Teilauftrag", article:"der", plural:"die Teilaufträge", en:"sub-task in a prompt", vi:"phần nhiệm vụ", ex:"Hake jeden Teilauftrag ab, statt ihn zu schätzen.", exEn:"Tick off every sub-task instead of guessing.", ipa:"TYL-auf-traak", coll:"einen Teilauftrag abhaken", tip:"Der erste Prüfdurchgang gilt nur diesen.", topic:"Exam", level:"C1" },
  { id:"fc8015", de:"Übertragbarkeit", article:"die", plural:"—", en:"transferability", vi:"khả năng áp dụng", ex:"Die Übertragbarkeit auf Präsenzberufe ist begrenzt.", exEn:"Transferability to on-site professions is limited.", ipa:"ÜÜ-ber-traak-baar-kyt", coll:"die Übertragbarkeit einschränken", tip:"Standardargument in Erörterungen — merken als Block.", topic:"Exam", level:"C1" },
  { id:"fc8016", de:"einwenden", article:"—", plural:"—", en:"to object", vi:"phản đối", ex:"Dagegen ließe sich einwenden, dass die Kosten steigen.", exEn:"One could object that costs would rise.", ipa:"AYN-ven-den", coll:"dagegen einwenden", tip:"*Dagegen ließe sich einwenden* ist die eleganteste Einleitung der Gegenposition.", topic:"Exam", level:"C1" },
  { id:"fc8017", de:"entkräften", article:"—", plural:"—", en:"to refute, to weaken", vi:"bác bỏ", ex:"Dieses Argument lässt sich mit einem Beispiel entkräften.", exEn:"This argument can be refuted with an example.", ipa:"ent-KREF-ten", coll:"ein Argument entkräften", tip:"Entkräften heißt einschränken, nicht lächerlich machen.", topic:"Exam", level:"C1" },
  { id:"fc8018", de:"erproben", article:"—", plural:"—", en:"to trial, to test out", vi:"thử nghiệm", ex:"Unternehmen erproben seit Jahren eine verkürzte Arbeitswoche.", exEn:"Companies have been trialling a shorter week for years.", ipa:"er-PROO-ben", coll:"ein Modell erproben", tip:"Gehobener als *ausprobieren*, typisch für Sachtexte.", topic:"Exam", level:"C1" },
  { id:"fc8019", de:"greifbar", article:"—", plural:"—", en:"tangible, graspable", vi:"dễ nắm bắt", ex:"Der praktische Teil hat den Stoff greifbarer gemacht.", exEn:"The practical part made the material more tangible.", ipa:"GRYF-baar", coll:"etwas greifbar machen", tip:"Nützlich in Rückmeldungen und Bewertungen.", topic:"Exam", level:"C1" },
  { id:"fc8020", de:"Präsenzpflicht", article:"die", plural:"die -pflichten", en:"mandatory on-site presence", vi:"bắt buộc có mặt", ex:"In Bereichen mit Präsenzpflicht lässt sich die Zeit kaum verkürzen.", exEn:"Where on-site presence is mandatory, hours can hardly be cut.", ipa:"pre-ZENTS-flikht", coll:"der Präsenzpflicht unterliegen", tip:"Standardgegenargument in Arbeitszeitdebatten.", topic:"Workplace", level:"C1" },

  /* ---- Goethe C1 · Sprechen ---- */
  { id:"fc8021", de:"Ausgangslage", article:"die", plural:"die Ausgangslagen", en:"starting situation", vi:"tình hình xuất phát", ex:"Zunächst zur Ausgangslage: Die Versuche zeigen ein einheitliches Bild.", exEn:"First to the starting situation: the trials show a consistent picture.", ipa:"AUS-gangs-laa-ge", coll:"zur Ausgangslage", tip:"Idealer erster Gliederungspunkt eines C1-Vortrags.", topic:"Exam", level:"C1" },
  { id:"fc8022", de:"Einschätzung", article:"die", plural:"die Einschätzungen", en:"assessment", vi:"đánh giá", ex:"Abschließend zu meiner eigenen Einschätzung.", exEn:"Finally, to my own assessment.", ipa:"AYN-shet-sung", coll:"eine Einschätzung abgeben", tip:"Weicher als *Meinung* und im Vortrag üblicher.", topic:"Exam", level:"C1" },
  { id:"fc8023", de:"Redeanteil", article:"der", plural:"die Redeanteile", en:"share of speaking time", vi:"thời lượng nói", ex:"Nicht der Redeanteil ist die Note, sondern die Qualität der Beiträge.", exEn:"Speaking time isn't the grade; the quality of contributions is.", ipa:"REE-de-an-tyl", coll:"den Redeanteil ausgleichen", tip:"Zwei gute Züge wiegen mehr als vier Minuten Redefluss.", topic:"Exam", level:"C1" },
  { id:"fc8024", de:"Themenhoheit", article:"die", plural:"—", en:"control of the topic", vi:"quyền dẫn dắt chủ đề", ex:"Wer aktiv abgibt, behält die Themenhoheit.", exEn:"Whoever hands over actively keeps control of the topic.", ipa:"TEE-men-hoo-hyt", coll:"die Themenhoheit behalten", tip:"*Soweit von meiner Seite — wie siehst du das?* ist genau dieser Zug.", topic:"Exam", level:"C1" },
  { id:"fc8025", de:"anknüpfen an", article:"—", plural:"—", en:"to pick up on", vi:"tiếp nối", ex:"Du hast die Präsenzberufe genannt — daran würde ich anknüpfen.", exEn:"You mentioned on-site professions — I'd pick up on that.", ipa:"AN-knüp-fen an", coll:"an einen Punkt anknüpfen", tip:"Trennbar, mit Dativ. Der wichtigste Interaktionszug im Sprechmodul.", topic:"Exam", level:"C1" },
  { id:"fc8026", de:"bündeln", article:"—", plural:"—", en:"to bundle, to sum up", vi:"gộp lại", ex:"Wir sind uns offenbar einig, dass … Unterschiedlich sehen wir …", exEn:"We evidently agree that … We differ on …", ipa:"BÜN-deln", coll:"eine Diskussion bündeln", tip:"Der stärkste Schlusszug: zeigt in einem Satz, dass du alles überblickt hast.", topic:"Exam", level:"C1" },
  { id:"fc8027", de:"abwägen", article:"—", plural:"—", en:"to weigh up", vi:"cân nhắc", ex:"Ein C1-Vortrag wägt ab, statt eine Seite zu vertreten.", exEn:"A C1 talk weighs up rather than championing one side.", ipa:"AP-vee-gen", coll:"Argumente abwägen", tip:"Nomen: die Abwägung. Kernbegriff für Schreiben und Sprechen.", topic:"Exam", level:"C1" },
  { id:"fc8028", de:"übertragbar", article:"—", plural:"—", en:"transferable", vi:"có thể áp dụng", ex:"Das Modell ist nicht auf jede Branche übertragbar.", exEn:"The model isn't transferable to every sector.", ipa:"üü-ber-TRAAK-baar", coll:"auf etwas übertragbar sein", tip:"Häufiges Einschränkungsargument — in Prüfungstexten und im Gespräch.", topic:"Exam", level:"C1" },

  /* ---- Interview · HR & Behavioral ---- */
  { id:"fc8029", de:"Zeithorizont", article:"der", plural:"die Zeithorizonte", en:"time horizon", vi:"tầm nhìn thời gian", ex:"Wir wollten dasselbe, hatten aber unterschiedliche Zeithorizonte im Kopf.", exEn:"We wanted the same thing but had different time horizons in mind.", ipa:"TSYT-ho-ri-tsont", coll:"denselben Zeithorizont haben", tip:"Erklärt viele Konflikte, ohne jemandem die Schuld zu geben.", topic:"Career", level:"C1" },
  { id:"fc8030", de:"Kriterienraster", article:"das", plural:"die Kriterienraster", en:"criteria grid", vi:"bảng tiêu chí", ex:"Wir haben zuerst ein Kriterienraster aufgeschrieben, dann bewertet.", exEn:"We wrote down a criteria grid first, then evaluated.", ipa:"kri-TEE-ri-en-ras-ter", coll:"ein Kriterienraster aufstellen", tip:"Löst Architekturstreit, ohne dass jemand nachgeben muss.", topic:"Career", level:"C1" },
  { id:"fc8031", de:"mitschleppen", article:"—", plural:"—", en:"to carry along unresolved", vi:"để dây dưa", ex:"Wir haben das drei Sprints lang mitgeschleppt.", exEn:"We carried it unresolved for three sprints.", ipa:"MIT-shlep-pen", coll:"ein Thema mitschleppen", tip:"Trennbar, umgangssprachlich, sehr präzise für ungelöste Konflikte.", topic:"Career", level:"C1" },
  { id:"fc8032", de:"nachgeben", article:"—", plural:"—", en:"to give in", vi:"nhượng bộ", ex:"… ohne dass einer von uns nur nachgibt, um Ruhe zu haben.", exEn:"… without either of us giving in just for peace.", ipa:"NAAKH-gee-ben", coll:"einem Argument nachgeben", tip:"Trennbar. Nachgeben ≠ überzeugt werden — der Unterschied zählt in der Antwort.", topic:"Career", level:"B2" },
  { id:"fc8033", de:"sich verkneifen", article:"—", plural:"—", en:"to hold back (a remark)", vi:"nén lại", ex:"Die Erklärung habe ich mir verkniffen und stattdessen nachgefragt.", exEn:"I held back the explanation and asked instead.", ipa:"zikh fer-KNY-fen", coll:"sich eine Bemerkung verkneifen", tip:"Genau der Reflex, den man beim Kritikannehmen unterdrücken muss.", topic:"Career", level:"C1" },
  { id:"fc8034", de:"beliebig", article:"—", plural:"—", en:"arbitrary, without a stance", vi:"tuỳ tiện", ex:"Wer jede Kritik kommentarlos umsetzt, wirkt beliebig.", exEn:"Someone who implements every criticism without comment seems arbitrary.", ipa:"be-LEE-bikh", coll:"beliebig wirken", tip:"Starkes Wort in der Selbstdarstellung: das Gegenteil von Profil haben.", topic:"Career", level:"C1" },
  { id:"fc8035", de:"umkehrbar", article:"—", plural:"—", en:"reversible", vi:"có thể đảo ngược", ex:"Ich sortiere danach, was umkehrbar ist und was nicht.", exEn:"I sort by what's reversible and what isn't.", ipa:"UM-keer-baar", coll:"eine umkehrbare Entscheidung", tip:"Das nützlichste Priorisierungskriterium — und es klingt nach Betriebserfahrung.", topic:"Career", level:"C1" },
  { id:"fc8036", de:"liegen bleiben", article:"—", plural:"—", en:"to be left undone", vi:"bị bỏ lại", ex:"Was kostet Vertrauen, wenn es liegen bleibt?", exEn:"What costs trust if it's left undone?", ipa:"LEE-gen BLY-ben", coll:"eine Aufgabe bleibt liegen", tip:"Trennbar in der Bedeutung, aber zwei Wörter geschrieben.", topic:"Workplace", level:"B2" },

  /* ---- Interview · System Design ---- */
  { id:"fc8037", de:"Größenordnung", article:"die", plural:"die Größenordnungen", en:"order of magnitude", vi:"bậc độ lớn", ex:"Reden wir über hundert Zahlungen pro Minute oder über zehntausend?", exEn:"Are we talking a hundred payments a minute or ten thousand?", ipa:"GRÖÖ-sen-ord-nung", coll:"die Größenordnung klären", tip:"Erste Klärungsfrage jeder Design-Aufgabe.", topic:"Architecture", level:"C1" },
  { id:"fc8039", de:"Auslastung", article:"die", plural:"die Auslastungen", en:"utilisation, load", vi:"mức tải", ex:"Ohne Zahlen zur aktuellen Auslastung ist jede Antwort geraten.", exEn:"Without figures on current utilisation any answer is a guess.", ipa:"AUS-las-tung", coll:"die Auslastung messen", tip:"-ung → die. Unterscheide von *die Last* (die Größe selbst).", topic:"Architecture", level:"B2" },
  { id:"fc8042", de:"Obergrenze", article:"die", plural:"die Obergrenzen", en:"cap, upper limit", vi:"giới hạn trên", ex:"Wiederholung mit wachsendem Abstand und einer Obergrenze.", exEn:"Backoff with a cap.", ipa:"OO-ber-gren-tse", coll:"eine Obergrenze festlegen", tip:"Gegenstück: die Untergrenze.", topic:"Architecture", level:"B2" },
  { id:"fc8043", de:"Doppelbuchung", article:"die", plural:"die Doppelbuchungen", en:"duplicate booking", vi:"ghi trùng", ex:"Idempotente Endpunkte verhindern Doppelbuchungen.", exEn:"Idempotent endpoints prevent duplicate bookings.", ipa:"DO-pel-buu-khung", coll:"eine Doppelbuchung vermeiden", tip:"Die Klärungsfrage dazu: Was ist schlimmer — doppelt oder verzögert?", topic:"Architecture", level:"B2" },
  { id:"fc8044", de:"überschlagen", article:"—", plural:"—", en:"to estimate roughly", vi:"ước lượng nhanh", ex:"Ich überschlage das kurz: zehntausend mal ein Kilobyte sind zehn Megabyte.", exEn:"Let me estimate: ten thousand times one kilobyte is ten megabytes.", ipa:"üü-ber-SHLAA-gen", coll:"eine Zahl überschlagen", tip:"Der Satz kauft Zeit und zeigt Methode gleichzeitig.", topic:"Architecture", level:"C1" },
  { id:"fc8045", de:"aufstauen (sich)", article:"—", plural:"—", en:"to pile up", vi:"dồn ứ", ex:"Die Zeitüberschreitung soll kurz sein, damit sich keine Verbindungen aufstauen.", exEn:"The timeout should be short so connections don't pile up.", ipa:"AUF-shtau-en", coll:"Verbindungen stauen sich auf", tip:"Trennbar und reflexiv. Verwandt: der Rückstau.", topic:"Architecture", level:"C1" },
  { id:"fc8046", de:"rückgängig machen", article:"—", plural:"—", en:"to reverse, to undo", vi:"hoàn tác", ex:"Das Aufteilen der Daten ist schwer rückgängig zu machen.", exEn:"Sharding the data is hard to reverse.", ipa:"RÜK-gen-gikh MA-khen", coll:"eine Entscheidung rückgängig machen", tip:"Ordne Skalierungsschritte nach genau diesem Kriterium.", topic:"Architecture", level:"B2" },

  /* ---- Interview · Gehalt & Vertrag ---- */
  { id:"fc8047", de:"Ausschlusskriterium", article:"das", plural:"die -kriterien", en:"deal-breaker", vi:"điều kiện loại trừ", ex:"Ein Ausschlusskriterium ist es nicht — mir geht es nicht nur um die Fixzahl.", exEn:"It's not a deal-breaker — it isn't only about the base figure.", ipa:"AUS-shlus-kri-tee-ri-um", coll:"ein Ausschlusskriterium sein", tip:"Nie mit Ja beantworten, bevor das Paket besprochen ist.", topic:"Career", level:"C1" },
  { id:"fc8048", de:"Spielraum", article:"der", plural:"die Spielräume", en:"room for manoeuvre", vi:"dư địa", ex:"Dürfte ich fragen, wo genau Ihr Spielraum liegt?", exEn:"May I ask where exactly your room for manoeuvre lies?", ipa:"SHPEEL-raum", coll:"Spielraum haben", tip:"Umlaut im Plural. Höflicher als „Wie viel geht noch?“.", topic:"Career", level:"C1" },
  { id:"fc8049", de:"Karenzentschädigung", article:"die", plural:"die -entschädigungen", en:"non-compete compensation", vi:"tiền bù không cạnh tranh", ex:"Ein nachvertragliches Wettbewerbsverbot ist ohne Karenzentschädigung nicht wirksam.", exEn:"A post-contractual non-compete is ineffective without compensation.", ipa:"ka-RENTS-ent-shee-di-gung", coll:"eine Karenzentschädigung zahlen", tip:"Steht die Klausel im Vertrag, ausdrücklich nachfragen.", topic:"Career", level:"C1" },
  { id:"fc8050", de:"Wettbewerbsverbot", article:"das", plural:"die -verbote", en:"non-compete clause", vi:"điều khoản không cạnh tranh", ex:"Das Wettbewerbsverbot regelt, wofür du nach dem Austritt arbeiten darfst.", exEn:"The non-compete governs whom you may work for after leaving.", ipa:"VET-be-verps-fer-boot", coll:"einem Wettbewerbsverbot unterliegen", tip:"Nachvertraglich nur mit Karenzentschädigung wirksam.", topic:"Career", level:"C1" },
  { id:"fc8051", de:"Nebentätigkeit", article:"die", plural:"die Nebentätigkeiten", en:"secondary employment", vi:"công việc phụ", ex:"Nebentätigkeiten sind häufig genehmigungspflichtig.", exEn:"Secondary work often requires approval.", ipa:"NEE-ben-tee-tikh-kyt", coll:"eine Nebentätigkeit anzeigen", tip:"Für öffentliche Open-Source-Arbeit unbedingt vorher prüfen.", topic:"Career", level:"C1" },
  { id:"fc8052", de:"Rückzahlungsklausel", article:"die", plural:"die -klauseln", en:"repayment clause", vi:"điều khoản hoàn trả", ex:"Die Rückzahlungsklausel gilt, wenn ich innerhalb von zwei Jahren kündige.", exEn:"The repayment clause applies if I resign within two years.", ipa:"RÜK-tsaa-lungs-klau-zel", coll:"unter eine Rückzahlungsklausel fallen", tip:"Üblich bei bezahlten Zertifizierungen — Bindungsdauer und Betrag prüfen.", topic:"Career", level:"C1" },
  { id:"fc8053", de:"Bindungsfrist", article:"die", plural:"die Bindungsfristen", en:"commitment period", vi:"thời gian ràng buộc", ex:"Ist das Weiterbildungsbudget an eine Bindungsfrist geknüpft?", exEn:"Is the training budget tied to a commitment period?", ipa:"BIN-dungs-frist", coll:"an eine Bindungsfrist geknüpft sein", tip:"Die Frage, die man vor der Zertifizierung stellt, nicht danach.", topic:"Career", level:"C1" },
  { id:"fc8054", de:"Mehrarbeit", article:"die", plural:"—", en:"overtime (formal term)", vi:"làm thêm giờ", ex:"„Mehrarbeit ist mit dem Gehalt abgegolten“ heißt: unbezahlt.", exEn:"'Overtime is covered by the salary' means: unpaid.", ipa:"MEER-ar-byt", coll:"Mehrarbeit leisten", tip:"Vertragsdeutsch für *Überstunden* — dieselbe Sache, formellerer Begriff.", topic:"Career", level:"C1" },
  { id:"fc8055", de:"abgelten", article:"—", plural:"—", en:"to compensate for, to cover", vi:"bù đắp trọn gói", ex:"Mehrarbeit ist mit dem Gehalt abgegolten.", exEn:"Overtime is covered by the salary.", ipa:"AP-gel-ten", coll:"mit dem Gehalt abgegolten sein", tip:"Partizip: abgegolten. Fast nur in Verträgen — und dort entscheidend.", topic:"Career", level:"C1" },
  { id:"fc8056", de:"vergüten", article:"—", plural:"—", en:"to remunerate", vi:"trả công", ex:"Wie wird die Rufbereitschaft vergütet?", exEn:"How is on-call duty remunerated?", ipa:"fer-GÜÜ-ten", coll:"eine Leistung vergüten", tip:"Nomen: die Vergütung. Formeller als *bezahlen*.", topic:"Career", level:"C1" },

  /* ---- Interview · Live-Coding ---- */
  { id:"fc8057", de:"Randfall", article:"der", plural:"die Randfälle", en:"edge case", vi:"trường hợp biên", ex:"Als Randfälle würde ich die leere Liste und einen einzigen Eintrag prüfen.", exEn:"As edge cases I'd check the empty list and a single entry.", ipa:"RANT-fal", coll:"Randfälle abdecken", tip:"Ungefragt nennen — die meisten warten, bis gefragt wird.", topic:"Software Development", level:"B2" },
  { id:"fc8058", de:"Laufzeit", article:"die", plural:"die Laufzeiten", en:"runtime complexity", vi:"độ phức tạp thời gian", ex:"Die Laufzeit ist linear, weil ich die Liste einmal durchgehe.", exEn:"Runtime is linear because I traverse the list once.", ipa:"LAUF-tsyt", coll:"die Laufzeit angeben", tip:"O(n) = linear, O(n²) = quadratisch, O(log n) = logarithmisch, O(1) = konstant.", topic:"Software Development", level:"B2" },
  { id:"fc8059", de:"Speicherbedarf", article:"der", plural:"—", en:"memory footprint", vi:"dung lượng bộ nhớ cần", ex:"Der Speicherbedarf ist ebenfalls linear.", exEn:"The memory footprint is linear as well.", ipa:"SHPY-kher-be-darf", coll:"den Speicherbedarf senken", tip:"Gehört immer in die Antwort — nicht nur die Laufzeit.", topic:"Software Development", level:"B2" },
  { id:"fc8060", de:"Denkstand", article:"der", plural:"—", en:"current state of one's thinking", vi:"mạch suy nghĩ hiện tại", ex:"Ich lege kurz meinen Denkstand offen: Ich weiß, dass ich … brauche.", exEn:"Let me expose my current thinking: I know I need …", ipa:"DENK-shtant", coll:"den Denkstand offenlegen", tip:"Stufe 1 beim Feststecken — vor dem Bitten um einen Hinweis.", topic:"Software Development", level:"C1" },
  { id:"fc8062", de:"abdecken", article:"—", plural:"—", en:"to cover (a case)", vi:"bao phủ", ex:"Damit ist abgedeckt, dass die Liste leer sein kann.", exEn:"That covers the case of an empty list.", ipa:"AP-de-ken", coll:"einen Fall abdecken", tip:"Trennbar. Nomen: die Testabdeckung.", topic:"Testing", level:"B2" },
  { id:"fc8063", de:"feststecken", article:"—", plural:"—", en:"to be stuck", vi:"bị tắc", ex:"Feststecken ist normal — bewertet wird, wie du feststeckst.", exEn:"Being stuck is normal — what's graded is how you get stuck.", ipa:"FEST-shte-ken", coll:"an einer Stelle feststecken", tip:"Trennbar. Umgangssprachlich auch: *ich hänge*.", topic:"Software Development", level:"B2" },
  { id:"fc8064", de:"Eintrag", article:"der", plural:"die Einträge", en:"entry, item", vi:"mục, phần tử", ex:"Reden wir über tausend Einträge oder zehn Millionen?", exEn:"Are we talking a thousand entries or ten million?", ipa:"AYN-traak", coll:"einen Eintrag hinzufügen", tip:"Umlaut im Plural. Auch: der Logeintrag, der Kalendereintrag.", topic:"Software Development", level:"B2" }
]);
