#!/usr/bin/env node
/*!
 * build.js — bundles every Markdown file under /content into js/content-bundle.js
 * so the app loads instantly via a plain <script> tag (works over GitHub Pages,
 * a local server, OR by double-clicking index.html — no fetch/CORS needed).
 *
 * Usage:  node build.js
 * Re-run whenever you add or edit Markdown in /content.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const CONTENT = path.join(ROOT, 'content');
const OUT = path.join(ROOT, 'js', 'content-bundle.js');

function walk(dir) {
  let files = [];
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) files = files.concat(walk(full));
    else if (name.endsWith('.md')) files.push(full);
  }
  return files;
}

if (!fs.existsSync(CONTENT)) {
  console.error('No /content directory found at ' + CONTENT);
  process.exit(1);
}

const files = walk(CONTENT).sort();
const map = {};
let totalChars = 0;
for (const full of files) {
  const key = path.relative(CONTENT, full).replace(/\\/g, '/').replace(/\.md$/, '');
  const content = fs.readFileSync(full, 'utf8');
  map[key] = content;
  totalChars += content.length;
}

const banner =
  '/*! content-bundle.js — GENERATED by build.js.\n' +
  ' * Do NOT edit by hand. Edit the Markdown in /content and run:  node build.js\n' +
  ' * Generated: ' + new Date().toISOString() + '\n' +
  ' * Modules: ' + files.length + '  ·  ~' + Math.round(totalChars / 1000) + 'k chars\n' +
  ' */\n';

fs.writeFileSync(OUT, banner + 'window.CONTENT_BUNDLE = ' + JSON.stringify(map) + ';\n', 'utf8');

console.log('✓ Bundled ' + files.length + ' Markdown modules → js/content-bundle.js');
Object.keys(map).sort().forEach(k => console.log('   · ' + k + '  (' + map[k].length + ' chars)'));
