#!/usr/bin/env node
/*!
 * build.js — bundles every Markdown file under /content into js/content-bundle.js
 * so the app loads instantly via a plain <script> tag (works over GitHub Pages,
 * a local server, OR by double-clicking index.html — no fetch/CORS needed).
 *
 * Usage:  node build.js
 * Re-run whenever you add or edit Markdown in /content.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const CONTENT = path.join(ROOT, 'content');
const OUT = path.join(ROOT, 'js', 'content-bundle.js');
const INDEX = path.join(ROOT, 'index.html');

function walk(dir) {
  let files = [];
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) files = files.concat(walk(full));
    else if (name.endsWith('.md')) files.push(full);
  }
  return files;
}

if (!fs.existsSync(CONTENT)) {
  console.error('No /content directory found at ' + CONTENT);
  process.exit(1);
}

const files = walk(CONTENT).sort();
const map = {};
let totalChars = 0;
for (const full of files) {
  const key = path.relative(CONTENT, full).replace(/\\/g, '/').replace(/\.md$/, '');
  const content = fs.readFileSync(full, 'utf8');
  map[key] = content;
  totalChars += content.length;
}

const json = JSON.stringify(map);

// Content hash → cache-busting version. Changes whenever any Markdown changes,
// so browsers (and the GitHub Pages CDN) always fetch the fresh bundle instead
// of serving a stale copy that is missing newly-added modules.
const version = crypto.createHash('sha1').update(json).digest('hex').slice(0, 10);

const banner =
  '/*! content-bundle.js — GENERATED by build.js.\n' +
  ' * Do NOT edit by hand. Edit the Markdown in /content and run:  node build.js\n' +
  ' * Generated: ' + new Date().toISOString() + '\n' +
  ' * Version: ' + version + '\n' +
  ' * Modules: ' + files.length + '  ·  ~' + Math.round(totalChars / 1000) + 'k chars\n' +
  ' */\n';

fs.writeFileSync(OUT, banner + 'window.CONTENT_BUNDLE = ' + json + ';\n', 'utf8');

// Stamp the cache-busting version onto the <script> tag in index.html so a
// rebuilt bundle is never masked by a cached one. (Query string is ignored for
// local file:// double-click use, so that path keeps working too.)
if (fs.existsSync(INDEX)) {
  const html = fs.readFileSync(INDEX, 'utf8');
  const tag = /(src=")js\/content-bundle\.js(?:\?v=[^"]*)?(")/;
  if (!tag.test(html)) {
    console.warn('! Could not find content-bundle.js <script> tag in index.html to stamp.');
  } else {
    const stamped = html.replace(tag, '$1js/content-bundle.js?v=' + version + '$2');
    if (stamped !== html) {
      fs.writeFileSync(INDEX, stamped, 'utf8');
      console.log('✓ Stamped index.html → content-bundle.js?v=' + version);
    } else {
      console.log('· index.html already at content-bundle.js?v=' + version);
    }
  }
}

console.log('✓ Bundled ' + files.length + ' Markdown modules → js/content-bundle.js  (v=' + version + ')');
Object.keys(map).sort().forEach(k => console.log('   · ' + k + '  (' + map[k].length + ' chars)'));
